"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { SecondarySidebar } from "@/components/layout/secondary-sidebar";
import { useLocale } from "@/components/locale-provider";
import { activateWorkflow,deactivateWorkflow,deleteWorkflow,duplicateWorkflow,listWorkflows,type Workflow } from "@/lib/api/workflows";
import { Icons } from "@/components/layout/icons";

export default function WorkflowsPage(){const{label}=useLocale();const[rows,setRows]=useState<Workflow[]>([]);const[q,setQ]=useState("");const[scope,setScope]=useState("all");const[busy,setBusy]=useState<string|null>(null);const load=()=>void listWorkflows(scope==="all"?undefined:scope).then(setRows).catch(()=>setRows([]));useEffect(load,[scope]);const visible=useMemo(()=>rows.filter(r=>r.name.toLowerCase().includes(q.toLowerCase())),[rows,q]);
 const toggle=async(r:Workflow)=>{setBusy(r.id);try{const next=r.status==="ACTIVE"?await deactivateWorkflow(r.id):await activateWorkflow(r.id);setRows(a=>a.map(x=>x.id===r.id?{...x,...next}:x))}finally{setBusy(null)}};const remove=async(r:Workflow)=>{if(!window.confirm(label("workflows.confirmDelete")))return;setBusy(r.id);try{await deleteWorkflow(r.id);setRows(a=>a.filter(x=>x.id!==r.id))}finally{setBusy(null)}};const duplicate=async(r:Workflow)=>{setBusy(r.id);try{const copy=await duplicateWorkflow(r.id);setRows(a=>[copy,...a])}finally{setBusy(null)}};
 return <div className="flex min-h-0 flex-1 bg-[#f6f8fb]"><SecondarySidebar section="workflows"/><main className="min-w-0 flex-1 overflow-y-auto"><header className="border-b border-slate-200 bg-white px-6 py-5"><div className="flex flex-wrap items-end justify-between gap-4"><div><div className="text-[9.5px] font-bold uppercase tracking-[.15em] text-slate-400">Workflows</div><h1 className="mt-1 text-[20px] font-semibold tracking-tight text-slate-900">{label("workflows.title")}</h1><p className="mt-1 max-w-xl text-[11.5px] leading-5 text-slate-500">{label("workflows.description")}</p></div><Link href="/files/workflows/builder" className="rounded-lg bg-[#1B66EA] px-4 py-2.5 text-[11px] font-semibold text-white shadow-sm">+ {label("workflows.create")}</Link></div></header><div className="border-b border-slate-200 bg-white px-6 py-3"><div className="flex flex-wrap items-center gap-2"><div className="flex min-w-[280px] flex-1 items-center gap-2 rounded-lg border border-slate-200 px-3 py-2.5"><Icons.search size={14}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={label("workflows.search")} className="min-w-0 flex-1 text-[11.5px] outline-none"/></div>{[["all",label("workflows.all")],["mine",label("workflows.mine")],["drafts",label("workflows.drafts")]].map(([v,t])=><button key={v} onClick={()=>setScope(v)} className={`rounded-lg px-3 py-2 text-[10.5px] ${scope===v?"bg-[#EEF4FF] font-semibold text-[#1B66EA]":"border border-slate-200 text-slate-600"}`}>{t}</button>)}<Link href="/files/workflows/tasks" className="rounded-lg border border-slate-200 px-3 py-2 text-[10.5px] text-slate-600">{label("workflows.waiting")}</Link><Link href="/files/workflows/runs" className="rounded-lg border border-slate-200 px-3 py-2 text-[10.5px] text-slate-600">{label("workflows.runs")}</Link></div></div>
 {visible.length===0?<div className="p-8"><div className="mx-auto max-w-2xl rounded-xl border border-dashed border-slate-300 bg-white p-12 text-center"><div className="mx-auto flex h-11 w-11 items-center justify-center rounded-xl bg-blue-50 text-[#1B66EA]"><Icons.flow size={22}/></div><h2 className="mt-4 text-[14px] font-semibold text-slate-900">{label("workflows.empty")}</h2><p className="mx-auto mt-1 max-w-md text-[11px] leading-5 text-slate-500">{label("workflows.description")}</p><Link href="/files/workflows/builder" className="mt-4 inline-flex rounded-lg bg-[#1B66EA] px-4 py-2 text-[11px] font-semibold text-white">{label("workflows.create")}</Link></div></div>:<div className="p-6"><div className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-[0_1px_2px_rgba(15,23,42,.03)]"><div className="grid grid-cols-[minmax(260px,1.8fr)_120px_110px_100px_170px] border-b border-slate-100 bg-[#fbfcfe] px-4 py-3 text-[9px] font-bold uppercase tracking-wider text-slate-400"><div>Workflow</div><div>Status</div><div>Mode</div><div>States</div><div className="text-end">Actions</div></div>{visible.map(r=>{const actions=(r.steps.find(s=>s.kind==="ACTIONS")?.config.value as Array<{type:string}>)||[];return <div key={r.id} className="group grid grid-cols-[minmax(260px,1.8fr)_120px_110px_100px_170px] items-center border-b border-slate-100 px-4 py-3 last:border-0 hover:bg-[#fbfcff]"><div className="min-w-0"><Link href={`/files/workflows/builder?id=${r.id}`} className="block truncate text-[12px] font-semibold text-slate-800 hover:text-[#1B66EA]">{r.name}</Link><div className="mt-0.5 truncate text-[10px] text-slate-400">{r.description||label("workflows.noDescription")} · {r.resourceType}</div></div><div><span className={`rounded-full px-2 py-1 text-[9px] font-semibold ${r.status==="ACTIVE"?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-600"}`}>{r.status}</span></div><div className="text-[10px] text-slate-500">{r.mode}</div><div className="text-[10px] text-slate-500">{r.states.length} · {actions.length} actions</div><div className="flex justify-end gap-1"><Link href={`/files/workflows/builder?id=${r.id}`} className="rounded-md border border-slate-200 px-2 py-1.5 text-[9.5px] text-slate-600">Edit</Link><button disabled={busy===r.id} onClick={()=>void toggle(r)} className="rounded-md border border-slate-200 px-2 py-1.5 text-[9.5px] text-slate-600">{r.status==="ACTIVE"?"Disable":"Enable"}</button><button disabled={busy===r.id} onClick={()=>void duplicate(r)} className="rounded-md border border-slate-200 px-2 py-1.5 text-[9.5px] text-slate-600">⋯</button><button disabled={busy===r.id} onClick={()=>void remove(r)} className="rounded-md border border-red-100 px-2 py-1.5 text-[9.5px] text-red-500">×</button></div></div>})}</div></div>}
 </main></div>}
