import { ForbiddenException, Injectable, NotFoundException } from '@nestjs/common'; import { PrismaService } from '../prisma/prisma.service'; import { NotificationsService } from '../notifications/notifications.service'; import type { AccessTokenPayload } from '../auth/jwt.types';
@Injectable() export class CommentsService { constructor(private readonly prisma:PrismaService, private readonly notifications:NotificationsService){}
 async list(u:AccessTokenPayload,fileId:string){const f=await this.prisma.file.findFirst({where:{id:fileId,orgId:u.org_id,deletedAt:null},include:{folder:true}}); if(!f)throw new NotFoundException('File not found'); return this.prisma.comment.findMany({where:{orgId:u.org_id,fileId,parentId:null,deletedAt:null},include:{user:{select:{id:true,name:true,email:true}},replies:{where:{deletedAt:null},include:{user:{select:{id:true,name:true,email:true}}},orderBy:{createdAt:'asc'}}},orderBy:{createdAt:'asc'}})}
 async add(u:AccessTokenPayload,fileId:string,body:string,parentId?:string){if(!body.trim()||body.length>5000)throw new ForbiddenException('Invalid comment'); const f=await this.prisma.file.findFirst({where:{id:fileId,orgId:u.org_id,deletedAt:null}});if(!f)throw new NotFoundException('File not found'); if(parentId){const parent=await this.prisma.comment.findFirst({where:{id:parentId,orgId:u.org_id,fileId,deletedAt:null},select:{userId:true}}); if(!parent) throw new NotFoundException('Parent comment not found');} const c=await this.prisma.comment.create({data:{orgId:u.org_id,fileId,userId:u.sub,body:body.trim(),parentId:parentId||null},include:{user:{select:{id:true,name:true,email:true}}}});
 const file=await this.prisma.file.findFirst({where:{id:fileId,orgId:u.org_id,deletedAt:null},select:{ownerId:true,name:true}});
 const targets=new Set<string>(); if(file?.ownerId && file.ownerId!==u.sub) targets.add(file.ownerId); if(parentId){ const parent=await this.prisma.comment.findFirst({where:{id:parentId,orgId:u.org_id},select:{userId:true}}); if(parent?.userId && parent.userId!==u.sub) targets.add(parent.userId); }
 const tokens=[...body.matchAll(/@([A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,})/g)].map(m=>m[1].toLowerCase());
 await this.prisma.fileActivity.create({data:{orgId:u.org_id,fileId,userId:u.sub,action:'COMMENT',metadata:{commentId:c.id,parentId:parentId||null,mentions:tokens}}});
 const mentioned= tokens.length ? await this.prisma.user.findMany({where:{email:{in:tokens},memberships:{some:{orgId:u.org_id}}},select:{id:true,email:true}}) : [];
 mentioned.forEach(x=>{if(x.id!==u.sub) targets.add(x.id);});
 const mentionedIds=new Set(mentioned.map(x=>x.id));
 await Promise.all([...targets].map(userId=>this.notifications.createOfficeNotification({userId,orgId:u.org_id,category:'collaboration',type:mentionedIds.has(userId)?'MENTION':'COMMENT',title:mentionedIds.has(userId)?'You were mentioned in a file comment':'New file comment',body:`${c.user?.name||c.user?.email||'A collaborator'} commented on ${file?.name||'a file'}${mentionedIds.has(userId)?' and mentioned you':''}.`,resourceType:'FILE',resourceId:fileId,priority:mentionedIds.has(userId)?'HIGH':'NORMAL'})));
 return c;}
 async update(u:AccessTokenPayload,id:string,body:string){if(!body.trim()||body.length>5000)throw new ForbiddenException('Invalid comment'); const c=await this.prisma.comment.findFirst({where:{id,orgId:u.org_id,deletedAt:null}});if(!c)throw new NotFoundException('Comment not found');if(c.userId!==u.sub&&u.role!=='ADMIN'&&u.role!=='SUPER_ADMIN')throw new ForbiddenException('Not allowed');return this.prisma.comment.update({where:{id},data:{body:body.trim(),editedAt:new Date()}});}
 async remove(u:AccessTokenPayload,id:string){const c=await this.prisma.comment.findFirst({where:{id,orgId:u.org_id,deletedAt:null}});if(!c)throw new NotFoundException('Comment not found');if(c.userId!==u.sub&&u.role!=='ADMIN'&&u.role!=='SUPER_ADMIN')throw new ForbiddenException('Not allowed');const now=new Date();await this.prisma.comment.updateMany({where:{OR:[{id},{parentId:id}]},data:{deletedAt:now}});return {ok:true};}
}
