'use client';
import type { WriterBlock } from './model';
export function WriterToolbar({activeBlock,onCommand,onBlockType,onAlign,onDirection,onInsertTable,onInsertImage,onPageBreak,onPageSettings,onLink,onFontFamily,onFontSize,onColor,onHighlight,onVerticalAlign,onList,onTableAction,onRule,onIndent,onOutdent,onToc,onBookmark,onFootnote,onEndnote,onFind,onColumns,onSectionBreak,onHeaderFooter,onEquation,onSymbol,onCitation,onBibliography,onAutoIndex,onCaption,onCrossReference,onIndex,onImageOptions,onTableOptions}:{activeBlock:WriterBlock|null;onCommand:(c:'bold'|'italic'|'underline'|'strike')=>void;onBlockType:(t:WriterBlock['type'])=>void;onAlign:(a:WriterBlock['align'])=>void;onDirection:(d:NonNullable<WriterBlock['direction']>)=>void;onInsertTable:()=>void;onInsertImage:()=>void;onPageBreak:()=>void;onPageSettings:()=>void;onLink:()=>void;onFontFamily:(v:string)=>void;onFontSize:(v:number)=>void;onColor:(v:string)=>void;onHighlight:(v:string)=>void;onVerticalAlign:(v:'baseline'|'superscript'|'subscript')=>void;onList:(ordered:boolean)=>void;onTableAction:(a:'add-row'|'remove-row'|'add-col'|'remove-col'|'borders')=>void;onRule:()=>void;onIndent:()=>void;onOutdent:()=>void;onToc:()=>void;onBookmark:()=>void;onFootnote:()=>void;onEndnote:()=>void;onFind:()=>void;onColumns:(v:number)=>void;onSectionBreak:()=>void;onHeaderFooter:()=>void;onEquation:()=>void;onSymbol:()=>void;onCitation:()=>void;onBibliography:()=>void;onAutoIndex:()=>void;onCaption:()=>void;onCrossReference:()=>void;onIndex:()=>void;onImageOptions:()=>void;onTableOptions:()=>void}){
 const button=(label:any,title:string,fn?:()=>void)=> <button type="button" title={title} onMouseDown={e=>e.preventDefault()} onClick={fn} className="rounded-md px-2 py-1.5 text-xs hover:bg-slate-100">{label}</button>;
 const isTable=activeBlock?.type==='table';
 return <div className="flex min-h-11 flex-wrap items-center gap-1 border-b border-slate-200 bg-white px-4 py-1.5">
  <select title="Font" onChange={e=>onFontFamily(e.target.value)} className="w-28 rounded-md border border-slate-200 px-2 py-1.5 text-xs"><option>Arial</option><option>Tahoma</option><option>Times New Roman</option><option>Georgia</option><option>Courier New</option></select>
  <select title="Font size" onChange={e=>onFontSize(Number(e.target.value))} className="w-16 rounded-md border border-slate-200 px-2 py-1.5 text-xs"><option value="11">11</option><option value="12">12</option><option value="14">14</option><option value="16">16</option><option value="18">18</option><option value="24">24</option><option value="32">32</option></select>
  {button(<b>B</b>,'Bold',()=>onCommand('bold'))}{button(<i>I</i>,'Italic',()=>onCommand('italic'))}{button(<u>U</u>,'Underline',()=>onCommand('underline'))}{button(<s>S</s>,'Strikethrough',()=>onCommand('strike'))}
  <input type="color" title="Text color" onChange={e=>onColor(e.target.value)} className="h-7 w-8 rounded border-0"/><input type="color" title="Highlight" defaultValue="#fff59d" onChange={e=>onHighlight(e.target.value)} className="h-7 w-8 rounded border-0"/>
  {button('x²','Superscript',()=>onVerticalAlign('superscript'))}{button('x₂','Subscript',()=>onVerticalAlign('subscript'))}{button('x','Baseline',()=>onVerticalAlign('baseline'))}
  <span className="mx-1 h-6 w-px bg-slate-200"/>
  <select aria-label="Paragraph style" value={activeBlock?.type==='title'||activeBlock?.type==='subtitle'||activeBlock?.type?.startsWith('heading')?activeBlock.type:'paragraph'} onChange={e=>onBlockType(e.target.value as WriterBlock['type'])} className="rounded-md border border-slate-200 px-2 py-1.5 text-xs"><option value="paragraph">Normal</option><option value="heading1">Heading 1</option><option value="heading2">Heading 2</option><option value="heading3">Heading 3</option></select>
  {button('•','Bulleted list',()=>onList(false))}{button('1.','Numbered list',()=>onList(true))}
  {button('←','Outdent',onOutdent)}{button('→','Indent',onIndent)}{button('L','Align left',()=>onAlign('start'))}{button('C','Center',()=>onAlign('center'))}{button('R','Align right',()=>onAlign('end'))}{button('J','Justify',()=>onAlign('justify'))}{button('LTR','Left-to-right',()=>onDirection('ltr'))}{button('RTL','Right-to-left',()=>onDirection('rtl'))}{button('↔','Auto direction',()=>onDirection('auto'))}
  <span className="mx-1 h-6 w-px bg-slate-200"/>{button('Table','Insert table',onInsertTable)}{button('Row +','Add row',()=>onTableAction('add-row'))}{button('Row −','Remove row',()=>onTableAction('remove-row'))}{button('Col +','Add column',()=>onTableAction('add-col'))}{button('Col −','Remove column',()=>onTableAction('remove-col'))}{button(isTable?'Borders':'Image','Toggle borders / image',isTable?()=>onTableAction('borders'):onInsertImage)}
  {button('Link','Insert link',onLink)}{button('Cols','Columns',()=>onColumns(2))}{button('Section','Section break',onSectionBreak)}{button('Header','Header / Footer',onHeaderFooter)}{button('∑','Equation',onEquation)}{button('Ω','Symbol',onSymbol)}{button('Cite','Citation',onCitation)}{button('Bib','Bibliography',onBibliography)}{button('Index','Build index',onAutoIndex)}{button('Caption','Caption',onCaption)}{button('Ref','Cross reference',onCrossReference)}{button('Index','Index entry',onIndex)}{button('TOC','Table of contents',onToc)}{button('Bookmark','Bookmark',onBookmark)}{button('Footnote','Footnote',onFootnote)}{button('Endnote','Endnote',onEndnote)}{button('Find','Find / Replace',onFind)}{button('Rule','Horizontal rule',onRule)}{button('Page break','Insert page break',onPageBreak)}{button('Image','Image layout',onImageOptions)}{button('Table','Table options',onTableOptions)}{button('Page','Page settings',onPageSettings)}
 </div>;
}
