ALTER TABLE `file_share_recipients` ADD COLUMN `permission` ENUM('VIEW','COMMENT','EDIT','ORGANIZE','FULL_ACCESS') NOT NULL DEFAULT 'VIEW';
ALTER TABLE `folder_share_recipients` ADD COLUMN `permission` ENUM('VIEW','COMMENT','EDIT','ORGANIZE','FULL_ACCESS') NOT NULL DEFAULT 'VIEW';
