import { getApiBaseUrl } from './client'; import { getToken } from './jwt'; import { emitGlobalToast } from '../global-toast';
export type SessionRecord={id:string;createdAt:string;lastSeenAt:string;expiresAt:string;ipAddress?:string|null;userAgent?:string|null;deviceId?:string|null;isCurrent?:boolean};
async function request<T>(path:string,init:RequestInit={}):Promise<T>{const token=getToken();const response=await fetch(`${getApiBaseUrl()}${path}`,{...init,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})}});if(!response.ok)throw new Error((await response.text())||'Request failed');return response.json() as Promise<T>}
export type ProfileRecord = { id: string; name: string | null; email: string; avatarUrl?: string | null; status?: string };
export async function updateProfile(input: { name?: string; avatarUrl?: string | null }): Promise<ProfileRecord> { const result = await request<ProfileRecord>('/auth/profile', { method: 'POST', body: JSON.stringify(input) }); emitGlobalToast({ message: input.avatarUrl !== undefined ? 'Profile photo updated' : 'Profile updated', messageAr: input.avatarUrl !== undefined ? 'تم تحديث صورة الملف الشخصي' : 'تم تحديث الملف الشخصي' }); return result; }
export async function changePassword(currentPassword:string,newPassword:string){ const result=await request<{ok:boolean}>('/auth/change-password',{method:'POST',body:JSON.stringify({currentPassword,newPassword})}); emitGlobalToast({message:'Password updated',messageAr:'تم تحديث كلمة المرور'}); return result; }
export const listSessions=()=>request<SessionRecord[]>('/auth/sessions'); export async function revokeSession(id:string){ const result=await request<{ok:boolean}>(`/auth/sessions/${id}`,{method:'DELETE'}); emitGlobalToast({message:'Session revoked',messageAr:'تم إلغاء الجلسة'}); return result; } export async function logoutAllSessions(){ const result=await request<{ok:boolean}>('/auth/logout-all',{method:'POST'}); emitGlobalToast({message:'Other sessions signed out',messageAr:'تم تسجيل الخروج من الجلسات الأخرى'}); return result; }

export type SecurityEventRecord={id:string;severity:string;eventType:string;ipAddress?:string|null;metadata?:unknown;createdAt:string};
export const listSecurityEvents=()=>request<SecurityEventRecord[]>('/auth/security-events');
