"use client";
import { useEffect, useState } from 'react';
import { Modal } from './modal';
import { useLocale } from './locale-provider';
import { attachWorkspaceLabel, createWorkspaceLabel, detachWorkspaceLabel, listWorkspaceLabels, listWorkspaceLabelResources, type WorkspaceLabel } from '../lib/api/workspace-labels';

const LABEL_COLORS = ['#159B68','#38C98A','#4388E8','#69BD35','#929292','#75D3B4','#9696F8','#9CC9EA','#9CDDE0','#A875D8','#B36B4C','#A9D46A','#B795F4','#C7B8C0','#C9A8B0','#C45CE0','#D86A62','#ED7BA4','#F04432','#F5C94C','#F04E3D','#F6E66C','#FA6B24','#FFA22C'];

export function LabelAssignmentModal({target,onClose,onChanged}:{target:{type:'FILE'|'FOLDER';id:string;name:string};onClose:()=>void;onChanged:()=>void}){
 const {locale}=useLocale();const ar=locale==='ar';const [labels,setLabels]=useState<WorkspaceLabel[]>([]);const [selected,setSelected]=useState<Set<string>>(new Set());const [initial,setInitial]=useState<Set<string>>(new Set());const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [createOpen,setCreateOpen]=useState(false);const [newName,setNewName]=useState('');const [newColor,setNewColor]=useState(LABEL_COLORS[0]);
 useEffect(()=>{let live=true;void listWorkspaceLabels().then(async rows=>({rows,resources:await Promise.all(rows.map(l=>listWorkspaceLabelResources(l.id).then(r=>({id:l.id,has:r.some(x=>x.resourceType===target.type&&x.resourceId===target.id)}))))})).then(detail=>{if(!live)return;setLabels(detail.rows);const ids=new Set(detail.resources.filter(x=>x.has).map(x=>x.id));setSelected(ids);setInitial(ids)}).catch(()=>setError(ar?'تعذر تحميل التصنيفات':'Could not load labels'));return()=>{live=false}},[target.id,target.type,ar]);
 const save=async()=>{setBusy(true);setError('');try{for(const l of labels){const before=initial.has(l.id),after=selected.has(l.id);if(before===after)continue;if(after)await attachWorkspaceLabel(l.id,target.type,target.id);else await detachWorkspaceLabel(l.id,target.type,target.id)}onChanged();onClose()}catch(e){setError(e instanceof Error?e.message:(ar?'تعذر حفظ التصنيفات':'Could not save labels'))}finally{setBusy(false)}};
 const create=async()=>{if(!newName.trim())return;setBusy(true);setError('');try{const label=await createWorkspaceLabel(newName.trim(),newColor);await attachWorkspaceLabel(label.id,target.type,target.id);setLabels(rows=>[...rows,label]);setSelected(rows=>new Set([...rows,label.id]));setInitial(rows=>new Set([...rows,label.id]));setCreateOpen(false);setNewName('');onChanged()}catch(e){setError(e instanceof Error?e.message:(ar?'تعذر إنشاء التصنيف':'Could not create label'))}finally{setBusy(false)}};
 return <>
  <Modal title={ar?'تصنيف العنصر':'Label As'} onClose={onClose} footer={<><button className="imkan-button-secondary" onClick={onClose}>{ar?'إلغاء':'Cancel'}</button><button className="imkan-button" disabled={busy} onClick={()=>void save()}>{busy?(ar?'جارٍ الحفظ':'Saving…'):(ar?'حفظ':'Save')}</button></>}>
   <div className="mb-3 text-[11px] text-slate-500">{target.name}</div>{error?<div className="mb-2 text-[11px] text-red-600">{error}</div>:null}
   <div className="max-h-72 space-y-1 overflow-auto">{labels.length===0?<div className="py-6 text-center text-[11px] text-slate-400">{ar?'لا توجد تصنيفات بعد':'No labels yet'}</div>:labels.map(l=><label key={l.id} className="flex cursor-pointer items-center gap-2 rounded-lg px-2 py-2 hover:bg-slate-50"><input type="checkbox" checked={selected.has(l.id)} onChange={e=>setSelected(prev=>{const n=new Set(prev);e.target.checked?n.add(l.id):n.delete(l.id);return n})}/><span className="h-3 w-3 rounded-[2px]" style={{background:l.color}}/><span className="text-[12px] text-slate-700">{l.name}</span></label>)}</div>
   <button type="button" onClick={()=>{setNewName('');setNewColor(LABEL_COLORS[0]);setCreateOpen(true)}} className="mt-3 flex w-full items-center gap-2 border-t border-slate-100 px-2 pt-3 text-start text-[12px] font-medium text-blue-600 hover:underline"><span className="text-[18px]">＋</span>{ar?'إنشاء تصنيف':'Create label'}</button>
  </Modal>
  {createOpen?<Modal title={ar?'إنشاء تصنيف':'Create Label'} onClose={()=>setCreateOpen(false)} className="w-full max-w-[590px]" footer={<><button className="imkan-button-secondary" onClick={()=>setCreateOpen(false)}>{ar?'إلغاء':'Cancel'}</button><button className="imkan-button" disabled={busy||!newName.trim()} onClick={()=>void create()}>{ar?'إنشاء':'Create'}</button></>}>
   <input autoFocus value={newName} onChange={e=>setNewName(e.target.value)} maxLength={80} placeholder={ar?'أدخل اسم التصنيف':'Enter label name'} className="h-10 w-full rounded-full border border-blue-500 px-4 text-[13px] outline-none"/>
   <p className="mb-3 mt-8 text-[12px] text-slate-600">{ar?'اختر لون التصنيف':'Choose Label Color'}</p><div className="grid max-w-[180px] grid-cols-6 gap-2">{LABEL_COLORS.map(c=><button key={c} type="button" onClick={()=>setNewColor(c)} aria-label={c} className="grid h-5 w-5 place-items-center rounded-[2px] text-[12px] text-white" style={{background:c}}>{newColor===c?'✓':''}</button>)}</div>
  </Modal>:null}
 </>;
}
