"use client";
import { useEffect, useState } from 'react';
import { Modal } from './modal';
import { useLocale } from './locale-provider';
import { attachWorkspaceLabel, detachWorkspaceLabel, listWorkspaceLabels, listWorkspaceLabelResources, type WorkspaceLabel } from '../lib/api/workspace-labels';
export function LabelAssignmentModal({target,onClose,onChanged}:{target:{type:'FILE'|'FOLDER';id:string;name:string};onClose:()=>void;onChanged:()=>void}){
 const {locale}=useLocale();const ar=locale==='ar';const [labels,setLabels]=useState<WorkspaceLabel[]>([]);const [selected,setSelected]=useState<Set<string>>(new Set());const [initial,setInitial]=useState<Set<string>>(new Set());const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{let live=true;void listWorkspaceLabels().then(async rows=>({rows,resources:await Promise.all(rows.map(l=>listWorkspaceLabelResources(l.id).then(r=>({id:l.id,has:r.some(x=>x.resourceType===target.type&&x.resourceId===target.id)}))))})).then(detail=>{if(!live)return;setLabels(detail.rows);const ids=new Set(detail.resources.filter(x=>x.has).map(x=>x.id));setSelected(ids);setInitial(ids)}).catch(()=>setError(ar?'تعذر تحميل التصنيفات':'Could not load labels'));return()=>{live=false}},[target.id,target.type,ar]);
 const save=async()=>{setBusy(true);setError('');try{for(const l of labels){const before=initial.has(l.id),after=selected.has(l.id);if(before===after)continue;if(after)await attachWorkspaceLabel(l.id,target.type,target.id);else await detachWorkspaceLabel(l.id,target.type,target.id)}onChanged();onClose()}catch(e){setError(e instanceof Error?e.message:(ar?'تعذر حفظ التصنيفات':'Could not save labels'))}finally{setBusy(false)}};
 return <Modal title={ar?'تصنيف العنصر':'Label as'} onClose={onClose} footer={<><button className="imkan-button-secondary" onClick={onClose}>{ar?'إلغاء':'Cancel'}</button><button className="imkan-button" disabled={busy} onClick={()=>void save()}>{busy?(ar?'جارٍ الحفظ':'Saving…'):(ar?'حفظ':'Save')}</button></>}><div className="mb-3 text-[11px] text-slate-500">{target.name}</div>{error?<div className="mb-2 text-[11px] text-red-600">{error}</div>:null}<div className="max-h-72 space-y-1 overflow-auto">{labels.length===0?<div className="py-6 text-center text-[11px] text-slate-400">{ar?'أنشئ تصنيفًا أولًا من قسم Labels':'Create a label first in Labels'}</div>:labels.map(l=><label key={l.id} className="flex cursor-pointer items-center gap-2 rounded-lg px-2 py-2 hover:bg-slate-50"><input type="checkbox" checked={selected.has(l.id)} onChange={e=>setSelected(prev=>{const n=new Set(prev);e.target.checked?n.add(l.id):n.delete(l.id);return n})}/><span className="h-3 w-3 rounded-full" style={{background:l.color}}/><span className="text-[12px] text-slate-700">{l.name}</span></label>)}</div></Modal>
}
