'use client';
import {useState} from 'react';
import type {ReactNode} from 'react';

type OfficeType='WRITER'|'SHEET'|'SHOW';
export type OfficeMobileProps={
 type:OfficeType; ar?:boolean; undo?:()=>void; redo?:()=>void; save?:()=>void; find?:()=>void; bold?:()=>void; italic?:()=>void; underline?:()=>void; navigation?:()=>void;
 selectedCell?:string; formulaValue?:string; editingCell?:boolean; onFormulaChange?:(v:string)=>void; onFormulaCommit?:()=>void; onBeginCellEdit?:()=>void;
 showIndex?:number; showCount?:number; onPrevSlide?:()=>void; onNextSlide?:()=>void; onPresent?:()=>void; onEdit?:()=>void; note?:string; onNoteChange?:(v:string)=>void;
 extra?:ReactNode;
};
const labels={WRITER:['كتابة','تنقل'],SHEET:['ورقة','خلية'],SHOW:['شرائح','ملاحظات']} as const;
export function OfficeMobile({type,ar=false,undo,redo,save,find,bold,italic,underline,navigation,selectedCell,formulaValue='',editingCell,onFormulaChange,onFormulaCommit,onBeginCellEdit,showIndex=0,showCount=0,onPrevSlide,onNextSlide,onPresent,onEdit,note='',onNoteChange,extra}:OfficeMobileProps){
 const [panel,setPanel]=useState<'main'|'format'|'nav'|'notes'>('main');
 const isSheet=type==='SHEET', isShow=type==='SHOW';
 const text=(en:string,arText:string)=>ar?arText:en;
 return <>
  {isSheet&&<div className="md:hidden sticky top-0 z-30 border-b bg-white px-2 py-1.5 shadow-sm" dir={ar?'rtl':'ltr'}><div className="flex items-center gap-1"><span className="w-14 shrink-0 rounded border bg-slate-50 px-2 py-1 text-center text-[11px] font-mono">{selectedCell||'A1'}</span><input aria-label={text('Formula bar','شريط الصيغة')} className="min-w-0 flex-1 rounded border px-2 py-1.5 text-xs outline-none focus:ring-1" value={formulaValue} onFocus={onBeginCellEdit} onChange={e=>onFormulaChange?.(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();onFormulaCommit?.()}}}/><button className="rounded border px-2 py-1.5 text-xs" onClick={onFormulaCommit}>{text('Done','تم')}</button></div></div>}
  {isShow&&panel==='notes'&&<div className="md:hidden fixed inset-x-0 bottom-14 z-40 max-h-[45vh] border-t bg-white p-3 shadow-2xl" dir={ar?'rtl':'ltr'}><div className="mb-2 flex items-center justify-between text-xs font-semibold"><span>{text('Speaker notes','ملاحظات المقدم')}</span><button aria-label={text('Close panel','إغلاق اللوحة')} className="rounded border px-2 py-1 office-hit-target" onClick={()=>setPanel('main')}>×</button></div><textarea className="h-28 w-full rounded border p-2 text-xs" value={note} onChange={e=>onNoteChange?.(e.target.value)} placeholder={text('Add notes…','أضف ملاحظات…')}/></div>}
  {isShow&&panel==='nav'&&<div className="md:hidden fixed inset-x-0 bottom-14 z-40 max-h-[42vh] overflow-auto border-t bg-white p-3 shadow-2xl" dir={ar?'rtl':'ltr'}><div className="mb-2 flex items-center justify-between text-xs font-semibold"><span>{text('Slide navigation','تنقل الشرائح')}</span><button aria-label={text('Close panel','إغلاق اللوحة')} className="rounded border px-2 py-1 office-hit-target" onClick={()=>setPanel('main')}>×</button></div><div className="mb-2 grid grid-cols-2 gap-2"><button className="rounded border px-3 py-2 text-xs" onClick={onPrevSlide}>← {text('Previous','السابق')}</button><button className="rounded border px-3 py-2 text-xs" onClick={onNextSlide}>{text('Next','التالي')} →</button></div><div className="text-center text-[11px] text-slate-500">{showIndex+1} / {showCount}</div></div>}
  <div className="md:hidden fixed inset-x-0 bottom-0 z-50 border-t bg-white/95 px-1 pb-[max(4px,env(safe-area-inset-bottom))] pt-1 shadow-[0_-4px_16px_rgba(15,23,42,.08)] backdrop-blur" dir={ar?'rtl':'ltr'}>
   <div className="flex items-center gap-1 overflow-x-auto">
    <button aria-label={text('Undo','تراجع')} className="mobile-office-btn office-hit-target" onClick={undo}>↶<span>{text('Undo','تراجع')}</span></button><button aria-label={text('Redo','إعادة')} className="mobile-office-btn office-hit-target" onClick={redo}>↷<span>{text('Redo','إعادة')}</span></button>
    {type==='WRITER'&&<><button aria-label={text('Bold','عريض')} className="mobile-office-btn office-hit-target" onClick={bold}>B<span>{text('Bold','عريض')}</span></button><button aria-label={text('Italic','مائل')} className="mobile-office-btn office-hit-target" onClick={italic}><i>I</i><span>{text('Italic','مائل')}</span></button><button aria-label={text('Underline','تحته خط')} className="mobile-office-btn office-hit-target" onClick={underline}><u>U</u><span>{text('Underline','تحته خط')}</span></button><button aria-label={text('Find','بحث')} className="mobile-office-btn office-hit-target" onClick={find}>⌕<span>{text('Find','بحث')}</span></button><button aria-label={text('Navigate','تنقل')} className="mobile-office-btn office-hit-target" onClick={navigation}>☰<span>{text('Navigate','تنقل')}</span></button></>}
    {type==='SHEET'&&<><button aria-label={text('Format','تنسيق')} className={`mobile-office-btn office-hit-target ${panel==='format'?'bg-slate-100':''}`} onClick={()=>setPanel(panel==='format'?'main':'format')}>Aa<span>{text('Format','تنسيق')}</span></button><button aria-label={text('Edit cell','تحرير الخلية')} className="mobile-office-btn office-hit-target" onClick={onBeginCellEdit}>✎<span>{text('Edit cell','تحرير')}</span></button></>}
    {isShow&&<><button aria-label={text('Slides','شرائح')} className="mobile-office-btn office-hit-target" onClick={()=>setPanel('nav')}>☰<span>{text('Slides','شرائح')}</span></button><button aria-label={text('Notes','ملاحظات')} className="mobile-office-btn office-hit-target" onClick={()=>setPanel('notes')}>▤<span>{text('Notes','ملاحظات')}</span></button><button aria-label={text('Edit','تحرير')} className="mobile-office-btn office-hit-target" onClick={onEdit}>✎<span>{text('Edit','تحرير')}</span></button><button aria-label={text('Present','عرض')} className="mobile-office-btn office-hit-target" onClick={onPresent}>▶<span>{text('Present','عرض')}</span></button></>}
    <span className="flex-1"/>{extra}<button aria-label={text('Save','حفظ')} className="mobile-office-btn office-hit-target" onClick={save}>▣<span>{text('Save','حفظ')}</span></button>
   </div>
  </div>
  {type==='SHEET'&&panel==='format'&&<div className="md:hidden fixed inset-x-0 bottom-14 z-40 border-t bg-white p-2 shadow-2xl" dir={ar?'rtl':'ltr'}><div className="grid grid-cols-3 gap-1"><button className="rounded border px-2 py-2 text-xs font-bold" onClick={bold}>B</button><button className="rounded border px-2 py-2 text-xs italic" onClick={italic}>I</button><button className="rounded border px-2 py-2 text-xs underline" onClick={underline}>U</button></div></div>}
  <style jsx>{`.mobile-office-btn{display:flex;min-width:52px;flex-direction:column;align-items:center;justify-content:center;gap:2px;border-radius:7px;padding:5px 6px;font-size:15px;line-height:1;color:#475569}.mobile-office-btn span{font-size:9px;white-space:nowrap}`}</style>
 </>;
}
