'use client';
import {useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import {downloadOfficeExport,exportOfficeFile,importOfficeFile,getOfficeConversionDiagnostics,runOfficeConversionRoundTrip,OfficeConversionReport} from '@/lib/api/office-conversion';

export function OfficeTransferControls({fileId,type,ar=false}:{fileId:string;type:'WRITER'|'SHEET'|'SHOW';ar?:boolean}){
 const router=useRouter(); const input=useRef<HTMLInputElement>(null); const [busy,setBusy]=useState(false); const [report,setReport]=useState<OfficeConversionReport|null>(null); const [mode,setMode]=useState<'analysis'|'roundtrip'|null>(null); const format=type==='WRITER'?'docx':type==='SHEET'?'xlsx':'pptx';
 const importIt=async(file:File)=>{setBusy(true);try{const r=await importOfficeFile(file);router.push(`/office/${r.type.toLowerCase()}/${r.fileId}`);}catch(e:any){window.alert(e?.message||'Import failed');}finally{setBusy(false)}};
 const diagnose=async()=>{setBusy(true);setMode('analysis');try{setReport(await getOfficeConversionDiagnostics(fileId,format));}catch(e:any){window.alert(e?.message||'Analysis failed');}finally{setBusy(false)}};
 const roundTrip=async()=>{setBusy(true);setMode('roundtrip');try{setReport(await runOfficeConversionRoundTrip(fileId,format));}catch(e:any){window.alert(e?.message||'Round-trip analysis failed');}finally{setBusy(false)}};
 const exportIt=async()=>{setBusy(true);try{downloadOfficeExport(await exportOfficeFile(fileId,format));}catch(e:any){window.alert(e?.message||'Export failed');}finally{setBusy(false)}};
 const label=(c:string)=>({preserved:ar?'محفوظ':'Preserved',converted:ar?'محوّل':'Converted',warning:ar?'تحذير':'Warning',unsupported:ar?'غير مدعوم':'Not supported'}[c]||c);
 return <div className="flex flex-col gap-2"><div className="flex flex-wrap gap-2"><button className="rounded-md border px-2.5 py-1.5 text-xs hover:bg-slate-50 disabled:opacity-50" disabled={busy} onClick={()=>input.current?.click()}>{ar?'استيراد':'Import'}</button><input ref={input} hidden type="file" accept={format==='docx'?'.docx':format==='xlsx'?'.xlsx':'.pptx'} onChange={e=>{const f=e.target.files?.[0];if(f)void importIt(f);e.currentTarget.value=''}}/><button className="rounded-md border px-2.5 py-1.5 text-xs hover:bg-slate-50 disabled:opacity-50" disabled={busy} onClick={()=>void diagnose()}>{ar?'مركز التوافق':'Compatibility Center'}</button><button className="rounded-md border px-2.5 py-1.5 text-xs hover:bg-slate-50 disabled:opacity-50" disabled={busy} onClick={()=>void roundTrip()}>{ar?'اختبار Round Trip':'Round-trip test'}</button><button className="rounded-md border px-2.5 py-1.5 text-xs hover:bg-slate-50 disabled:opacity-50" disabled={busy} onClick={()=>void exportIt()}>{ar?`تصدير ${format.toUpperCase()}`:`Export ${format.toUpperCase()}`}</button></div>
 {report&&<div className="rounded-lg border bg-slate-50 p-3 text-[11px]"><div className="flex flex-wrap items-center justify-between gap-2"><div className="font-semibold">{ar?'مركز توافق IMKAN Office':'IMKAN Office Compatibility Center'}</div><div className="text-slate-500">{report.sourceFormat} → {report.targetFormat.toUpperCase()} · {report.converterVersion} · schema {report.nativeSchemaVersion}</div></div><div className="mt-2 grid grid-cols-2 gap-1 sm:grid-cols-4"><div>✓ {label('preserved')}: {report.summary.preserved}</div><div>↔ {label('converted')}: {report.summary.converted}</div><div>⚠ {label('warning')}: {report.summary.warning}</div><div>✕ {label('unsupported')}: {report.summary.unsupported}</div></div>{report.roundTrip&&<div className="mt-2 rounded border bg-white p-2"><div className="font-medium">{ar?'نتيجة Round Trip':'Round-trip result'}: {report.roundTrip.structurallyStable?(ar?'مستقر بنيوياً':'Structurally stable'):(ar?'يوجد اختلاف بنيوي':'Structural differences detected')}</div><div className="mt-1 text-slate-600">{ar?'حجم التصدير':'Exported'}: {report.roundTrip.exportedBytes.toLocaleString()} bytes · {ar?'المقاييس':'Metrics'}: {Object.entries(report.roundTrip.metricDiffs).map(([k,v])=>`${k}:${v>0?'+':''}${v}`).join(' · ')}</div></div>}{report.diagnostics.length>0&&<div className="mt-2 space-y-1">{report.diagnostics.slice(0,8).map((d,i)=><div key={i}><span className="font-medium">[{label(d.category||'converted')}]</span> {d.message}</div>)}</div>}</div>}
 </div>;
}
