'use client';
import {useMemo,useState} from 'react';
import type {ReactNode} from 'react';

type Action=()=>void;
export type OfficeRibbonProps={
 type:'WRITER'|'SHEET'|'SHOW'; ar?:boolean; saved?:boolean; saving?:boolean;
 actions?:Record<string,Action|undefined>; presence?:ReactNode;
};

type RibbonConfig=Record<'WRITER'|'SHEET'|'SHOW',Record<string,string[]>>;
const labels:RibbonConfig={
 WRITER:{File:['Save','Print','Export'],Home:['Undo','Redo','Bold','Italic','Underline','Align','Find'],Insert:['Table','Image','Page Break','TOC','Bookmark','Footnote'],Layout:['Page Setup','Columns','Breaks','Margins'],References:['TOC','Bookmark','Footnote','Citation','Bibliography','Index'],Review:['Comments','Track Changes','Snapshot'],View:['Print','Fullscreen','Navigation']},
 SHEET:{File:['Save','Print','Export'],Home:['Undo','Redo','Bold','Italic','Format','Fill Down'],Insert:['Chart','Table','Pivot','Sheet'],'Page Layout':['Freeze','Print Area','Page Setup'],Formulas:['Formula','Named Range','Recalculate'],Data:['Sort','Filter','Validation','Named Range'],Review:['Comments','Snapshot'],View:['Freeze','Fullscreen','Navigation']},
 SHOW:{File:['Save','Export','Print'],Home:['Undo','Redo','Present'],Insert:['Text','Image','Shape','Video','Audio','Table'],Design:['Theme','Background','Layout'],Transitions:['Transition','Transition Duration'],Animations:['Animation','Animation Order','Animation Timing'], 'Slide Show':['Present','Presenter View','Audience View'],Review:['Comments','Snapshot'],View:['Navigator','Fullscreen','Grid']}
};
const key=(s:string)=>s.toLowerCase().replaceAll(' ','');
const icon=(n:string)=>({Undo:'↶',Redo:'↷',Bold:'B',Italic:'I',Underline:'U',Table:'▦',Chart:'▥',Pivot:'◫',Find:'⌕',Print:'⎙',Fullscreen:'⛶',Present:'▶',Image:'▧',Video:'▶',Audio:'♫',Delete:'⌫',Save:'▣',Export:'⇩',Navigation:'☰',Navigator:'☰',Formula:'ƒx',Theme:'◈',Background:'◐',Layout:'▤',Transition:'↝',Animations:'✦',Animation:'✦',Grid:'▦'} as Record<string,string>)[n]||'•';
const arLabels:Record<string,string>={File:'ملف',Home:'الرئيسية',Insert:'إدراج',Layout:'تخطيط',References:'مراجع',Review:'مراجعة',View:'عرض',Data:'بيانات','Page Layout':'تخطيط الصفحة',Formulas:'الصيغ',Design:'تصميم',Transitions:'انتقالات',Animations:'حركات','Slide Show':'عرض الشرائح',Save:'حفظ',Print:'طباعة',Export:'تصدير',Undo:'تراجع',Redo:'إعادة',Bold:'عريض',Italic:'مائل',Underline:'تحته خط',Align:'محاذاة',Find:'بحث',Table:'جدول',Image:'صورة','Page Break':'فاصل صفحة',TOC:'جدول المحتويات',Bookmark:'إشارة مرجعية',Footnote:'حاشية',Comments:'تعليقات','Track Changes':'تتبع التغييرات',Snapshot:'لقطة',Fullscreen:'ملء الشاشة',Format:'تنسيق','Fill Down':'تعبئة لأسفل',Chart:'رسم',Pivot:'Pivot',Sheet:'ورقة',Sort:'فرز',Filter:'تصفية',Validation:'تحقق','Named Range':'نطاق مسمى',Freeze:'تجميد','Print Area':'منطقة الطباعة','Page Setup':'إعداد الصفحة',Formula:'صيغة',Recalculate:'إعادة الحساب',Present:'عرض','Presenter View':'وضع المقدم','Audience View':'عرض الجمهور',Text:'نص',Shape:'شكل',Video:'فيديو',Audio:'صوت','New Slide':'شريحة جديدة',Duplicate:'تكرار',Delete:'حذف',Transition:'انتقال','Transition Duration':'مدة الانتقال',Animation:'حركة','Animation Order':'ترتيب الحركات','Animation Timing':'توقيت الحركة',Theme:'نسق',Background:'خلفية',Navigation:'تنقل',Navigator:'المستكشف',Grid:'شبكة',Citation:'استشهاد',Bibliography:'ببليوغرافيا',Index:'فهرس',Columns:'أعمدة',Breaks:'فواصل',Margins:'هوامش'};
const actionAliases:Record<string,string[]>={Save:['save','persist'],Print:['print'],Export:['export'],Navigation:['navigation','openNavigation'],Navigator:['navigator','navigation'],Citation:['citation','insertCitation'],Bibliography:['bibliography','insertBibliography'],Index:['index','buildIndex'],Columns:['columns'],Breaks:['breaks','sectionBreak'],Margins:['margins'],PageSetup:['pageSetup'],Formula:['formula','insertFormula'],Recalculate:['recalculate'],Theme:['theme'],Background:['background'],Grid:['grid']};
export function OfficeRibbon({type,ar=false,saved=true,saving=false,actions={},presence}:OfficeRibbonProps){
 const tabs=useMemo(()=>Object.keys(labels[type]),[type]); const [tab,setTab]=useState(tabs.includes('Home')?'Home':tabs[0]);
 const available=(n:string)=>{for(const candidate of [key(n),n,...(actionAliases[n]||[])]) if(actions[candidate]) return actions[candidate]; return undefined;};
 return <div aria-label={ar?'شريط Office':'Office ribbon'} role="region" className="sticky top-0 z-40 border-b border-slate-200 bg-white shadow-sm print:hidden" dir={ar?'rtl':'ltr'}>
   <div className="flex h-9 items-center gap-1 overflow-x-auto px-2 text-xs"><div className="me-2 hidden font-semibold text-[var(--wd-primary)] sm:block">IMKAN Office</div>{tabs.map(t=><button key={t} role="tab" aria-selected={tab===t} aria-controls={`office-ribbon-panel-${key(t)}`} onClick={()=>setTab(t)} className={`rounded px-3 py-1.5 whitespace-nowrap ${tab===t?'bg-slate-100 font-semibold text-slate-900':'text-slate-500 hover:bg-slate-50'}`}>{ar?(arLabels[t]||t):t}</button>)}<span className="ms-auto hidden sm:block text-[10px] text-slate-400">{saving?(ar?'جارٍ الحفظ…':'Saving…'):(saved?(ar?'تم الحفظ':'Saved'):(ar?'غير محفوظ':'Unsaved'))}</span>{presence}</div>
   <div id={`office-ribbon-panel-${key(tab)}`} role="tabpanel" aria-label={ar?(arLabels[tab]||tab):tab} className="flex min-h-14 items-center gap-1 overflow-x-auto px-2 pb-2 pt-1">{labels[type][tab].map((n:string)=>{const fn=available(n);return <button key={n} aria-label={ar?(arLabels[n]||n):n} disabled={!fn} onClick={()=>fn?.()} title={ar?(arLabels[n]||n):n} className="flex min-w-[58px] flex-col items-center gap-1 rounded-lg px-2 py-1.5 text-[10px] text-slate-600 hover:bg-slate-100 disabled:cursor-not-allowed disabled:opacity-35"><span className="flex h-7 w-8 items-center justify-center rounded border border-slate-200 bg-slate-50 text-xs">{icon(n)}</span><span className="whitespace-nowrap">{ar?(arLabels[n]||n):n}</span></button>})}</div>
 </div>;
}
