"use client";
import { useEffect, useMemo, useState } from "react";
import { useLocale } from "./locale-provider";
import { getWorkflow, listWorkflowParticipantOptions, listWorkflows, startWorkflow, type Workflow, type WorkflowParticipantOptions } from "../lib/api/workflows";
import { Modal } from "./modal";

type Field = { id:string; name:string; description?:string; type:string; required?:boolean; defaultValue?:string; max?:number; options?:string[] };
type Rule = { type:"USER"|"GROUP"|"ROLE"; ids?:string[]; roles?:string[] };

export function WorkflowPicker({resourceType,resourceId,resourceName,onClose,onStarted}:{resourceType:"FILE"|"FOLDER";resourceId:string;resourceName:string;onClose:()=>void;onStarted:()=>void}){
 const {label}=useLocale(); const [rows,setRows]=useState<Workflow[]>([]); const [loading,setLoading]=useState(true); const [selected,setSelected]=useState<Workflow|null>(null); const [detail,setDetail]=useState<Workflow|null>(null); const [options,setOptions]=useState<WorkflowParticipantOptions|null>(null); const [fieldValues,setFieldValues]=useState<Record<string,unknown>>({}); const [users,setUsers]=useState<string[]>([]); const [groups,setGroups]=useState<string[]>([]); const [roles,setRoles]=useState<string[]>([]); const [comment,setComment]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
 useEffect(()=>{ void listWorkflows().then(r=>setRows(r.filter(x=>x.mode==="MANUAL"&&x.resourceType===resourceType&&x.status==="ACTIVE"))).catch(e=>setError(e instanceof Error?e.message:"Unable to load workflows")).finally(()=>setLoading(false)); },[resourceType]);
 const loadDetail=async(w:Workflow)=>{setError("");setSelected(w);try{const full=await getWorkflow(w.id);setDetail(full);const needsParticipants=full.transitions.some(t=>t.actions.some(a=>a.type==="request_approval"&&a.config?.allowStarterParticipants===true));if(needsParticipants){try{setOptions(await listWorkflowParticipantOptions());}catch(e){setOptions(null);setError(e instanceof Error?e.message:"Unable to load participant options");}}else setOptions(null);const fields=(full.steps.find(s=>s.kind==="WORKFLOW_FIELDS")?.config.value as Field[]|undefined)??[];setFieldValues(Object.fromEntries(fields.filter(f=>f.defaultValue!==undefined).map(f=>[f.id,f.defaultValue])));}catch(e){setError(e instanceof Error?e.message:"Unable to load workflow details");}};
 const fields=useMemo(()=>((detail?.steps.find(s=>s.kind==="WORKFLOW_FIELDS")?.config.value as Field[]|undefined)??[]),[detail]);
 const needsStarterParticipants=useMemo(()=>detail?.transitions.some(t=>t.actions.some(a=>a.type==="request_approval"&&a.config?.allowStarterParticipants===true))??false,[detail]);
 const rules:Rule[]=[...(users.length?[{type:"USER" as const,ids:users}]:[]),...(groups.length?[{type:"GROUP" as const,ids:groups}]:[]),...(roles.length?[{type:"ROLE" as const,roles}]:[])];
 const start=async()=>{if(!detail)return;setBusy(true);setError("");try{await startWorkflow(detail.id,{fileId:resourceId,name:resourceName,resourceType,userId:"",fieldValues,participantRules:needsStarterParticipants?rules:undefined,comment});onStarted();onClose();}catch(e){setError(e instanceof Error?e.message:label("error.generic"));}finally{setBusy(false)}};
 return <Modal title={label("menu.assignWorkflow")} onClose={onClose}><div className="space-y-3">
   <p className="text-[12px] text-slate-500">{resourceName}</p>{error&&<div className="rounded-lg bg-red-50 px-3 py-2 text-[11px] text-red-700">{error}</div>}
   {!detail ? loading?<p className="text-[12px] text-slate-500">{label("common.loading")}</p>:rows.length===0?<p className="rounded-lg bg-slate-50 px-3 py-4 text-center text-[12px] text-slate-500">No manual workflows are available.</p>:<div className="max-h-80 space-y-2 overflow-y-auto">{rows.map(w=><button key={w.id} onClick={()=>void loadDetail(w)} className="w-full rounded-lg border border-slate-200 p-3 text-start hover:border-[#1B66EA] hover:bg-[#F7FAFF]"><div className="text-[12px] font-semibold">{w.name}</div><div className="mt-1 text-[10.5px] text-slate-500">{w.description||"Manual workflow"}</div><div className="mt-2 text-[9px] text-slate-400">{w.states.length} states · {w.transitions.length} transitions</div></button>)}</div>
   :<><div className="flex items-start gap-2 rounded-xl border border-slate-200 bg-slate-50 p-3"><button onClick={()=>setDetail(null)} className="rounded-md border border-slate-200 bg-white px-2 py-1 text-[10px] text-slate-600">←</button><div className="min-w-0"><div className="text-[13px] font-semibold text-slate-900">{detail.name}</div><div className="mt-1 text-[10px] text-slate-500">{detail.description||"Manual workflow"}</div></div></div>
    {fields.length>0&&<div className="rounded-xl border border-slate-200 p-3"><div className="text-[10px] font-semibold text-slate-700">Workflow details</div><div className="mt-2 space-y-2">{fields.map(f=><label key={f.id} className="block text-[10px] font-medium text-slate-600">{f.name}{f.required&&<span className="ms-1 text-red-500">*</span>}<div className="mt-1">{f.type==="multi"?<textarea value={String(fieldValues[f.id]??"")} maxLength={f.max} onChange={e=>setFieldValues(v=>({...v,[f.id]:e.target.value}))} rows={3} className="w-full rounded-lg border border-slate-200 px-2.5 py-2 text-[10.5px]"/>:f.type==="choice"?<select value={String(fieldValues[f.id]??"")} onChange={e=>setFieldValues(v=>({...v,[f.id]:e.target.value}))} className="w-full rounded-lg border border-slate-200 px-2.5 py-2 text-[10.5px]"><option value="">Select…</option>{(f.options??[]).map(o=><option key={o}>{o}</option>)}</select>:f.type==="boolean"?<select value={fieldValues[f.id]===true?"true":fieldValues[f.id]===false?"false":""} onChange={e=>setFieldValues(v=>({...v,[f.id]:e.target.value==="true"}))} className="w-full rounded-lg border border-slate-200 px-2.5 py-2 text-[10.5px]"><option value="">Select…</option><option value="true">Yes</option><option value="false">No</option></select>:<input type={f.type==="email"?"email":f.type==="number"?"number":f.type==="date"?"date":f.type==="datetime"?"datetime-local":"text"} value={String(fieldValues[f.id]??"")} maxLength={f.max} onChange={e=>setFieldValues(v=>({...v,[f.id]:f.type==="number"?(e.target.value===""?"":Number(e.target.value)):e.target.value}))} className="w-full rounded-lg border border-slate-200 px-2.5 py-2 text-[10.5px]"/>}</div>{f.description&&<div className="mt-1 text-[9px] text-slate-400">{f.description}</div>}</label>)}</div></div>}
    {needsStarterParticipants&&options&&<div className="rounded-xl border border-slate-200 p-3"><div className="text-[10px] font-semibold text-slate-700">Participants</div><p className="mt-1 text-[9.5px] text-slate-500">Choose the users, groups, or roles who should receive the approval task.</p><div className="mt-2 grid gap-2">{options.users.length>0&&<select multiple value={users} onChange={e=>setUsers(Array.from(e.target.selectedOptions).map(o=>o.value))} className="h-24 w-full rounded-lg border border-slate-200 px-2 py-2 text-[10px]">{options.users.map(u=><option key={u.id} value={u.id}>{u.name||u.email} · {u.email}</option>)}</select>}{options.groups.length>0&&<select multiple value={groups} onChange={e=>setGroups(Array.from(e.target.selectedOptions).map(o=>o.value))} className="h-20 w-full rounded-lg border border-slate-200 px-2 py-2 text-[10px]">{options.groups.map(g=><option key={g.id} value={g.id}>{g.name} · {g.memberCount??0}</option>)}</select>}<div className="flex flex-wrap gap-1">{options.roles.map(role=><label key={role} className="rounded-md border border-slate-200 px-2 py-1 text-[8.5px] text-slate-600"><input type="checkbox" className="me-1 accent-[#1B66EA]" checked={roles.includes(role)} onChange={e=>setRoles(v=>e.target.checked?[...v,role]:v.filter(x=>x!==role))}/>{role}</label>)}</div></div></div>}
    <label className="block text-[10px] font-medium text-slate-600">Comment <textarea value={comment} onChange={e=>setComment(e.target.value)} maxLength={4000} rows={2} placeholder="Optional start comment" className="mt-1 w-full resize-none rounded-lg border border-slate-200 px-2.5 py-2 text-[10.5px]"/></label>
    <div className="flex justify-end gap-2"><button onClick={()=>setDetail(null)} disabled={busy} className="rounded-lg border border-slate-200 px-3 py-2 text-[10px] text-slate-600">Cancel</button><button onClick={()=>void start()} disabled={busy||!detail} className="rounded-lg bg-[#1B66EA] px-4 py-2 text-[10px] font-semibold text-white disabled:opacity-50">{busy?"Starting…":"Start workflow"}</button></div>
   </>}
 </div></Modal>;
}
