export type WorkflowHelpKey =
  | 'workflow.list' | 'workflow.builder' | 'workflow.fields' | 'workflow.state' | 'workflow.transition'
  | 'workflow.conditions' | 'workflow.actions' | 'workflow.participants' | 'workflow.sla' | 'workflow.versions'
  | 'workflow.runs' | 'workflow.tasks' | 'workflow.templates' | 'workflow.functions' | 'workflow.diagnostics'
  | 'workflow.queue' | 'workflow.audit' | 'workflow.dynamic-values';

type HelpEntry = { title: string; description: string; steps: string[]; tips: string[]; warnings?: string[]; examples?: string[] };
export const WORKFLOW_HELP: Record<WorkflowHelpKey, { ar: HelpEntry; en: HelpEntry }> = {
  'workflow.list': { ar:{title:'إدارة سير العمل',description:'أنشئ سير العمل، راقب حالته، وادخل إلى المصمم والسجلات من مكان واحد.',steps:['أنشئ سير عمل جديد من زر New.','افتح المصمم لبناء الحقول والحالات والانتقالات.','فعّل النسخة بعد مراجعة الإعدادات.'],tips:['المسودة قابلة للتعديل؛ النسخة النشطة تُنفّذ على التشغيل.']}, en:{title:'Workflow management',description:'Create workflows, monitor status, and open the builder and runtime areas from one place.',steps:['Create a workflow from New.','Open the builder to configure fields, states and transitions.','Activate only after reviewing the configuration.'],tips:['Drafts are editable; the active version is what runtime executes.']} },
  'workflow.builder': { ar:{title:'مصمم سير العمل',description:'المصمم هو مركز إعداد سير العمل: الحقول، التصميم، المراجعة والتفعيل.',steps:['ابدأ بالحقول والقيم الافتراضية.','ابنِ الحالات والانتقالات على اللوحة.','اضبط الشروط والمشاركين وSLA والإجراءات.','راجع ثم فعّل.'],tips:['استخدم المعاينة والقيم الديناميكية بدل كتابة القيم المتغيرة يدوياً.']}, en:{title:'Workflow builder',description:'The builder is the configuration center for fields, design, review and activation.',steps:['Configure fields and defaults.','Build states and transitions on the canvas.','Configure conditions, participants, SLA and actions.','Review and activate.'],tips:['Use the dynamic-value browser instead of hard-coding runtime values.']} },
  'workflow.fields': { ar:{title:'حقول سير العمل',description:'حقول مخصصة تحفظ بيانات الحالة وتستخدمها الشروط والإجراءات والقوالب.',steps:['أضف نوع الحقل.','حدد الاسم والنوع والقيمة الافتراضية والتحقق.','رتب الحقول حسب ترتيب ظهورها.'],tips:['اجعل معرف الحقل ثابتاً لأن القيم الديناميكية تعتمد عليه.']}, en:{title:'Workflow fields',description:'Custom fields store workflow data used by conditions, actions and templates.',steps:['Add a field type.','Configure name, type, default and validation.','Reorder fields as needed.'],tips:['Keep field IDs stable because dynamic values reference them.']} },
  'workflow.state': { ar:{title:'الحالة State',description:'الحالة تمثل مرحلة تشغيل واضحة داخل سير العمل.',steps:['حدد اسم ووصف الحالة.','حدد إن كانت حالة نهائية.','اربطها بالانتقالات الداخلة والخارجة.'],tips:['استخدم حالات قصيرة ومحددة مثل مراجعة، موافقة، مكتمل.']}, en:{title:'State',description:'A state represents a clear stage in a workflow run.',steps:['Set a name and description.','Mark terminal states when appropriate.','Connect incoming and outgoing transitions.'],tips:['Prefer short, explicit states such as Review, Approval and Completed.']} },
  'workflow.transition': { ar:{title:'الانتقال Transition',description:'الانتقال يحدد كيف ينتقل التشغيل من حالة إلى أخرى وما يحدث قبل وأثناء وبعد الانتقال.',steps:['اختر الحالة المصدر والهدف.','اضبط Trigger وConditions.','أضف Before/During/After actions.','حدد المشاركين وSLA عند الحاجة.'],tips:['قسّم الإجراءات حسب توقيتها لتسهيل التشخيص.']}, en:{title:'Transition',description:'A transition defines how a run moves between states and what happens before, during and after it.',steps:['Choose source and target states.','Configure trigger and conditions.','Add Before/During/After actions.','Configure participants and SLA when needed.'],tips:['Separate actions by timing to make runtime diagnostics easier.']} },
  'workflow.conditions': { ar:{title:'الشروط',description:'الشروط تحدد متى يسمح الانتقال بالتنفيذ باستخدام مجموعات AND/OR متداخلة.',steps:['اختر الحقل أو القيمة الديناميكية.','حدد عامل المقارنة والقيمة.','ادمج الشروط داخل مجموعات AND/OR عند الحاجة.'],tips:['استخدم قيم workflow.* وfile.* عندما تعتمد القاعدة على التشغيل الفعلي.']}, en:{title:'Conditions',description:'Conditions decide when a transition is allowed using nested AND/OR groups.',steps:['Choose a field or dynamic value.','Select an operator and comparison value.','Combine rules into AND/OR groups when needed.'],tips:['Use workflow.* and file.* values when rules depend on runtime data.']} },
  'workflow.actions': { ar:{title:'الإجراءات',description:'الإجراءات تنفذ العمل الفعلي في الانتقال، مثل الإشعارات والقوالب والدوال الآمنة.',steps:['اختر نوع الإجراء.','اضبط مدخلاته باستخدام القيم الديناميكية.','رتب الإجراءات حسب أولوية التنفيذ.'],tips:['الدوال الآمنة تستخدم قائمة عمليات مقيدة ولا تنفذ JavaScript عشوائياً.']}, en:{title:'Actions',description:'Actions perform the real work of a transition, including notifications, templates and safe functions.',steps:['Choose an action type.','Configure inputs with dynamic values.','Order actions by execution priority.'],tips:['Safe functions use a controlled operation set and do not execute arbitrary JavaScript.']} },
  'workflow.participants': { ar:{title:'المشاركون',description:'حدد من يستلم مهمة الموافقة ومن يملك صلاحية إتمامها.',steps:['اختر المستخدمين أو المجموعات أو الأدوار.','اختر ANY أو ALL حسب سياسة الموافقة.','راجع المهمة من Waiting for my action.'],tips:['استخدم ALL للموافقات الجماعية وANY عندما يكفي أول رد صالح.']}, en:{title:'Participants',description:'Define who receives and can complete an approval task.',steps:['Choose users, groups or roles.','Select ANY or ALL approval policy.','Review tasks from Waiting for my action.'],tips:['Use ALL for collective approval and ANY when the first valid response is enough.']} },
  'workflow.sla': { ar:{title:'SLA والتصعيد',description:'حدد المهلة وساعات العمل والتنبيهات والتصعيد للمهمات.',steps:['حدد Due time وReminder.','اضبط المنطقة الزمنية وأيام وساعات العمل.','أضف مستويات التصعيد عند الحاجة.'],tips:['اختبر السيناريو خارج ساعات العمل للتأكد من احترام التقويم.']}, en:{title:'SLA and escalation',description:'Configure deadlines, working hours, reminders and escalation for tasks.',steps:['Set due and reminder times.','Configure timezone, working days and hours.','Add escalation levels when needed.'],tips:['Test scenarios outside working hours to verify calendar behavior.']} },
  'workflow.versions': { ar:{title:'الإصدارات',description:'النسخ المنشورة غير قابلة للتعديل وتثبت نسخة التشغيل التي استخدمها كل Run.',steps:['راجع سجل النسخ.','انشر نسخة جديدة بعد التعديل.','استخدم Rollback لإنشاء مسودة من نسخة سابقة.'],tips:['احتفظ بوصف واضح للتغييرات قبل النشر.']}, en:{title:'Versions',description:'Published versions are immutable and each run records the exact version it executed.',steps:['Review version history.','Publish a new version after changes.','Use rollback to create a draft from an earlier version.'],tips:['Keep changes clearly described before publishing.']} },
  'workflow.runs': { ar:{title:'سجل التشغيل',description:'راقب حالة التشغيل، النسخة، المهمة، أخطاء التنفيذ ومحاولات الطابور.',steps:['فلتر حسب الحالة أو التاريخ.','افتح تفاصيل Run لمراجعة الخطوات والـJobs.','أعد المحاولة فقط للتشغيلات الفاشلة.'],tips:['افحص lastError وlease قبل اعتبار المشكلة مشكلة في المحرك.']}, en:{title:'Run history',description:'Monitor run status, version, tasks, runtime errors and queue attempts.',steps:['Filter by status or date.','Open a run to inspect steps and jobs.','Retry only failed runs.'],tips:['Inspect lastError and lease information before treating an issue as an engine failure.']} },
  'workflow.tasks': { ar:{title:'المهام',description:'هنا تظهر المهام التي تنتظر إجراء المستخدمين والمشاركين.',steps:['افتح المهمة.','راجع الحقول والشروط والمشاركين.','اختر الانتقال وأضف تعليقاً عند الحاجة.'],tips:['المهام المتأخرة تظهر مع أولوية أو تصعيد وفق إعداد SLA.']}, en:{title:'Tasks',description:'This area contains approval tasks waiting for participant action.',steps:['Open the task.','Review fields, conditions and participants.','Choose the transition and add a comment when needed.'],tips:['Overdue tasks can show priority or escalation according to SLA.']} },
  'workflow.templates': { ar:{title:'قوالب البيانات',description:'قوالب قابلة لإعادة الاستخدام مع إصدارات ومعاينة وقيم ديناميكية.',steps:['أنشئ قالباً نصياً أو HTML أو JSON.','استخدم المتغيرات الديناميكية.','عاين ثم أنشئ إصداراً جديداً عند التعديل.'],tips:['لا تعتبر قوالب البيانات محرك PDF/DOCX كاملاً.']}, en:{title:'Data templates',description:'Reusable templates with versions, preview and dynamic values.',steps:['Create a TEXT, HTML or JSON template.','Use dynamic variables.','Preview it and create a new version when editing.'],tips:['Data templates are not a full PDF/DOCX rendering engine.']} },
  'workflow.functions': { ar:{title:'الدوال الآمنة',description:'دوال منظمة بإصدارات واختبار وعمليات مسموحة مسبقاً.',steps:['أنشئ تعريف الدالة.','اختبر المدخلات والمخرجات.','انشر إصداراً عند اعتماده.'],tips:['لا تسمح المنظومة بتنفيذ كود JavaScript عشوائي.']}, en:{title:'Safe functions',description:'Versioned, testable functions built from an allow-listed operation set.',steps:['Create the function definition.','Test inputs and outputs.','Publish the approved version.'],tips:['The system does not execute arbitrary JavaScript.']} },
  'workflow.diagnostics': { ar:{title:'التشخيص',description:'فحوصات صحة قاعدة البيانات والمحرك والطابور والقيم الديناميكية والإصدارات.',steps:['شغّل الفحص.','اقرأ الحالات PASS/WARN/FAIL.','افتح الطابور أو سجل التدقيق للمشكلة التفصيلية.'],tips:['وجود Dead-letter يستحق مراجعة فورية.']}, en:{title:'Diagnostics',description:'Health checks for database, engine, queue, dynamic values and versioning.',steps:['Run the health check.','Read PASS/WARN/FAIL states.','Open Queue or Audit for detailed investigation.'],tips:['Dead-letter jobs should be investigated promptly.']} },
  'workflow.queue': { ar:{title:'مركز الطابور',description:'راقب Jobs الفعلية: الحالة، المحاولات، الأولوية، الـLease والأخطاء.',steps:['فلتر حسب الحالة.','راجع المحاولات والـlastError.','استخدم Run history لإعادة تشغيل التشغيل الفاشل.'],tips:['وجود lease قد يعني أن Worker يعالج المهمة حالياً.']}, en:{title:'Queue center',description:'Monitor real jobs: status, attempts, priority, lease and errors.',steps:['Filter by job status.','Inspect attempts and lastError.','Use Run history to retry failed runs.'],tips:['An active lease may mean a worker is processing the job.']} },
  'workflow.audit': { ar:{title:'سجل التدقيق',description:'سجل تغييرات الإعدادات والتفعيل والإصدارات والقوالب والدوال وأحداث التشغيل.',steps:['فلتر حسب المورد أو الإجراء.','افتح metadata لمقارنة before/after.','استخدم الوقت والمستخدم لتتبع التغيير.'],tips:['سجل التدقيق لا يغيّر إعدادات النظام؛ هو للشفافية والتحقيق.']}, en:{title:'Audit center',description:'Track configuration, activation, version, template, function and runtime audit events.',steps:['Filter by resource or action.','Inspect metadata for before/after changes.','Use time and actor to trace changes.'],tips:['Audit is read-only and intended for transparency and investigation.']} },
  'workflow.dynamic-values': { ar:{title:'القيم الديناميكية',description:'متصفح مرئي للقيم التي يمكن استخدامها داخل الشروط والإجراءات والقوالب.',steps:['اختر namespace مثل file أو workflow.','انسخ المسار المطلوب.','استخدمه في الحقل أو الإجراء.'],tips:['قيمة مثل {{file.name}} تتغير حسب الملف الذي يشغّل العملية.']}, en:{title:'Dynamic values',description:'A visual browser of values available inside conditions, actions and templates.',steps:['Choose a namespace such as file or workflow.','Copy the required path.','Use it in a field or action.'],tips:['A value such as {{file.name}} changes with the file that triggers the run.']} },
};
