import {Workbook,SheetCell,activeSheet,cellKey,cloneWorkbook,parseKey} from './model';
export function addSheet(w:Workbook){const n=cloneWorkbook(w),id=`sheet-${Date.now()}`;n.sheets.push({id,name:`Sheet${n.sheets.length+1}`,cells:{}});n.activeSheet=id;return n}
export function deleteActiveSheet(w:Workbook){if(w.sheets.length<=1)return w;const n=cloneWorkbook(w),i=n.sheets.findIndex(s=>s.id===n.activeSheet);n.sheets.splice(i,1);n.activeSheet=n.sheets[Math.max(0,i-1)].id;return n}
export function renameSheet(w:Workbook,name:string){const n=cloneWorkbook(w),s=activeSheet(n);if(s)s.name=name.trim().slice(0,80)||s.name;return n}
export const setActiveSheet=(w:Workbook,id:string)=>({...w,activeSheet:id});
export function updateCell(w:Workbook,row:number,col:number,value:string,formula?:string){const n=cloneWorkbook(w),s=activeSheet(n);if(!s)return w;const key=cellKey(row,col);const old=s.cells[key];const cell:SheetCell={value:formula?null:(value===''?null:(/^[-+]?\d+(\.\d+)?$/.test(value)?Number(value):value)),...(formula?{formula}:{validation:old?.validation,format:old?.format})};if(value===''&&!formula){if(old?.validation)cell.validation=old.validation; if(old?.format)cell.format=old.format;if(!cell.validation&&!cell.format)delete s.cells[key];else s.cells[key]=cell}else s.cells[key]=cell;return n}
export function patchFormat(w:Workbook,key:string,format:Partial<NonNullable<SheetCell['format']>>){const n=cloneWorkbook(w),s=activeSheet(n);if(!s)return w;s.cells[key]={...(s.cells[key]??{value:null}),format:{...(s.cells[key]?.format??{}),...format}};return n}
export function setValidation(w:Workbook,key:string,validation:SheetCell['validation']){const n=cloneWorkbook(w),s=activeSheet(n);if(!s)return w;s.cells[key]={...(s.cells[key]??{value:null}),validation};return n}
export function setColumnWidth(w:Workbook,col:string,width:number){const n=cloneWorkbook(w),s=activeSheet(n);if(s)s.columnWidths={...(s.columnWidths??{}),[col]:Math.max(60,Math.min(420,width))};return n}
export function setRowHeight(w:Workbook,row:number,height:number){const n=cloneWorkbook(w),s=activeSheet(n);if(s)s.rowHeights={...(s.rowHeights??{}),[row]:Math.max(22,Math.min(100,height))};return n}
export function freeze(w:Workbook,rows:number,cols:number){const n=cloneWorkbook(w),s=activeSheet(n);if(s){s.frozenRows=Math.max(0,Math.min(20,rows));s.frozenColumns=Math.max(0,Math.min(10,cols))}return n}
export function mergeRange(w:Workbook,start:string,end:string){const n=cloneWorkbook(w),s=activeSheet(n);if(!s)return w;const a=parseKey(start)!,b=parseKey(end)!;const st=cellKey(Math.min(a.row,b.row),Math.min(a.col,b.col)),en=cellKey(Math.max(a.row,b.row),Math.max(a.col,b.col));s.merges=[...(s.merges??[]).filter(m=>!(m.start===st&&m.end===en)),{start:st,end:en}];return n}
export function unmergeRange(w:Workbook,start:string,end:string){const n=cloneWorkbook(w),s=activeSheet(n);if(s)s.merges=(s.merges??[]).filter(m=>!(m.start===start&&m.end===end));return n}
export function sortSheet(w:Workbook,column:string,direction:'asc'|'desc'){const n=cloneWorkbook(w),s=activeSheet(n);if(!s)return w;const rows=new Map<number,Record<string,SheetCell>>();for(const [k,v] of Object.entries(s.cells)){const p=parseKey(k)!;if(!rows.has(p.row))rows.set(p.row,{});rows.get(p.row)![k]=v}const ordered=[...rows.entries()].sort((a,b)=>{const av=a[1][`${column}${a[0]+1}`]?.value??'';const bv=b[1][`${column}${b[0]+1}`]?.value??'';return (av<bv?-1:av>bv?1:0)*(direction==='asc'?1:-1)});const cells:Record<string,SheetCell>={};ordered.forEach(([_,row],ri)=>Object.entries(row).forEach(([k,v])=>{const p=parseKey(k)!;cells[cellKey(ri,p.col)]=v}));s.cells=cells;s.sort={column,direction};return n}
export function setFilter(w:Workbook,column:string,query:string){const n=cloneWorkbook(w),s=activeSheet(n);if(s)s.filters={...(s.filters??{}),[column]:query};return n}
export function clearFilter(w:Workbook,column?:string){const n=cloneWorkbook(w),s=activeSheet(n);if(!s)return w;if(!column)s.filters=null;else{const f={...(s.filters??{})};delete f[column];s.filters=Object.keys(f).length?f:null}return n}

export function addNamedRange(w:Workbook,name:string,reference:string,scopeSheetId?:string){const n=cloneWorkbook(w);const clean=name.trim().replace(/\s+/g,'_').slice(0,80);if(!clean)return w;n.namedRanges=[...(n.namedRanges??[]).filter(x=>x.name.toLowerCase()!==clean.toLowerCase()),{name:clean,reference:reference.trim().toUpperCase().slice(0,200),scopeSheetId}];return n}
export function deleteNamedRange(w:Workbook,name:string){const n=cloneWorkbook(w);n.namedRanges=(n.namedRanges??[]).filter(x=>x.name.toLowerCase()!==name.toLowerCase());return n}
export function addTable(w:Workbook,start:string,end:string,name:string,hasHeader=true){const n=cloneWorkbook(w),s=activeSheet(n);if(!s)return w;const clean=name.trim().replace(/\s+/g,'_').slice(0,80);if(!clean)return w;s.tables=[...(s.tables??[]).filter(t=>t.name.toLowerCase()!==clean.toLowerCase()),{id:`table-${Date.now()}`,name:clean,start:start.toUpperCase(),end:end.toUpperCase(),hasHeader,style:'banded'}];return n}
export function deleteTable(w:Workbook,name:string){const n=cloneWorkbook(w),s=activeSheet(n);if(s)s.tables=(s.tables??[]).filter(t=>t.name.toLowerCase()!==name.toLowerCase());return n}
export function addPivotTable(w:Workbook,sourceRange:string,name:string,rowField?:string,valueField?:string,aggregation:'sum'|'count'|'average'='sum'){const n=cloneWorkbook(w),s=activeSheet(n);if(!s)return w;s.pivotTables=[...(s.pivotTables??[]),{id:`pivot-${Date.now()}`,name:name.trim().slice(0,80)||`Pivot${(s.pivotTables?.length??0)+1}`,sourceRange:sourceRange.toUpperCase(),rowField:rowField?.trim(),valueField:valueField?.trim(),aggregation}];return n}
