'use client';
import type { ReactNode } from 'react';
import type {SheetCell,NumberFormat} from './model';

type Props={cell?:SheetCell;tab?:'home'|'insert'|'data'|'view';onTabChange?:(v:'home'|'insert'|'data'|'view')=>void;onCopy?:()=>void;onCut?:()=>void;onPaste?:()=>void;onClear?:()=>void;onFreezeToggle?:()=>void;onBold:()=>void;onItalic:()=>void;onColor:(v:string)=>void;onBg:(v:string)=>void;onAlign:(v:'start'|'center'|'end')=>void;onFormat:(v:NumberFormat)=>void;onAddSheet:()=>void;onDeleteSheet:()=>void;onRename:()=>void;onFreeze:()=>void;onSort:()=>void;onMerge:()=>void;onUnmerge:()=>void;onFilter:()=>void;onValidation:()=>void;onNamedRange:()=>void;onTable:()=>void;onPivot:()=>void;onChart:()=>void;onConditional:()=>void};

const Group=({label,children}:{label:string;children:ReactNode})=><div className="flex min-h-[62px] flex-col justify-between border-r border-slate-200 px-2 py-1 last:border-r-0"><div className="flex flex-wrap items-center gap-1">{children}</div><div className="pt-1 text-[9px] font-medium uppercase tracking-wide text-slate-400">{label}</div></div>;
const Btn=({children,onClick,active=false,title}:{children:ReactNode;onClick:()=>void;active?:boolean;title?:string})=><button title={title} onClick={onClick} className={`h-7 rounded px-2 text-[11px] font-medium transition ${active?'bg-slate-200 text-slate-900':'text-slate-700 hover:bg-slate-100'}`}>{children}</button>;

export function SheetToolbar(p:Props){return <div className="border-b border-slate-200 bg-white shadow-sm"><div className="flex h-9 items-end gap-1 border-b border-slate-200 px-2">{([['home','Home'],['insert','Insert'],['data','Data'],['view','View']] as const).map(([id,label])=><button key={id} onClick={()=>p.onTabChange?.(id)} className={`h-8 rounded-t px-4 text-xs font-medium ${p.tab===id||(!p.tab&&id==='home')?'border border-b-white bg-white text-slate-900':'text-slate-500 hover:bg-slate-50'}`}>{label}</button>)}</div><div className="flex min-h-[74px] items-stretch overflow-x-auto px-1">
  <Group label="Clipboard">{p.onCopy&&<Btn onClick={p.onCopy}>Copy</Btn>}{p.onCut&&<Btn onClick={p.onCut}>Cut</Btn>}{p.onPaste&&<Btn onClick={p.onPaste}>Paste</Btn>}{p.onClear&&<Btn onClick={p.onClear}>Clear</Btn>}<Btn onClick={p.onBold} active={!!p.cell?.format?.bold} title="Bold">B</Btn><Btn onClick={p.onItalic} active={!!p.cell?.format?.italic} title="Italic"><i>I</i></Btn><label className="flex h-7 items-center gap-1 rounded px-2 text-[11px] hover:bg-slate-100">A<input aria-label="Font color" type="color" value={p.cell?.format?.color??'#111827'} onChange={e=>p.onColor(e.target.value)} className="h-4 w-4 border-0 p-0"/></label></Group>
  <Group label="Font"><label className="flex h-7 items-center gap-1 rounded border border-slate-200 px-1 text-[10px]">Fill<input aria-label="Cell fill" type="color" value={p.cell?.format?.background??'#ffffff'} onChange={e=>p.onBg(e.target.value)} className="h-4 w-4 border-0 p-0"/></label><select aria-label="Alignment" className="h-7 rounded border border-slate-200 px-1 text-[11px]" value={p.cell?.format?.align??'start'} onChange={e=>p.onAlign(e.target.value as any)}><option value="start">Left</option><option value="center">Center</option><option value="end">Right</option></select></Group>
  <Group label="Number"><select aria-label="Number format" className="h-7 rounded border border-slate-200 px-1 text-[11px]" value={p.cell?.format?.numberFormat??'general'} onChange={e=>p.onFormat(e.target.value as NumberFormat)}><option value="general">General</option><option value="number">Number</option><option value="currency">Currency</option><option value="percent">Percent</option><option value="date">Date</option></select></Group>
  <Group label="Data"><Btn onClick={p.onSort}>Sort</Btn><Btn onClick={p.onFilter}>Filter</Btn><Btn onClick={p.onValidation}>Validation</Btn><Btn onClick={p.onConditional}>Conditional</Btn></Group>
  <Group label="Insert"><Btn onClick={p.onTable}>Table</Btn><Btn onClick={p.onPivot}>Pivot</Btn><Btn onClick={p.onChart}>Chart</Btn><Btn onClick={p.onNamedRange}>Name</Btn></Group>
  <Group label="Layout"><Btn onClick={p.onFreezeToggle??p.onFreeze}>Freeze</Btn><Btn onClick={p.onMerge}>Merge</Btn><Btn onClick={p.onUnmerge}>Unmerge</Btn><Btn onClick={p.onInsertRows}>+ Row</Btn><Btn onClick={p.onDeleteRows}>− Row</Btn><Btn onClick={p.onInsertColumns}>+ Col</Btn><Btn onClick={p.onDeleteColumns}>− Col</Btn></Group>
  <Group label="Sheets"><Btn onClick={p.onAddSheet}>＋ Sheet</Btn><Btn onClick={p.onRename}>Rename</Btn><Btn onClick={p.onDeleteSheet}>Delete</Btn></Group>
</div></div>}
