"use client";
import { useEffect, useState } from "react";
import { WorkflowShell } from "@/components/workflow-shell";
import { WorkflowHelp } from "@/components/workflow-help";
import { useLocale } from "@/components/locale-provider";
import { createWorkflowFunction, listWorkflowFunctionVersions, listWorkflowFunctions, publishWorkflowFunctionVersion, testWorkflowFunction, type WorkflowFunction, type WorkflowFunctionVersion } from "@/lib/api/workflows";

const starter = { name:"Normalize file status", key:"normalize_file_status", description:"Safely set a workflow field from file metadata.", definition:{operations:[{op:"SET_FIELD",field:"status",value:"{{file.extension}}"}]}, runtime:"SAFE", permissions:["read_file_metadata","write_workflow_fields"], timeoutMs:1000, memoryLimitMb:64 };
export default function WorkflowFunctionsPage(){
 const {locale}=useLocale(); const ar=locale==="ar"; const [rows,setRows]=useState<WorkflowFunction[]>([]); const [open,setOpen]=useState(false); const [draft,setDraft]=useState(starter); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [versions,setVersions]=useState<WorkflowFunctionVersion[]>([]); const [selected,setSelected]=useState<WorkflowFunction|null>(null); const [result,setResult]=useState<unknown>(null);
 const load=()=>void listWorkflowFunctions().then(r=>setRows(r.custom||[])).catch(e=>setError(e instanceof Error?e.message:"Unable to load functions")); useEffect(load,[]);
 const create=async()=>{setBusy(true);setError("");try{await createWorkflowFunction(draft);setOpen(false);load()}catch(e){setError(e instanceof Error?e.message:(ar?"تعذر إنشاء الدالة":"Unable to create function"))}finally{setBusy(false)}};
 const showVersions=async(f:WorkflowFunction)=>{setSelected(f);try{setVersions(await listWorkflowFunctionVersions(f.id))}catch(e){setError(e instanceof Error?e.message:"Unable to load versions")}};
 const publish=async(v:WorkflowFunctionVersion)=>{if(!selected)return;setBusy(true);try{await publishWorkflowFunctionVersion(selected.id,v.id);load();setSelected(null)}catch(e){setError(e instanceof Error?e.message:"Unable to publish")}finally{setBusy(false)}};
 const test=async(f:WorkflowFunction)=>{setBusy(true);setError("");try{setResult(await testWorkflowFunction(f.id,{file:{id:"test-file",name:"contract.pdf",extension:".pdf",fileType:"PDF",mimeType:"application/pdf"},fields:{status:"pending"}}))}catch(e){setError(e instanceof Error?e.message:"Function test failed")}finally{setBusy(false)}};
 return <WorkflowShell active="functions" title={ar?"الدوال الآمنة":"Safe workflow functions"} subtitle={ar?"دوال بإصدارات ثابتة وتنفيذ محكوم بدون وصول مباشر إلى النظام.":"Versioned controlled functions with no direct access to the server process."}>
 <main className="h-full overflow-y-auto p-4 sm:p-5" dir={ar?"rtl":"ltr"}><div className="mx-auto max-w-[1200px]">
  <div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><WorkflowHelp compact helpKey="workflow.functions" title={ar?"ما هي الدوال الآمنة؟":"What are safe functions?"} description={ar?"تنفذ عمليات محددة مسبقاً داخل عقد آمن. لا تسمح V17-A بتشغيل JavaScript عشوائي أو الوصول إلى الملفات والعمليات والبيئة.":"Controlled operations execute through a safe contract. V17-A does not allow arbitrary JavaScript, filesystem, process or environment access."}/><span className="text-[10px] text-slate-500">{rows.length} {ar?"دوال":"functions"}</span></div><button className="wd-pill wd-pill-new" onClick={()=>{setDraft(starter);setOpen(true)}}>＋ {ar?"دالة آمنة جديدة":"New safe function"}</button></div>
  <div className="wd-card mt-5 p-4"><div className="grid gap-3 sm:grid-cols-3"><div><div className="text-[9px] uppercase tracking-[.14em] text-slate-400">Runtime</div><div className="mt-1 text-[12px] font-semibold">SAFE</div></div><div><div className="text-[9px] uppercase tracking-[.14em] text-slate-400">Isolation</div><div className="mt-1 text-[12px] font-semibold">{ar?"عمليات مسموحة فقط":"Allow-listed operations"}</div></div><div><div className="text-[9px] uppercase tracking-[.14em] text-slate-400">Limits</div><div className="mt-1 text-[12px] font-semibold">100–5000ms · 16–128MB</div></div></div></div>
  {rows.length===0?<div className="wd-card mt-4 border-dashed p-10 text-center"><h2 className="text-[13px] font-semibold">{ar?"لا توجد دوال مخصصة":"No custom functions"}</h2><p className="mt-1 text-[10px] text-slate-500">{ar?"أنشئ دالة من العمليات الآمنة المحددة.":"Create a function using the controlled operation set."}</p></div>:<div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{rows.map(f=><article key={f.id} className="wd-card flex min-h-[210px] flex-col p-4"><div className="flex items-start justify-between"><div className="wf-icon">ƒ</div><span className="rounded-full bg-slate-100 px-2 py-1 text-[8px]">v{f.activeVersion?.version??1}</span></div><h3 className="mt-3 text-[12.5px] font-semibold">{f.name}</h3><p className="mt-1 text-[10px] leading-5 text-slate-500">{f.description||f.key}</p><div className="mt-auto flex flex-wrap gap-1.5 pt-4"><button className="wd-pill wd-pill-new" onClick={()=>void test(f)}>{ar?"اختبار":"Test"}</button><button className="wd-pill wd-pill-new" onClick={()=>void showVersions(f)}>{ar?"الإصدارات":"Versions"}</button></div></article>)}</div>}
  {error&&<div className="mt-4 rounded-xl bg-red-50 p-3 text-[10px] text-red-700">{error}</div>}
  {result&&<div className="wd-card mt-4 p-4"><div className="text-[10px] font-semibold">{ar?"نتيجة الاختبار":"Test result"}</div><pre className="mt-2 max-h-64 overflow-auto rounded-xl bg-slate-50 p-3 text-[9px] whitespace-pre-wrap">{JSON.stringify(result,null,2)}</pre></div>}
 </div></main>
 {open&&<div className="fixed inset-0 z-[240] flex items-center justify-center bg-slate-950/40 p-4"><div className="wf-modal w-[min(760px,96vw)] p-5" dir={ar?"rtl":"ltr"}><h2 className="text-[17px] font-semibold">{ar?"إنشاء دالة آمنة":"Create safe function"}</h2><div className="mt-4 grid gap-3"><input className="wf-input" placeholder={ar?"اسم الدالة":"Function name"} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/><input className="wf-input" placeholder="unique_key" value={draft.key} onChange={e=>setDraft({...draft,key:e.target.value})}/><textarea className="wf-input min-h-[180px] font-mono" value={JSON.stringify(draft.definition,null,2)} onChange={e=>{try{setDraft({...draft,definition:JSON.parse(e.target.value)})}catch{}}}/><div className="rounded-xl bg-slate-50 p-3 text-[9px] leading-5 text-slate-500">{ar?"العمليات المتاحة: SET_FIELD, COPY_VALUE, CONCAT, LOWERCASE, UPPERCASE, NUMBER, ADD, SUBTRACT, MULTIPLY, DIVIDE, NOTIFY_OWNER, ADD_TAG, IF":"Allowed: SET_FIELD, COPY_VALUE, CONCAT, LOWERCASE, UPPERCASE, NUMBER, ADD, SUBTRACT, MULTIPLY, DIVIDE, NOTIFY_OWNER, ADD_TAG, IF"}</div></div><div className="mt-5 flex justify-end gap-2"><button className="wd-pill wd-pill-new" onClick={()=>setOpen(false)}>{ar?"إلغاء":"Cancel"}</button><button className="wd-pill wd-pill-new" disabled={busy} onClick={()=>void create()}>{ar?"إنشاء":"Create"}</button></div></div></div>}
 {selected&&<div className="fixed inset-0 z-[240] flex items-center justify-center bg-slate-950/40 p-4"><div className="wf-modal w-[min(760px,96vw)] p-5" dir={ar?"rtl":"ltr"}><div className="flex items-center justify-between"><div><h2 className="text-[16px] font-semibold">{selected.name}</h2><p className="text-[10px] text-slate-500">{ar?"إصدارات الدالة":"Function versions"}</p></div><button className="wd-icon-btn" onClick={()=>setSelected(null)}>×</button></div><div className="mt-4 space-y-2">{versions.map(v=><div key={v.id} className="rounded-xl border border-slate-100 p-3"><div className="flex items-center justify-between"><b className="text-[11px]">v{v.version}</b><button disabled={busy||v.status==="ACTIVE"} className="wd-pill wd-pill-new" onClick={()=>void publish(v)}>{v.status==="ACTIVE"?(ar?"نشطة":"Active"):(ar?"نشر":"Publish")}</button></div><pre className="mt-2 max-h-32 overflow-auto rounded-lg bg-slate-50 p-2 text-[8.5px] whitespace-pre-wrap">{JSON.stringify(v.definition,null,2)}</pre></div>)}</div></div></div>}
 </WorkflowShell>
}
