"use client";
import { useEffect, useState } from "react";
import { WorkflowShell } from "@/components/workflow-shell";
import { WorkflowHelp } from "@/components/workflow-help";
import { WorkflowConceptGuide } from "@/components/workflow-concept-guide";
import { useLocale } from "@/components/locale-provider";
import { createWorkflowFunction, updateWorkflowFunction, deleteWorkflowFunction, createWorkflowFunctionVersion, listWorkflowFunctionExecutions, listWorkflowFunctionVersions, listWorkflowFunctions, listConnections, publishWorkflowFunctionVersion, testWorkflowFunction, type WorkflowFunction, type WorkflowFunctionVersion, type Connection } from "@/lib/api/workflows";

const starter = { name:"Normalize file status", key:"normalize_file_status", description:"Safely set a workflow field from file metadata.", definition:{operations:[{op:"SET_FIELD",field:"status",value:"{{file.extension}}"}]}, runtime:"SAFE", permissions:["read_file_metadata","write_workflow_fields"], timeoutMs:1000, memoryLimitMb:64 };
export default function WorkflowFunctionsPage(){
 const {locale}=useLocale(); const ar=locale==="ar"; const [rows,setRows]=useState<WorkflowFunction[]>([]); const [open,setOpen]=useState(false); const [draft,setDraft]=useState(starter); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [versions,setVersions]=useState<WorkflowFunctionVersion[]>([]); const [selected,setSelected]=useState<WorkflowFunction|null>(null); const [result,setResult]=useState<unknown>(null); const [connections,setConnections]=useState<Connection[]>([]); const [executions,setExecutions]=useState<any[]>([]); const [editName,setEditName]=useState("");
 const operations=Array.isArray((draft.definition as any)?.operations)?(draft.definition as any).operations:[];
 const updateOperation=(index:number, patch:Record<string,unknown>)=>setDraft({...draft,definition:{...((draft.definition as any)||{}),operations:operations.map((op:any,i:number)=>i===index?{...op,...patch}:op)}});
 const addOperation=(op:string)=>setDraft({...draft,definition:{...((draft.definition as any)||{}),operations:[...operations,{op,field:op==="HTTP_REQUEST"?"response":"result",value:"",left:"",right:"",connectionId:"",method:"GET",path:"/",outputField:"response"}]}});
 const removeOperation=(index:number)=>setDraft({...draft,definition:{...((draft.definition as any)||{}),operations:operations.filter((_:any,i:number)=>i!==index)}});

 useEffect(()=>{ void listConnections({status:"ACTIVE"}).then(setConnections).catch(()=>undefined); },[]);
 const load=()=>void listWorkflowFunctions().then(r=>setRows(r.custom||[])).catch(e=>setError(e instanceof Error?e.message:"Unable to load functions")); useEffect(load,[]);
 const create=async()=>{setBusy(true);setError("");try{await createWorkflowFunction(draft);setOpen(false);load()}catch(e){setError(e instanceof Error?e.message:(ar?"تعذر إنشاء الدالة":"Unable to create function"))}finally{setBusy(false)}};
 const showVersions=async(f:WorkflowFunction)=>{setSelected(f);setEditName(f.name);try{const [vs,ex]=await Promise.all([listWorkflowFunctionVersions(f.id),listWorkflowFunctionExecutions(f.id)]);setVersions(vs);setExecutions(ex)}catch(e){setError(e instanceof Error?e.message:"Unable to load versions")}};
 const saveMeta=async()=>{if(!selected)return;setBusy(true);try{const next=await updateWorkflowFunction(selected.id,{name:editName});setSelected(next);load()}catch(e){setError(e instanceof Error?e.message:"Unable to update")}finally{setBusy(false)}};
 const remove=async()=>{if(!selected)return;setBusy(true);try{await deleteWorkflowFunction(selected.id);setSelected(null);load()}catch(e){setError(e instanceof Error?e.message:"Unable to delete; the function may be referenced by a workflow")}finally{setBusy(false)}};
 const forkVersion=async(v:WorkflowFunctionVersion)=>{if(!selected)return;setBusy(true);try{const created=await createWorkflowFunctionVersion(selected.id,{definition:v.definition});setVersions([created,...versions]);}catch(e){setError(e instanceof Error?e.message:"Unable to create draft version")}finally{setBusy(false)}};
 const publish=async(v:WorkflowFunctionVersion)=>{if(!selected)return;setBusy(true);try{await publishWorkflowFunctionVersion(selected.id,v.id);load();setSelected(null)}catch(e){setError(e instanceof Error?e.message:"Unable to publish")}finally{setBusy(false)}};
 const test=async(f:WorkflowFunction,versionId?:string)=>{setBusy(true);setError("");try{setResult(await testWorkflowFunction(f.id,{file:{id:"test-file",name:"contract.pdf",extension:".pdf",fileType:"PDF",mimeType:"application/pdf"},fields:{status:"pending"}},versionId))}catch(e){setError(e instanceof Error?e.message:"Function test failed")}finally{setBusy(false)}};
 return <WorkflowShell active="functions" title={ar?"الدوال الآمنة":"Safe workflow functions"} subtitle={ar?"دوال بإصدارات ثابتة وتنفيذ محكوم بدون وصول مباشر إلى النظام.":"Versioned controlled functions with no direct access to the server process."}>
 <main className="h-full min-h-0 overflow-y-auto bg-white p-2 sm:p-3" dir={ar?"rtl":"ltr"}><div className="flex min-h-full w-full flex-col">
  <div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><WorkflowHelp compact helpKey="workflow.functions" title={ar?"ما هي الدوال الآمنة؟":"What are safe functions?"} description={ar?"تنفذ عمليات محددة مسبقاً داخل عقد آمن. لا تسمح V17-A بتشغيل JavaScript عشوائي أو الوصول إلى الملفات والعمليات والبيئة.":"Controlled operations execute through a safe contract. V17-A does not allow arbitrary JavaScript, filesystem, process or environment access."}/><span className="text-[10px] text-slate-500">{rows.length} {ar?"دوال":"functions"}</span></div><button className="wd-pill wd-pill-new" onClick={()=>{setDraft(starter);setOpen(true)}}>＋ {ar?"دالة آمنة جديدة":"New safe function"}</button></div>
  <div className="mt-4"><WorkflowConceptGuide ar={ar} /></div>
    <div className="wd-card mt-4 p-4"><div className="grid gap-3 sm:grid-cols-3"><div><div className="text-[9px] uppercase tracking-[.14em] text-slate-400">Runtime</div><div className="mt-1 text-[12px] font-semibold">SAFE</div></div><div><div className="text-[9px] uppercase tracking-[.14em] text-slate-400">Isolation</div><div className="mt-1 text-[12px] font-semibold">{ar?"عمليات مسموحة فقط":"Allow-listed operations"}</div></div><div><div className="text-[9px] uppercase tracking-[.14em] text-slate-400">Limits</div><div className="mt-1 text-[12px] font-semibold">100–5000ms · 16–128MB</div></div></div></div>
  {rows.length===0?<div className="wd-card mt-4 border-dashed p-10 text-center"><h2 className="text-[13px] font-semibold">{ar?"لا توجد دوال مخصصة":"No custom functions"}</h2><p className="mt-1 text-[10px] text-slate-500">{ar?"أنشئ دالة من العمليات الآمنة المحددة.":"Create a function using the controlled operation set."}</p></div>:<div className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{rows.map(f=><article key={f.id} className="wd-card flex min-h-[210px] w-full flex-col p-4"><div className="flex items-start justify-between"><div className="wf-icon">ƒ</div><span className="rounded-full bg-slate-100 px-2 py-1 text-[8px]">v{f.activeVersion?.version??1}</span></div><h3 className="mt-3 text-[12.5px] font-semibold">{f.name}</h3><p className="mt-1 text-[10px] leading-5 text-slate-500">{f.description||f.key}</p><div className="mt-auto flex flex-wrap gap-1.5 pt-4"><button className="wd-pill wd-pill-record" onClick={()=>void test(f)}>{ar?"اختبار":"Test"}</button><button className="wd-pill wd-pill-record" onClick={()=>void showVersions(f)}>{ar?"الإصدارات":"Versions"}</button></div></article>)}</div>}
  {error&&<div className="mt-4 rounded-xl bg-red-50 p-3 text-[10px] text-red-700">{error}</div>}
  {result&&<div className="wd-card mt-4 p-4"><div className="text-[10px] font-semibold">{ar?"نتيجة الاختبار":"Test result"}</div><pre className="mt-2 max-h-64 overflow-auto rounded-xl bg-slate-50 p-3 text-[9px] whitespace-pre-wrap">{JSON.stringify(result,null,2)}</pre></div>}
 </div></main>
 {open&&<div className="fixed inset-0 z-[240] flex items-center justify-center bg-slate-950/40 p-4"><div className="wf-modal w-[min(760px,96vw)] p-5" dir={ar?"rtl":"ltr"}><h2 className="text-[17px] font-semibold">{ar?"إنشاء دالة آمنة":"Create safe function"}</h2><div className="mt-4 rounded-xl border border-violet-200 bg-violet-50/60 p-3"><div className="text-[10px] font-semibold text-violet-900">{ar?"كيف تعمل الدالة؟":"How does a function work?"}</div><p className="mt-1 text-[9px] leading-4 text-violet-800">{ar?"الدالة عبارة عن سلسلة عمليات SAFE محددة. يمكن ربطها بـWorkflow كإجراء، ويمكن لعملية HTTP_REQUEST أن تستخدم Connection للوصول إلى خدمة خارجية.":"A function is a sequence of controlled SAFE operations. A workflow can run it as an action, and HTTP_REQUEST can use a Connection to reach an external service."}</p></div><div className="mt-4 grid gap-3"><input className="wf-input" placeholder={ar?"اسم الدالة":"Function name"} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/><input className="wf-input" placeholder="unique_key" value={draft.key} onChange={e=>setDraft({...draft,key:e.target.value})}/><div className="rounded-xl border border-emerald-200 bg-emerald-50/60 p-3"><div className="text-[10px] font-semibold text-emerald-900">{ar?"استخدام Connection داخل الدالة":"Use a Connection inside the function"}</div><p className="mt-1 text-[9px] leading-4 text-emerald-800">{ar?"اختر اتصال OAuth، ثم أضف HTTP_REQUEST. عند التنفيذ سيستخدم الخادم اعتماد الاتصال تلقائياً.":"Select an OAuth connection, then add HTTP_REQUEST. At runtime the server uses the connection authorization automatically."}</p><div className="mt-2 flex flex-wrap items-center gap-2"><select className="wf-input min-w-[220px]" id="function-rest-connection"><option value="">{ar?"اختر اتصالاً لإضافة طلب HTTP":"Select connection to add HTTP request"}</option>{connections.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button type="button" className="wd-pill wd-pill-record" onClick={()=>{const el=document.getElementById("function-rest-connection") as HTMLSelectElement|null; const id=el?.value; if(!id)return; const d=draft.definition&&typeof draft.definition==="object"?draft.definition as any:{}; const ops=Array.isArray(d.operations)?d.operations:[]; setDraft({...draft,definition:{...d,operations:[...ops,{op:"HTTP_REQUEST",connectionId:id,method:"GET",path:"/",outputField:"http"}]}})}}>{ar?"＋ إضافة طلب HTTP":"＋ Add HTTP request"}</button></div></div><div className="rounded-xl border border-slate-200 bg-white p-3">
<div className="text-[9px] font-semibold uppercase tracking-[.14em] text-slate-400">{ar ? "كيف تبني الدالة؟" : "How to build the function"}</div>
<div className="mt-2 grid gap-2 sm:grid-cols-3">
<div className="rounded-lg bg-slate-50 p-2.5"><div className="text-[9px] font-semibold text-slate-700">1 · {ar ? "Input" : "Input"}</div><div className="mt-1 text-[8.5px] leading-4 text-slate-500">{ar ? "استخدم قيم الملف وحقول Workflow كمدخلات." : "Use file values and workflow fields as inputs."}</div></div>
<div className="rounded-lg bg-slate-50 p-2.5"><div className="text-[9px] font-semibold text-slate-700">2 · {ar ? "Operations" : "Operations"}</div><div className="mt-1 text-[8.5px] leading-4 text-slate-500">{ar ? "نفذ عمليات SAFE بالترتيب. استخدم HTTP_REQUEST فقط عند الحاجة." : "Run SAFE operations in order. Use HTTP_REQUEST only when needed."}</div></div>
<div className="rounded-lg bg-slate-50 p-2.5"><div className="text-[9px] font-semibold text-slate-700">3 · {ar ? "Output" : "Output"}</div><div className="mt-1 text-[8.5px] leading-4 text-slate-500">{ar ? "احفظ النتيجة في outputField ثم استخدمها في Workflow." : "Store the result in an output field and use it in the workflow."}</div></div>
</div></div>
<div className="rounded-xl border border-slate-200 bg-white p-3">
<div className="flex items-center justify-between gap-2"><div><div className="text-[10px] font-semibold text-slate-800">{ar?"خطوات الدالة":"Function steps"}</div><div className="mt-1 text-[8.5px] text-slate-500">{ar?"ابنِ الدالة خطوة بخطوة؛ لا تحتاج لكتابة JSON.":"Build the function step by step — no JSON required."}</div></div><button type="button" className="wd-pill wd-pill-record" onClick={()=>addOperation("SET_FIELD")}>＋ {ar?"إضافة خطوة":"Add step"}</button></div>
<div className="mt-3 space-y-2">{operations.map((op:any,index:number)=>{
 const kind=String(op.op||"SET_FIELD");
 const set=(patch:Record<string,unknown>)=>updateOperation(index,patch);
 return <div key={index} className="rounded-xl border border-slate-200 bg-slate-50/70 p-3">
  <div className="flex items-center gap-2"><span className="grid h-6 w-6 place-items-center rounded-full bg-white text-[9px] font-bold text-slate-500">{index+1}</span>
  <select className="wf-input flex-1" value={kind} onChange={e=>set({op:e.target.value})}>
   {["SET_FIELD","COPY_VALUE","CONCAT","LOWERCASE","UPPERCASE","NUMBER","ADD","SUBTRACT","MULTIPLY","DIVIDE","NOTIFY_OWNER","ADD_TAG","IF","HTTP_REQUEST"].map(v=><option key={v}>{v}</option>)}
  </select><button type="button" className="wd-icon-btn" onClick={()=>removeOperation(index)}>×</button></div>
  <div className="mt-2 grid gap-2 sm:grid-cols-2">
   {["SET_FIELD","COPY_VALUE","CONCAT","LOWERCASE","UPPERCASE","NUMBER","ADD","SUBTRACT","MULTIPLY","DIVIDE"].includes(kind)?<input className="wf-input" placeholder={ar?"اسم حقل النتيجة":"Output field"} value={String(op.field??"")} onChange={e=>set({field:e.target.value})}/>:null}
   {["SET_FIELD","CONCAT"].includes(kind)?<input className="wf-input" placeholder={ar?"القيمة أو {{file.name}}":"Value or {{file.name}}"} value={String(op.value??"")} onChange={e=>set({value:e.target.value})}/>:null}
   {["COPY_VALUE","LOWERCASE","UPPERCASE","NUMBER","ADD","SUBTRACT","MULTIPLY","DIVIDE","CONCAT"].includes(kind)?<input className="wf-input" placeholder={ar?"القيمة الأولى / المصدر":"First value / source"} value={String(op.left??"")} onChange={e=>set({left:e.target.value})}/>:null}
   {["ADD","SUBTRACT","MULTIPLY","DIVIDE","CONCAT"].includes(kind)?<input className="wf-input" placeholder={ar?"القيمة الثانية":"Second value"} value={String(op.right??"")} onChange={e=>set({right:e.target.value})}/>:null}
   {kind==="CONCAT"?<input className="wf-input" placeholder={ar?"الفاصل (اختياري)":"Separator (optional)"} value={String(op.separator??"")} onChange={e=>set({separator:e.target.value})}/>:null}
   {kind==="ADD_TAG"?<input className="wf-input" placeholder={ar?"اسم الوسم":"Tag"} value={String(op.tag??"")} onChange={e=>set({tag:e.target.value})}/>:null}
   {kind==="NOTIFY_OWNER"?<><input className="wf-input" placeholder={ar?"عنوان الإشعار":"Notification title"} value={String(op.title??"")} onChange={e=>set({title:e.target.value})}/><input className="wf-input" placeholder={ar?"نص الإشعار":"Notification body"} value={String(op.body??"")} onChange={e=>set({body:e.target.value})}/></>:null}
   {kind==="HTTP_REQUEST"?<>
    <select className="wf-input" value={String(op.connectionId??"")} onChange={e=>set({connectionId:e.target.value})}><option value="">{ar?"اختر اتصالاً":"Select connection"}</option>{connections.map(c=><option key={c.id} value={c.id}>{c.name} · {c.provider}</option>)}</select>
    <select className="wf-input" value={String(op.method??"GET")} onChange={e=>set({method:e.target.value})}>{["GET","POST","PUT","PATCH","DELETE","HEAD"].map(v=><option key={v}>{v}</option>)}</select>
    <div className="sm:col-span-2"><input className="wf-input w-full" placeholder="/v1/resource or ?id={{file.id}}" value={String(op.path??"/")} onChange={e=>set({path:e.target.value})}/><div className="mt-1 text-[8px] leading-4 text-slate-500">{ar?"المسار نسبي إلى Base URL للاتصال. مثال: /v1/files أو ?id={{file.id}}. لا تضع الدومين الكامل.":"Path is relative to the connection Base URL. Example: /v1/files or ?id={{file.id}}. Do not enter the full domain."}</div></div>
    <input className="wf-input" placeholder={ar?"حقل حفظ الاستجابة":"Response output field"} value={String(op.outputField??"response")} onChange={e=>set({outputField:e.target.value})}/>
   </>:null}
  </div>
 </div>})}</div>
 {operations.length===0?<div className="mt-3 rounded-lg border border-dashed border-slate-200 p-4 text-center text-[9px] text-slate-500">{ar?"أضف أول خطوة للبدء.":"Add the first step to start."}</div>:null}
 <div className="mt-3 flex flex-wrap gap-1.5">{["SET_FIELD","COPY_VALUE","CONCAT","LOWERCASE","UPPERCASE","NUMBER","ADD","SUBTRACT","MULTIPLY","DIVIDE","NOTIFY_OWNER","ADD_TAG","IF","HTTP_REQUEST"].map(v=><button key={v} type="button" className="rounded-full border border-slate-200 bg-white px-2 py-1 text-[8px] text-slate-600" onClick={()=>addOperation(v)}>＋ {v}</button>)}</div>
</div>
<details className="rounded-xl border border-slate-200 bg-slate-50 p-3"><summary className="cursor-pointer text-[9px] font-semibold text-slate-600">{ar?"تحرير JSON متقدم (اختياري)":"Advanced JSON editor (optional)"}</summary><textarea className="wf-input mt-3 min-h-[160px] font-mono" value={JSON.stringify(draft.definition,null,2)} onChange={e=>{try{setDraft({...draft,definition:JSON.parse(e.target.value)})}catch{}}}/></details></div><div className="mt-5 flex justify-end gap-2"><button className="wd-pill wd-pill-record" onClick={()=>setOpen(false)}>{ar?"إلغاء":"Cancel"}</button><button className="wd-pill wd-pill-new" disabled={busy} onClick={()=>void create()}>{ar?"إنشاء":"Create"}</button></div></div></div>}
 {selected&&<div className="fixed inset-0 z-[240] flex items-center justify-center bg-slate-950/40 p-4"><div className="wf-modal w-[min(820px,96vw)] max-h-[90vh] overflow-y-auto p-5" dir={ar?"rtl":"ltr"}>
  <div className="flex items-center justify-between"><div><h2 className="text-[16px] font-semibold">{selected.name}</h2><p className="text-[10px] text-slate-500">{ar?"إصدارات وتنفيذ الدالة":"Function versions and executions"}</p></div><button className="wd-icon-btn" onClick={()=>setSelected(null)}>×</button></div>
  <div className="mt-4 grid gap-2 sm:grid-cols-[1fr_auto_auto]"><input className="wf-input" value={editName} onChange={e=>setEditName(e.target.value)} /><button className="wd-pill wd-pill-record" disabled={busy} onClick={()=>void saveMeta()}>{ar?"حفظ":"Save"}</button><button className="wd-pill wd-pill-record" disabled={busy} onClick={()=>void remove()}>{ar?"حذف":"Delete"}</button></div>
  <div className="mt-4 space-y-2">{versions.map(v=><div key={v.id} className="wd-card p-3"><div className="flex items-center justify-between gap-2"><b className="text-[11px]">v{v.version}</b><div className="flex flex-wrap gap-1"><button disabled={busy} className="wd-pill wd-pill-record" onClick={()=>void test(selected,v.id)}>{ar?"اختبار":"Test"}</button><button disabled={busy||v.status==="ACTIVE"} className="wd-pill wd-pill-new" onClick={()=>void publish(v)}>{v.status==="ACTIVE"?(ar?"نشطة":"Active"):(ar?"نشر":"Publish")}</button><button disabled={busy} className="wd-pill wd-pill-record" onClick={()=>void forkVersion(v)}>{ar?"نسخة مسودة":"New draft"}</button></div></div><div className="mt-1 text-[8px] uppercase tracking-wider text-slate-400">{v.status}</div><pre className="mt-2 max-h-32 overflow-auto rounded-lg bg-slate-50 p-2 text-[8.5px] whitespace-pre-wrap">{JSON.stringify(v.definition,null,2)}</pre></div>)}</div>
  <div className="mt-5"><div className="text-[10px] font-semibold">{ar?"آخر عمليات التنفيذ":"Recent executions"}</div><div className="mt-2 max-h-40 space-y-1 overflow-auto">{executions.map(x=><div key={x.id} className="flex items-center justify-between rounded-lg bg-slate-50 px-3 py-2 text-[9px]"><span>{x.status} · v{x.versionId.slice(0,6)}</span><span>{x.durationMs??"-"} ms</span></div>)}</div></div>
 </div></div>}
 </WorkflowShell>
}
