"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import { ZohoWorkdriveLayout } from "@/components/layout/zoho-workdrive-layout";
import { SecondarySidebar } from "@/components/layout/secondary-sidebar";
import { useLocale } from "@/components/locale-provider";
import { createWorkflow, getWorkflow, updateWorkflow, type Workflow } from "@/lib/api/workflows";

type StateDraft={name:string;description:string;terminal:boolean};
export default function WorkflowBuilderPage(){
 const {label}=useLocale(); const params=useSearchParams(); const id=params.get("id");
 const [name,setName]=useState(""); const [description,setDescription]=useState(""); const [mode,setMode]=useState<"AUTOMATIC"|"MANUAL">("AUTOMATIC"); const [resourceType,setResourceType]=useState<"FILE"|"FOLDER">("FILE"); const [trigger,setTrigger]=useState("upload"); const [condition,setCondition]=useState("any"); const [actions,setActions]=useState<Array<{type:string;config:Record<string,unknown>}>>([{type:"notify",config:{}}]); const [states,setStates]=useState<StateDraft[]>([{name:"Start",description:"",terminal:false},{name:"Completed",description:"",terminal:true}]); const [loading,setLoading]=useState(!!id); const [busy,setBusy]=useState(false); const [saved,setSaved]=useState(false);
 useEffect(()=>{if(!id)return; void getWorkflow(id).then((w:Workflow)=>{setName(w.name);setDescription(w.description||"");setMode(w.mode);setResourceType(w.resourceType);const t=w.steps.find(s=>s.kind==="TRIGGER")?.config.value;setTrigger(typeof t==="string"?t:"upload");const c=w.steps.find(s=>s.kind==="CONDITION")?.config.value;setCondition(typeof c==="string"?c:"any");const a=w.steps.find(s=>s.kind==="ACTIONS")?.config.value;if(Array.isArray(a))setActions(a as Array<{type:string;config:Record<string,unknown>}>);if(w.states.length)setStates(w.states.map(s=>({name:s.name,description:s.description||"",terminal:s.terminal})));}).finally(()=>setLoading(false));},[id]);
 const save=async(status:"DRAFT"|"ACTIVE")=>{if(!name.trim()||busy)return;setBusy(true);setSaved(false);try{const payload={name:name.trim(),description,mode,resourceType,trigger,condition,actions,status,states,transitions:[{from:0,to:Math.min(1,states.length-1),name:"Continue",actions}]};if(id)await updateWorkflow(id,payload);else await createWorkflow(payload);setSaved(true);}finally{setBusy(false)}};
 const addState=()=>setStates(s=>[...s,{name:`State ${s.length+1}`,description:"",terminal:false}]); const removeState=(i:number)=>{if(states.length<=2)return;setStates(s=>s.filter((_,idx)=>idx!==i));};
 if(loading)return <ZohoWorkdriveLayout><div className="p-6">Loading…</div></ZohoWorkdriveLayout>;
 return <ZohoWorkdriveLayout><div className="flex min-h-0 flex-1"><SecondarySidebar section="workflows"/><main className="min-w-0 flex-1 overflow-y-auto bg-white"><div className="flex items-center justify-between border-b border-slate-200 px-5 py-4"><div><p className="text-[11px] uppercase tracking-wide text-slate-500">{label("workflows.builder")}</p><h1 className="text-[18px] font-semibold">{id?label("workflows.editTitle"):label("workflows.newTitle")}</h1></div><Link href="/files/workflows" className="rounded-lg border border-slate-200 px-3 py-2 text-[12px]">{label("workflows.back")}</Link></div><div className="grid gap-5 p-5 xl:grid-cols-[1fr_1.2fr]"><section className="space-y-4"><div className="rounded-xl border border-slate-200 p-4"><h2 className="text-[14px] font-semibold">{label("workflows.basics")}</h2><div className="mt-3 space-y-3"><label className="block text-[12px]">{label("workflows.name")}<input value={name} onChange={e=>setName(e.target.value)} className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-[13px]"/></label><label className="block text-[12px]">{label("workflows.description")}<textarea value={description} onChange={e=>setDescription(e.target.value)} className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-[13px]" rows={3}/></label><div className="grid grid-cols-2 gap-3"><label className="text-[12px]">{label("workflows.mode")}<select value={mode} onChange={e=>setMode(e.target.value as "AUTOMATIC"|"MANUAL")} className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-[13px]"><option value="AUTOMATIC">Automatic</option><option value="MANUAL">Manual</option></select></label><label className="text-[12px]">{label("workflows.resourceType")}<select value={resourceType} onChange={e=>setResourceType(e.target.value as "FILE"|"FOLDER")} className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-[13px]"><option value="FILE">File</option><option value="FOLDER">Folder</option></select></label></div></div></div>
 <div className="rounded-xl border border-slate-200 p-4"><h2 className="text-[14px] font-semibold">{label("workflows.triggerAndCondition")}</h2><div className="mt-3 space-y-3"><label className="block text-[12px]">{label("workflows.trigger")}<select value={trigger} disabled={mode==="MANUAL"} onChange={e=>setTrigger(e.target.value)} className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-[13px]"><option value="upload">File uploaded</option><option value="create">File/folder created</option><option value="move">Moved</option><option value="copy">Copied</option><option value="rename">Renamed</option><option value="properties_updated">Properties updated</option><option value="ready">Marked ready</option></select></label><label className="block text-[12px]">{label("workflows.condition")}<select value={condition} onChange={e=>setCondition(e.target.value)} className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2 text-[13px]"><option value="any">Any</option><option value="PDF">PDF</option><option value="IMAGE">Image</option></select></label></div></div>
 <div className="rounded-xl border border-slate-200 p-4"><div className="flex items-center justify-between"><h2 className="text-[14px] font-semibold">{label("workflows.actions")}</h2><button onClick={()=>setActions(a=>[...a,{type:"notify",config:{}}])} className="rounded-lg border border-slate-200 px-2 py-1 text-[11px]">+ {label("workflows.addAction")}</button></div><div className="mt-3 space-y-2">{actions.map((a,i)=><div key={i} className="grid grid-cols-[1fr_auto] gap-2"><select value={a.type} onChange={e=>setActions(all=>all.map((x,n)=>n===i?{...x,type:e.target.value}:x))} className="rounded-lg border border-slate-200 px-3 py-2 text-[12px]"><option value="notify">Notify</option><option value="favorite" disabled={resourceType==="FOLDER"}>Favorite</option><option value="tag" disabled={resourceType==="FOLDER"}>Add tag</option><option value="archive" disabled={resourceType==="FOLDER"}>Mark final / archive</option><option value="move" disabled={resourceType==="FOLDER"}>Move</option><option value="copy" disabled={resourceType==="FOLDER"}>Copy</option><option value="share" disabled={resourceType==="FOLDER"}>Share</option><option value="request_approval">Request approval</option></select>{["move","copy"].includes(a.type)&&<input value={String(a.config.destinationFolderId||"")} onChange={e=>setActions(all=>all.map((x,n)=>n===i?{...x,config:{...x.config,destinationFolderId:e.target.value}}:x))} placeholder="Destination folder ID" className="rounded-lg border border-slate-200 px-2 py-1.5 text-[12px]"/>}{a.type==="tag"&&<input value={String(a.config.name||"")} onChange={e=>setActions(all=>all.map((x,n)=>n===i?{...x,config:{...x.config,name:e.target.value}}:x))} placeholder="Tag name" className="rounded-lg border border-slate-200 px-2 py-1.5 text-[12px]"/>}{a.type==="share"&&<input value={String(a.config.userIds||"")} onChange={e=>setActions(all=>all.map((x,n)=>n===i?{...x,config:{...x.config,userIds:e.target.value.split(",").map(v=>v.trim()).filter(Boolean)}}:x))} placeholder="Recipient user IDs, comma separated" className="rounded-lg border border-slate-200 px-2 py-1.5 text-[12px]"/>}<button onClick={()=>setActions(all=>all.filter((_,n)=>n!==i))} className="rounded-lg border border-slate-200 px-2 text-red-600">×</button></div>)}</div><p className="mt-2 text-[11px] text-slate-500">{label("workflows.actionLimit")}</p></div></section>
 <section className="rounded-xl border border-slate-200 p-4"><div className="flex items-center justify-between"><div><h2 className="text-[14px] font-semibold">{label("workflows.states")}</h2><p className="mt-1 text-[11.5px] text-slate-500">{label("workflows.statesHelp")}</p></div><button onClick={addState} className="rounded-lg border border-slate-200 px-2 py-1 text-[11px]">+ {label("workflows.addState")}</button></div><div className="mt-4 space-y-3">{states.map((s,i)=><div key={i} className="rounded-xl border border-slate-200 p-3"><div className="flex items-center gap-2"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-slate-100 text-[11px]">{i+1}</span><input value={s.name} onChange={e=>setStates(all=>all.map((x,n)=>n===i?{...x,name:e.target.value}:x))} className="min-w-0 flex-1 rounded-lg border border-slate-200 px-2 py-1.5 text-[12px]"/><label className="text-[11px]"><input type="checkbox" checked={s.terminal} onChange={e=>setStates(all=>all.map((x,n)=>n===i?{...x,terminal:e.target.checked}:x))}/> {label("workflows.terminal")}</label>{states.length>2&&<button onClick={()=>removeState(i)} className="text-red-600">×</button>}</div><textarea value={s.description} onChange={e=>setStates(all=>all.map((x,n)=>n===i?{...x,description:e.target.value}:x))} className="mt-2 w-full rounded-lg border border-slate-200 px-2 py-1.5 text-[12px]" placeholder={label("workflows.stateDescription")} rows={2}/>{i<states.length-1&&<div className="mt-2 rounded-lg bg-slate-50 p-2 text-[11px] text-slate-500">{label("workflows.transitionDefault")} → {states[i+1].name}</div>}</div>)}</div><div className="mt-5 flex flex-wrap justify-end gap-2 border-t border-slate-100 pt-4"><Link href="/files/workflows" className="rounded-lg border border-slate-200 px-3 py-2 text-[12px]">{label("workflows.cancel")}</Link><button disabled={busy} onClick={()=>void save("DRAFT")} className="rounded-lg border border-slate-200 px-3 py-2 text-[12px]">{label("workflows.saveDraft")}</button><button disabled={busy} onClick={()=>void save("ACTIVE")} className="rounded-lg bg-[var(--wd-primary)] px-3 py-2 text-[12px] font-medium text-white">{label("workflows.activate")}</button>{saved&&<span className="self-center text-[11px] text-green-700">{label("workflows.saved")}</span>}</div></section></div></main></div></ZohoWorkdriveLayout>;
}
