"use client";
import { useCallback, useEffect, useState } from "react";
import { useLocale } from "../../../components/locale-provider";
import { AlertBanner } from "../../../components/alert-banner";
import { EmptyState } from "../../../components/empty-state";
import { SkeletonLoader } from "../../../components/skeleton-loader";
import { listCollaborationActivity, type CollaborationActivity } from "../../../lib/api/notifications";
import { formatDateLocalized } from "../../../lib/localized";

function initials(name?: string|null,email?: string){return (name||email||"U").split(/\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase();}
function actionText(action:string, ar:boolean){const m:Record<string,string>=ar?{CREATE:"أنشأ ملفًا",UPDATE:"حدّث ملفًا",DELETE:"حذف ملفًا",RESTORE:"استعاد ملفًا",MOVE:"نقل ملفًا",COPY:"نسخ ملفًا",DOWNLOAD:"نزّل ملفًا",PREVIEW:"عاين ملفًا",SHARE:"شارك ملفًا",UNSHARE:"أوقف مشاركة ملف",COMMENT:"علّق على ملف",UPLOAD_VERSION:"رفع إصدارًا جديدًا",RESTORE_VERSION:"استعاد إصدارًا",CHANGE_PERMISSION:"غيّر صلاحية ملف"}:{CREATE:"created a file",UPDATE:"updated a file",DELETE:"deleted a file",RESTORE:"restored a file",MOVE:"moved a file",COPY:"copied a file",DOWNLOAD:"downloaded a file",PREVIEW:"previewed a file",SHARE:"shared a file",UNSHARE:"stopped sharing a file",COMMENT:"commented on a file",UPLOAD_VERSION:"uploaded a new version",RESTORE_VERSION:"restored a version",CHANGE_PERMISSION:"changed file permission"}; return m[action]||action;}
export default function ActivityPage(){const{locale}=useLocale();const ar=locale==='ar';const[rows,setRows]=useState<CollaborationActivity[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const load=useCallback(async()=>{setLoading(true);setError('');try{setRows(await listCollaborationActivity(75));}catch{setError(ar?'تعذر تحميل مركز التعاون.':'Unable to load Collaboration Center.')}finally{setLoading(false)}},[ar]);useEffect(()=>{void load()},[load]);return <section className="wd-page" dir={ar?'rtl':'ltr'}><div className="wd-page-head"><div className="wd-page-head-titles"><h1>{ar?'مركز التعاون':'Collaboration Center'}</h1><p>{ar?'نشاط الملفات والتعليقات والمشاركة التي يمكنك الوصول إليها.':'File activity, comments and sharing events across resources you can access.'}</p></div><div className="wd-page-head-actions"><button className="wd-btn wd-btn-ghost" onClick={()=>void load()}>{ar?'تحديث':'Refresh'}</button></div></div>{error?<AlertBanner message={error}/>:null}{loading?<SkeletonLoader rows={6} columns={3}/>:rows.length===0?<EmptyState title={ar?'لا توجد أنشطة بعد':'No collaboration activity yet'}/>:<div className="wd-card overflow-hidden"><div className="divide-y divide-slate-100">{rows.map(r=><article key={r.id} className="flex items-center gap-3 px-5 py-4 hover:bg-slate-50"><div className="wd-avatar shrink-0">{initials(r.actor?.name,r.actor?.email)}</div><div className="min-w-0 flex-1"><div className="text-[11px] text-slate-700"><strong>{r.actor?.name||r.actor?.email|| (ar?'مستخدم':'User')}</strong>{' '}{actionText(r.action,ar)}{' '}<span className="font-semibold text-slate-900">{r.file.name}</span></div><div className="mt-1 text-[9.5px] text-slate-400">{formatDateLocalized(r.createdAt,locale)}</div></div><a href={`/files/${r.file.id}`} className="wd-btn wd-btn-ghost shrink-0">{ar?'فتح':'Open'}</a></article>)}</div></div>}</section>}
