"use client";
import { useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import { ZohoWorkdriveLayout } from "@/components/layout/zoho-workdrive-layout";
import { SecondarySidebar } from "@/components/layout/secondary-sidebar";
import { useLocale } from "@/components/locale-provider";
import { Icons } from "@/components/layout/icons";
import { openWip } from "@/components/wip-modal";
type Category="documents"|"spreadsheets"|"presentations";
type Template={id:string;name:string;category:Category;description:string;icon:keyof typeof Icons};
const templates:Template[]=[
{id:"blank-doc",name:"Blank document",category:"documents",description:"Start with a clean document.",icon:"doc"},
{id:"project-plan",name:"Project plan",category:"documents",description:"Plan goals, milestones, owners and dates.",icon:"doc"},
{id:"budget",name:"Budget tracker",category:"spreadsheets",description:"Track planned and actual project costs.",icon:"sheet"},
{id:"weekly-report",name:"Weekly report",category:"spreadsheets",description:"Summarize weekly progress and metrics.",icon:"sheet"},
{id:"pitch",name:"Project presentation",category:"presentations",description:"Present a project clearly to stakeholders.",icon:"slide"}];
export default function TemplatesPage(){const{label}=useLocale();const params=useSearchParams();const category=params.get("category");const[q,setQ]=useState("");const filtered=useMemo(()=>templates.filter(t=>(!category||category==="my"||t.category===category)&&`${t.name} ${t.description}`.toLowerCase().includes(q.toLowerCase())),[category,q]);return <ZohoWorkdriveLayout><div className="flex min-h-0 flex-1"><SecondarySidebar section="templates"/><main className="min-w-0 flex-1 overflow-y-auto bg-white"><div className="border-b border-[color:var(--imkan-color-border)] px-5 py-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-[18px] font-semibold text-slate-900">{label("templates.title")}</h1><p className="mt-1 text-[12.5px] text-slate-500">{label("templates.description")}</p></div><button type="button" onClick={()=>openWip(label("templates.comingSoon"))} className="rounded-lg border border-slate-200 px-3 py-2 text-[12.5px] font-medium text-slate-700 hover:bg-slate-50">+ {label("templates.comingSoon")}</button></div><div className="mt-4 flex max-w-xl items-center gap-2 rounded-lg border border-slate-200 px-3 py-2"><Icons.search size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={label("templates.search")} className="min-w-0 flex-1 text-[13px] outline-none"/></div></div>{filtered.length===0?<div className="p-6"><div className="wd-empty"><span className="wd-empty-icon"><Icons.layout size={24}/></span><h2>{label("templates.empty")}</h2><p>{label("templates.description")}</p></div></div>:<div className="grid grid-cols-[repeat(auto-fill,minmax(230px,1fr))] gap-4 p-5">{filtered.map(t=>{const I=Icons[t.icon];return <article key={t.id} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm hover:border-slate-300"><div className="flex h-28 items-center justify-center rounded-lg bg-slate-50 text-[var(--wd-primary)]"><I size={42}/></div><h2 className="mt-3 truncate text-[14px] font-semibold text-slate-900">{t.name}</h2><p className="mt-1 min-h-10 text-[12px] leading-5 text-slate-500">{t.description}</p><div className="mt-3 flex gap-2"><button type="button" onClick={()=>openWip(t.name)} className="flex-1 rounded-lg bg-[var(--wd-primary)] px-3 py-2 text-[12px] font-medium text-white">{label("templates.use")}</button><button type="button" onClick={()=>openWip(t.name)} className="rounded-lg border border-slate-200 px-3 py-2 text-[12px] text-slate-600">{label("templates.preview")}</button></div></article>})}</div>}</main></div></ZohoWorkdriveLayout>}
