CREATE TABLE `connection_provider_configs` (
  `id` CHAR(36) NOT NULL,
  `org_id` CHAR(36) NOT NULL,
  `provider_key` VARCHAR(100) NOT NULL,
  `enabled` BOOLEAN NOT NULL DEFAULT true,
  `client_id` TEXT NULL,
  `client_secret` TEXT NULL,
  `tenant_id` VARCHAR(200) NULL,
  `callback_url` VARCHAR(2000) NULL,
  `auth_url` VARCHAR(2000) NULL,
  `token_url` VARCHAR(2000) NULL,
  `revoke_url` VARCHAR(2000) NULL,
  `scopes` JSON NULL,
  `last_tested_at` DATETIME(3) NULL,
  `last_test_ok` BOOLEAN NULL,
  `last_test_message` TEXT NULL,
  `created_by_id` CHAR(36) NULL,
  `updated_by_id` CHAR(36) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  UNIQUE INDEX `connection_provider_configs_org_id_provider_key_key` (`org_id`, `provider_key`),
  INDEX `connection_provider_configs_org_id_enabled_idx` (`org_id`, `enabled`),
  CONSTRAINT `connection_provider_configs_org_id_fkey` FOREIGN KEY (`org_id`) REFERENCES `organizations` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `connection_provider_configs_created_by_id_fkey` FOREIGN KEY (`created_by_id`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `connection_provider_configs_updated_by_id_fkey` FOREIGN KEY (`updated_by_id`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
