"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { SecondarySidebar } from "@/components/layout/secondary-sidebar";
import { useLocale } from "@/components/locale-provider";
import { createWorkflow, getWorkflow, updateWorkflow, type Workflow } from "@/lib/api/workflows";

const BLUE = "#1B66EA";
type Action = { type: string; config: Record<string, unknown> };
type StateDraft = { name: string; description: string; terminal: boolean };
type NodePosition = { x: number; y: number };
type TransitionDraft = { from: number; to: number; name: string; description?: string; trigger?: string; condition?: unknown; actions: Action[] };
type FieldDraft = { id: string; name: string; type: string; required: boolean; options?: string[] };
const TRIGGERS = [["upload","File uploaded"],["create","File/folder created"],["move","File/folder moved"],["copy","File/folder copied"],["rename","File renamed"],["delete","File moved to trash"],["properties_updated","Properties updated"],["ready","File marked as ready"]] as const;
const ACTIONS = [["notify","Send notification"],["move","Move"],["copy","Copy"],["generate_link","Generate link"],["share","Share"],["request_approval","Request approval"],["favorite","Add to favorites"],["tag","Add tag"],["mark_final","Mark as final"],["create_folder","Create folder"]] as const;
const ACTION_ICONS: Record<string,string> = { notify:"◌",move:"↗",copy:"□",generate_link:"⌁",share:"⌯",request_approval:"✓",favorite:"☆",tag:"#",mark_final:"◆",create_folder:"＋" };
function cx(...v:(string|false|undefined)[]){return v.filter(Boolean).join(" ")}
function uid(){return Math.random().toString(36).slice(2,9)}
function actionLabel(type:string){return ACTIONS.find(x=>x[0]===type)?.[1]||type}

export default function WorkflowBuilderPage(){
 const {label}=useLocale(); const router=useRouter(); const params=useSearchParams(); const urlId=params.get("id");
 const [workflowId,setWorkflowId]=useState<string|null>(urlId); const [name,setName]=useState(""); const [description,setDescription]=useState("");
 const [mode,setMode]=useState<"AUTOMATIC"|"MANUAL">("AUTOMATIC"); const [resourceType,setResourceType]=useState<"FILE"|"FOLDER">("FILE");
 const [triggers,setTriggers]=useState<string[]>(["upload"]); const [condition,setCondition]=useState("any"); const [extension,setExtension]=useState(""); const [nameContains,setNameContains]=useState("");
 const [actions,setActions]=useState<Action[]>([{type:"notify",config:{}}]);
 const [states,setStates]=useState<StateDraft[]>([{name:"Start",description:"Workflow entry point",terminal:false},{name:"Completed",description:"",terminal:true}]);
 const [transitions,setTransitions]=useState<TransitionDraft[]>([{from:0,to:1,name:"Complete",actions:[{type:"notify",config:{}}]}]);
 const [selected,setSelected]=useState("trigger"); const [tab,setTab]=useState<"design"|"fields"|"review">("design"); const [loading,setLoading]=useState(Boolean(urlId)); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState("");
 const [fields,setFields]=useState<FieldDraft[]>([]);
 const [positions,setPositions]=useState<NodePosition[]>([{x:340,y:360},{x:340,y:560}]);
 const [zoom,setZoom]=useState(1);
 useEffect(()=>{if(!workflowId)return;try{const raw=localStorage.getItem(`imkan-workflow-layout:${workflowId}`);if(raw){const parsed=JSON.parse(raw);if(Array.isArray(parsed))setPositions(parsed)}}catch{}},[workflowId]);
 useEffect(()=>{if(!workflowId)return;try{localStorage.setItem(`imkan-workflow-layout:${workflowId}`,JSON.stringify(positions))}catch{}},[workflowId,positions]);
 useEffect(()=>{if(!urlId)return; void getWorkflow(urlId).then((w:Workflow)=>{
   setName(w.name); setDescription(w.description||""); setMode(w.mode); setResourceType(w.resourceType);
   const tv=w.steps.find(s=>s.kind==="TRIGGER")?.config.value; setTriggers(Array.isArray(tv)?tv.map(String):[String(tv||"upload")]);
   const cv=w.steps.find(s=>s.kind==="CONDITION")?.config.value;
   if(typeof cv==="string") setCondition(cv); else if(cv&&typeof cv==="object"){const c=cv as Record<string,unknown>; if(typeof c.extension==="string")setExtension(c.extension); if(typeof c.nameContains==="string")setNameContains(c.nameContains);}
   const av=w.steps.find(s=>s.kind==="ACTIONS")?.config.value; if(Array.isArray(av))setActions(av as Action[]);
   const fv=w.steps.find(s=>s.kind==="WORKFLOW_FIELDS")?.config.value; if(Array.isArray(fv))setFields(fv as FieldDraft[]);
   if(w.states.length){setStates(w.states.map(s=>({name:s.name,description:s.description||"",terminal:s.terminal}))); setPositions(prev=>w.states.map((_,i)=>prev[i]||{x:340,y:360+i*190}));}
   if(w.transitions.length)setTransitions(w.transitions.map(t=>({from:w.states.findIndex(s=>s.id===t.fromStateId),to:w.states.findIndex(s=>s.id===t.toStateId),name:t.name,description:t.description||"",trigger:t.trigger||undefined,condition:t.condition||undefined,actions:(t.actions||[]).map(a=>({type:a.type,config:a.config??{}}))})));
 }).catch(()=>setError(label("error.generic"))).finally(()=>setLoading(false));},[urlId,label]);
 const conditionValue=useMemo(()=>{const list:any[]=[]; if(condition!=="any")list.push(condition); if(extension.trim())list.push({extension:extension.trim().replace(/^\./,"")}); if(nameContains.trim())list.push({nameContains:nameContains.trim()}); return list.length>1?{all:list}:list.length===1?list[0]:"any";},[condition,extension,nameContains]);
 const save=async(status:"DRAFT"|"ACTIVE")=>{if(busy)return;if(!name.trim()){setError(label("workflows.nameRequired"));return}if(!states.length||!states.some(s=>s.terminal)){setError("Add at least one final state.");return}if(transitions.some(t=>t.from<0||t.to<0||t.from>=states.length||t.to>=states.length)){setError("Fix invalid transitions before saving.");return}setBusy(true);setError("");setMessage("");try{const payload={name:name.trim(),description,mode,resourceType,trigger:mode==="MANUAL"?"manual":triggers,condition:conditionValue,actions,status,states,transitions,fields};const saved=workflowId?await updateWorkflow(workflowId,payload):await createWorkflow(payload);setWorkflowId(saved.id);setMessage(status==="ACTIVE"?"Workflow activated":"Draft saved");if(status==="ACTIVE")window.setTimeout(()=>router.push("/files/workflows"),500);}catch(e){setError(e instanceof Error?e.message:label("error.generic"));}finally{setBusy(false)}};
 const addState=()=>{if(states.length>=20)return;const i=states.length;const next={name:`State ${i+1}`,description:"",terminal:false};setStates(v=>[...v,next]);setPositions(v=>[...v,{x:340,y:360+i*190}]);setSelected(`state-${i}`)};
 const removeState=(i:number)=>{if(states.length<=1)return;setStates(v=>v.filter((_,idx)=>idx!==i));setPositions(v=>v.filter((_,idx)=>idx!==i));setTransitions(v=>v.filter(t=>t.from!==i&&t.to!==i).map(t=>({...t,from:t.from>i?t.from-1:t.from,to:t.to>i?t.to-1:t.to})));setSelected("trigger")};
 const moveState=(i:number,pos:NodePosition)=>setPositions(v=>v.map((p,j)=>j===i?pos:p));
 const addTransition=(from:number,to:number)=>{const idx=transitions.length;setTransitions(v=>[...v,{from,to,name:"New transition",description:"",actions:[]}]);setSelected(`transition-${idx}`)};
 const updateState=(i:number,key:keyof StateDraft,value:unknown)=>setStates(v=>v.map((x,idx)=>idx===i?{...x,[key]:value}:x));
 const selectedTransition=selected.startsWith("transition-")?Number(selected.split("-")[1]):-1; const selectedState=selected.startsWith("state-")?Number(selected.split("-")[1]):-1;
 const updateTransition=(i:number,key:string,value:unknown)=>setTransitions(v=>v.map((x,idx)=>idx===i?{...x,[key]:value}:x));
 const addAction=(type:string,target:"global"|number="global")=>{const action={type,config:{}};if(target==="global")setActions(v=>v.length<5?[...v,action]:v);else setTransitions(v=>v.map((t,i)=>i===target&&t.actions.length<5?{...t,actions:[...t.actions,action]}:t))};
 const updateAction=(target:"global"|number,index:number,key:string,value:unknown)=>{const fn=(arr:Action[])=>arr.map((a,i)=>i===index?{...a,config:{...a.config,[key]:value}}:a);if(target==="global")setActions(fn);else setTransitions(v=>v.map((t,i)=>i===target?{...t,actions:fn(t.actions)}:t));};
 const removeAction=(target:"global"|number,index:number)=>{if(target==="global")setActions(v=>v.filter((_,i)=>i!==index));else setTransitions(v=>v.map((t,i)=>i===target?{...t,actions:t.actions.filter((_,x)=>x!==index)}:t));};
 const addField=()=>setFields(v=>[...v,{id:uid(),name:`Field ${v.length+1}`,type:"Text",required:false}]);
 const exportSpec=()=>{const spec={version:2,name,description,mode,resourceType,trigger:triggers,condition:conditionValue,actions,states,transitions,fields};const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(spec,null,2)],{type:"application/json"}));a.download=`${name||"workflow"}.json`;a.click();URL.revokeObjectURL(a.href)};
 if(loading)return <div className="flex min-h-0 flex-1"><SecondarySidebar section="workflows"/><main className="flex-1 p-8 text-sm text-slate-500">{label("common.loading")}</main></div>;
 return <div className="flex min-h-0 flex-1 bg-[#f5f7fa]"><SecondarySidebar section="workflows"/><main className="min-w-0 flex-1 overflow-hidden">
  <header className="border-b border-slate-200 bg-white">
   <div className="flex min-h-[64px] items-center justify-between gap-4 px-5"><div className="flex min-w-0 items-center gap-3"><Link href="/files/workflows" className="rounded-lg p-2 text-slate-500 hover:bg-slate-100">←</Link><div className="min-w-0"><div className="flex items-center gap-2"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Untitled workflow" className="w-[min(440px,48vw)] bg-transparent text-[15px] font-semibold text-slate-900 outline-none placeholder:text-slate-400"/><span className={cx("rounded-full px-2 py-1 text-[9px] font-semibold",workflowId?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-500")}>{workflowId?"SAVED":"DRAFT"}</span></div><div className="mt-0.5 text-[10.5px] text-slate-400">{resourceType === "FILE" ? "Files" : "Folders"} · {mode === "AUTOMATIC" ? "Automatic" : "Manual"} · {states.length} states</div></div></div><div className="flex items-center gap-2"><button onClick={exportSpec} className="hidden rounded-lg border border-slate-200 px-3 py-2 text-[11px] text-slate-600 hover:bg-slate-50 md:inline-flex">Export</button><button disabled={busy} onClick={()=>void save("DRAFT")} className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-[11px] font-medium text-slate-700">Save draft</button><button disabled={busy} onClick={()=>void save("ACTIVE")} className="rounded-lg bg-[#1B66EA] px-4 py-2 text-[11px] font-semibold text-white shadow-sm">{busy?"Saving…":"Enable workflow"}</button></div></div>
   <nav className="flex gap-6 px-6">{([['design','Design workflow'],['fields','Workflow fields'],['review','Review']] as const).map(([v,t])=><button key={v} onClick={()=>setTab(v)} className={cx("relative py-3 text-[11.5px] font-medium",tab===v?"text-[#1B66EA]":"text-slate-500 hover:text-slate-800")}>{t}{tab===v&&<span className="absolute inset-x-0 bottom-0 h-0.5 bg-[#1B66EA]"/>}</button>)}</nav>
  </header>
  {(error||message)&&<div className={cx("mx-5 mt-3 rounded-lg border px-3 py-2 text-[11px]",error?"border-red-200 bg-red-50 text-red-700":"border-emerald-200 bg-emerald-50 text-emerald-700")}>{error||message}</div>}
  {tab==="fields"?<FieldsTab fields={fields} setFields={setFields} addField={addField}/>:tab==="review"?<ReviewTab name={name} mode={mode} resourceType={resourceType} triggers={triggers} states={states} transitions={transitions} actions={actions} fields={fields} onBack={()=>setTab("design")} onEnable={()=>void save("ACTIVE")}/>:<div className="grid h-[calc(100vh-132px)] min-h-[650px] grid-cols-[205px_minmax(520px,1fr)_330px]">
   <aside className="overflow-y-auto border-e border-slate-200 bg-[#fbfcfe] p-3"><div className="px-2 pb-2 text-[9.5px] font-bold uppercase tracking-wider text-slate-400">Workflow elements</div><div className="space-y-1"><PaletteItem icon="⚡" title="Trigger" subtitle="Starts the workflow" onClick={()=>setSelected("trigger")}/><PaletteItem icon="◇" title="Condition" subtitle="Controls eligibility" onClick={()=>setSelected("condition")}/><PaletteItem icon="●" title="State" subtitle="A stage in the flow" onClick={addState}/><PaletteItem icon="→" title="Transition" subtitle="Moves between states" onClick={()=>states.length>1&&addTransition(0,1)}/></div><div className="mt-5 border-t border-slate-200 pt-4"><div className="px-2 pb-2 text-[9.5px] font-bold uppercase tracking-wider text-slate-400">Actions</div><div className="space-y-1">{ACTIONS.map(([v,l])=><button key={v} onClick={()=>addAction(v)} className="flex w-full items-center gap-2 rounded-lg px-2.5 py-2 text-start text-[10px] text-slate-600 hover:bg-white hover:shadow-sm"><span className="flex h-6 w-6 items-center justify-center rounded-md bg-white text-slate-400 shadow-sm">{ACTION_ICONS[v]}</span><span>{l}</span></button>)}</div></div></aside>
   <section className="relative overflow-auto bg-[#f7f9fc] p-7"><div className="mb-4 flex items-center justify-between"><div><div className="text-[10px] font-semibold uppercase tracking-[.13em] text-slate-400">Visual workflow</div><div className="mt-1 text-[11px] text-slate-500">Select an element to configure it. Add multiple transitions from the same state to create branches.</div></div><div className="flex items-center gap-1 rounded-lg border border-slate-200 bg-white p-1 text-[10px]"><button onClick={()=>{setZoom(1);document.getElementById("workflow-canvas")?.scrollTo({top:0,left:0,behavior:"smooth"})}} className="rounded px-2 py-1 text-slate-500 hover:bg-slate-50">Fit</button><span className="px-1 text-slate-300">100%</span></div></div><WorkflowCanvas states={states} transitions={transitions} selected={selected} setSelected={setSelected} addTransition={addTransition} removeState={removeState} positions={positions} moveState={moveState} zoom={zoom} setZoom={setZoom}/></section>
   <Inspector selected={selected} mode={mode} setMode={setMode} resourceType={resourceType} setResourceType={setResourceType} triggers={triggers} setTriggers={setTriggers} condition={condition} setCondition={setCondition} extension={extension} setExtension={setExtension} nameContains={nameContains} setNameContains={setNameContains} states={states} selectedState={selectedState} updateState={updateState} removeState={removeState} transitions={transitions} selectedTransition={selectedTransition} updateTransition={updateTransition} actions={actions} addAction={addAction} updateAction={updateAction} removeAction={removeAction} fields={fields} setTab={setTab}/>
  </div>}
 </main></div>
}

function PaletteItem({icon,title,subtitle,onClick}:{icon:string;title:string;subtitle:string;onClick:()=>void}){return <button onClick={onClick} className="flex w-full items-center gap-2 rounded-lg border border-transparent px-2 py-2.5 text-start hover:border-slate-200 hover:bg-white"><span className="flex h-7 w-7 items-center justify-center rounded-md border border-slate-200 bg-white text-[12px] text-slate-500">{icon}</span><span><span className="block text-[10.5px] font-semibold text-slate-700">{title}</span><span className="block text-[9px] text-slate-400">{subtitle}</span></span></button>}

function WorkflowCanvas({states,transitions,selected,setSelected,addTransition,removeState,positions,moveState,zoom,setZoom}:{states:StateDraft[];transitions:TransitionDraft[];selected:string;setSelected:(s:string)=>void;addTransition:(f:number,t:number)=>void;removeState:(i:number)=>void;positions:NodePosition[];moveState:(i:number,p:NodePosition)=>void;zoom:number;setZoom:(v:number)=>void}){
 const canvasW=900, canvasH=Math.max(850, ...positions.map(p=>p.y+150));
 const cardW=250, cardH=92;
 const point=(i:number,side:"top"|"bottom")=>{const p=positions[i]||{x:340,y:360};return {x:p.x+cardW/2,y:p.y+(side==="bottom"?cardH:0)}};
 const onDrag=(e:React.PointerEvent,i:number)=>{const target=e.currentTarget as HTMLElement;target.setPointerCapture(e.pointerId);const sx=e.clientX,sy=e.clientY,base=positions[i]||{x:340,y:360};const move=(ev:PointerEvent)=>{moveState(i,{x:Math.max(24,Math.min(canvasW-cardW-24,base.x+(ev.clientX-sx)/zoom)),y:Math.max(220,base.y+(ev.clientY-sy)/zoom)})};const up=()=>{window.removeEventListener("pointermove",move);window.removeEventListener("pointerup",up)};window.addEventListener("pointermove",move);window.addEventListener("pointerup",up)};
 return <div className="relative overflow-hidden rounded-xl border border-slate-200 bg-white shadow-[0_1px_3px_rgba(15,23,42,.04)]">
  <div className="absolute right-3 top-3 z-30 flex items-center gap-1 rounded-lg border border-slate-200 bg-white/95 p-1 shadow-sm"><button onClick={()=>setZoom(Math.max(.65,+(zoom-.1).toFixed(2)))} className="h-7 w-7 rounded text-slate-500 hover:bg-slate-100">−</button><span className="w-12 text-center text-[9px] text-slate-500">{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(Math.min(1.35,+(zoom+.1).toFixed(2)))} className="h-7 w-7 rounded text-slate-500 hover:bg-slate-100">+</button><button onClick={()=>setZoom(1)} className="rounded px-2 text-[9px] text-slate-500 hover:bg-slate-100">Reset</button></div>
  <div className="h-[calc(100vh-245px)] min-h-[610px] overflow-auto" id="workflow-canvas"><div className="relative" style={{width:canvasW*zoom,height:canvasH*zoom,backgroundImage:"radial-gradient(#dbe2ea 1px, transparent 1px)",backgroundSize:`${18*zoom}px ${18*zoom}px`}}><div style={{width:canvasW,height:canvasH,transform:`scale(${zoom})`,transformOrigin:"top left"}} className="relative">
   <div className="absolute left-1/2 top-6 z-10 w-[250px] -translate-x-1/2"><button onClick={()=>setSelected("trigger")} className={cx("w-full rounded-xl border bg-white p-3 text-start shadow-sm",selected==="trigger"?"border-blue-300 ring-2 ring-blue-50":"border-slate-200")}><div className="flex items-center gap-2"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-blue-50 text-[#1B66EA]">⚡</span><span><span className="block text-[9px] font-bold uppercase tracking-wider text-slate-400">Trigger</span><span className="block text-[12px] font-semibold text-slate-800">Workflow trigger</span></span></div><div className="mt-2 text-[9.5px] text-slate-500">Starts the workflow</div></button></div>
   <div className="absolute left-1/2 top-[126px] h-[55px] w-px -translate-x-1/2 bg-slate-300"/><button onClick={()=>setSelected("condition")} className={cx("absolute left-1/2 top-[182px] z-10 w-[250px] -translate-x-1/2 rounded-xl border bg-white p-3 text-start shadow-sm",selected==="condition"?"border-blue-300 ring-2 ring-blue-50":"border-slate-200")}><div className="flex items-center gap-2"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-amber-50 text-amber-600">◇</span><span><span className="block text-[9px] font-bold uppercase tracking-wider text-slate-400">Condition</span><span className="block text-[12px] font-semibold text-slate-800">Eligibility</span></span></div><div className="mt-2 text-[9.5px] text-slate-500">Controls whether the workflow continues</div></button>
   <svg className="pointer-events-none absolute inset-0 z-[5]" width={canvasW} height={canvasH}>{transitions.map((t,idx)=>{const a=point(t.from,"bottom"),b=point(t.to,"top");const mid=(a.y+b.y)/2;return <g key={idx}><path d={`M ${a.x} ${a.y} C ${a.x} ${mid}, ${b.x} ${mid}, ${b.x} ${b.y}`} fill="none" stroke={selected===`transition-${idx}`?"#1B66EA":"#cbd5e1"} strokeWidth={selected===`transition-${idx}`?2.5:1.5}/><polygon points={`${b.x},${b.y} ${b.x-5},${b.y-8} ${b.x+5},${b.y-8}`} fill={selected===`transition-${idx}`?"#1B66EA":"#94a3b8"}/><foreignObject x={(a.x+b.x)/2-55} y={mid-12} width="110" height="24"><button onClick={()=>setSelected(`transition-${idx}`)} className={cx("pointer-events-auto w-full truncate rounded-full border bg-white px-2 py-1 text-[8px] shadow-sm",selected===`transition-${idx}`?"border-blue-300 text-blue-700":"border-slate-200 text-slate-500")}>{t.name||"Transition"}</button></foreignObject></g>})}</svg>
   {states.map((s,i)=>{const p=positions[i]||{x:340,y:360};return <div key={i} className="absolute z-10 w-[250px]" style={{left:p.x,top:p.y}}><div onPointerDown={e=>onDrag(e,i)} className="cursor-grab active:cursor-grabbing"><button onClick={()=>setSelected(`state-${i}`)} className={cx("w-full rounded-xl border bg-white p-3 text-start shadow-sm",selected===`state-${i}`?"border-blue-300 ring-2 ring-blue-50":"border-slate-200")}><div className="flex items-center gap-2"><span className={cx("flex h-8 w-8 items-center justify-center rounded-lg",s.terminal?"bg-emerald-50 text-emerald-600":"bg-slate-100 text-slate-500")}>{s.terminal?"✓":"●"}</span><span className="min-w-0 flex-1"><span className="block text-[9px] font-bold uppercase tracking-wider text-slate-400">State {i+1}</span><span className="block truncate text-[12px] font-semibold text-slate-800">{s.name||`State ${i+1}`}</span></span>{s.terminal&&<span className="rounded-full bg-emerald-50 px-2 py-1 text-[8px] font-semibold text-emerald-700">Final</span>}</div><div className="mt-2 truncate text-[9.5px] text-slate-500">{s.description||"No description"}</div></button></div><div className="mt-1 flex justify-center gap-1"><button onClick={()=>{const to=i===states.length-1?Math.max(0,i-1):i+1;addTransition(i,to)}} className="rounded-full border border-dashed border-slate-300 bg-white px-2 py-1 text-[8px] text-slate-500">+ Transition</button><button onClick={()=>removeState(i)} className="rounded-full border border-transparent bg-white px-2 py-1 text-[8px] text-slate-400 hover:text-red-500">Remove</button></div></div>})}
   <div className="absolute bottom-4 left-4 z-20 rounded-lg border border-slate-200 bg-white/95 p-2 shadow-sm"><div className="mb-1 text-[8px] font-semibold uppercase tracking-wider text-slate-400">Mini map</div><div className="relative h-20 w-28 rounded bg-slate-50">{states.map((s,i)=>{const p=positions[i]||{x:340,y:360};return <div key={i} className="absolute h-2 w-5 rounded-sm bg-slate-300" style={{left:p.x/8,top:p.y/12}}/>})}</div></div>
  </div></div></div></div>
}
function Inspector(p:any){return <aside className="overflow-y-auto border-s border-slate-200 bg-white"><div className="border-b border-slate-100 px-4 py-4"><div className="text-[9px] font-bold uppercase tracking-[.14em] text-slate-400">Configuration</div><div className="mt-1 text-[14px] font-semibold text-slate-900">{p.selected==="trigger"?"Workflow trigger":p.selected==="condition"?"Workflow condition":p.selectedState>=0?"State":p.selectedTransition>=0?"Transition":"Select an element"}</div></div><div className="space-y-5 p-4">
 {p.selected==="trigger"&&<><Field label="Run mode"><div className="grid grid-cols-2 rounded-lg bg-slate-100 p-1"><button onClick={()=>p.setMode("AUTOMATIC")} className={cx("rounded-md py-2 text-[10px]",p.mode==="AUTOMATIC"?"bg-white font-semibold text-slate-800 shadow-sm":"text-slate-500")}>Automatic</button><button onClick={()=>p.setMode("MANUAL")} className={cx("rounded-md py-2 text-[10px]",p.mode==="MANUAL"?"bg-white font-semibold text-slate-800 shadow-sm":"text-slate-500")}>Manual</button></div></Field><Field label="Resource"><div className="grid grid-cols-2 gap-2"><button onClick={()=>p.setResourceType("FILE")} className={cx("rounded-lg border px-3 py-2 text-[10px]",p.resourceType==="FILE"?"border-blue-200 bg-blue-50 text-blue-700":"border-slate-200 text-slate-500")}>Files</button><button onClick={()=>p.setResourceType("FOLDER")} className={cx("rounded-lg border px-3 py-2 text-[10px]",p.resourceType==="FOLDER"?"border-blue-200 bg-blue-50 text-blue-700":"border-slate-200 text-slate-500")}>Folders</button></div></Field>{p.mode==="AUTOMATIC"&&<Field label="Events"><div className="space-y-1">{TRIGGERS.map(([v,l])=><label key={v} className="flex items-center gap-2 rounded-lg px-2 py-2 hover:bg-slate-50"><input type="checkbox" checked={p.triggers.includes(v)} onChange={e=>p.setTriggers(e.target.checked?[...p.triggers,v]:p.triggers.filter((x:string)=>x!==v))}/><span className="text-[10px] text-slate-600">{l}</span></label>)}</div></Field>}</>}
 {p.selected==="condition"&&<><Field label="File type"><select value={p.condition} onChange={e=>p.setCondition(e.target.value)} className="control"><option value="any">Any type</option><option value="PDF">PDF</option><option value="IMAGE">Image</option><option value="DOCUMENT">Document</option><option value="SPREADSHEET">Spreadsheet</option><option value="PRESENTATION">Presentation</option><option value="VIDEO">Video</option><option value="AUDIO">Audio</option></select></Field><Field label="Extension"><input value={p.extension} onChange={e=>p.setExtension(e.target.value.replace(/^\./,""))} placeholder="e.g. pdf" className="control"/></Field><Field label="Name contains"><input value={p.nameContains} onChange={e=>p.setNameContains(e.target.value)} placeholder="e.g. contract" className="control"/></Field></>}
 {p.selectedState>=0&&p.states[p.selectedState]&&<><Field label="State name"><input value={p.states[p.selectedState].name} onChange={e=>p.updateState(p.selectedState,"name",e.target.value)} className="control"/></Field><Field label="Description"><textarea value={p.states[p.selectedState].description} onChange={e=>p.updateState(p.selectedState,"description",e.target.value)} rows={3} className="control resize-none"/></Field><label className="flex items-center gap-2 text-[10px] text-slate-600"><input type="checkbox" checked={p.states[p.selectedState].terminal} onChange={e=>p.updateState(p.selectedState,"terminal",e.target.checked)}/> Final state</label><button onClick={()=>p.removeState(p.selectedState)} className="text-[10px] font-medium text-red-600">Remove state</button><ActionList actions={[]} add={()=>{}} remove={()=>{}} readOnly/></>}
 {p.selectedTransition>=0&&p.transitions[p.selectedTransition]&&<TransitionInspector p={p}/>}
 {p.selected!=="trigger"&&p.selected!=="condition"&&p.selectedState<0&&p.selectedTransition<0&&<div className="rounded-lg border border-dashed border-slate-300 p-5 text-center text-[10px] text-slate-400">Select a node on the canvas to configure it.</div>}
 {p.selected==="trigger"&&<ActionList actions={p.actions} add={(t:string)=>p.addAction(t,"global")} remove={(i:number)=>p.removeAction("global",i)} update={(i:number,k:string,v:unknown)=>p.updateAction("global",i,k,v)}/>} 
 {p.selected!=="trigger"&&<div className="rounded-lg border border-slate-200 bg-slate-50 p-3"><div className="text-[10px] font-semibold text-slate-700">Workflow fields</div><div className="mt-1 text-[9.5px] leading-4 text-slate-400">{p.fields.length?`${p.fields.length} field${p.fields.length>1?"s":""} available to actions and conditions.`:"No custom fields configured."}</div><button onClick={()=>p.setTab("fields")} className="mt-2 text-[9.5px] font-semibold text-[#1B66EA]">Manage fields →</button></div>}
 </div></aside>}

function TransitionInspector({p}:{p:any}){const [tab,setTab]=useState<"before"|"during"|"after">("before");const t=p.transitions[p.selectedTransition];return <><div className="flex rounded-lg bg-slate-100 p-1"><button onClick={()=>setTab("before")} className={cx("flex-1 rounded-md py-2 text-[9px]",tab==="before"?"bg-white font-semibold shadow-sm":"text-slate-500")}>Before</button><button onClick={()=>setTab("during")} className={cx("flex-1 rounded-md py-2 text-[9px]",tab==="during"?"bg-white font-semibold shadow-sm":"text-slate-500")}>During</button><button onClick={()=>setTab("after")} className={cx("flex-1 rounded-md py-2 text-[9px]",tab==="after"?"bg-white font-semibold shadow-sm":"text-slate-500")}>After</button></div><Field label="Transition name"><input value={t.name} onChange={e=>p.updateTransition(p.selectedTransition,"name",e.target.value)} className="control"/></Field><Field label="To state"><select value={t.to} onChange={e=>p.updateTransition(p.selectedTransition,"to",Number(e.target.value))} className="control">{p.states.map((s:any,i:number)=><option key={i} value={i}>{s.name||`State ${i+1}`}</option>)}</select></Field>{tab==="before"&&<><Field label="Description"><textarea value={t.description||""} onChange={e=>p.updateTransition(p.selectedTransition,"description",e.target.value)} rows={3} className="control resize-none"/></Field><Field label="Condition"><select className="control"><option>Always</option><option>When workflow condition passes</option><option>When a custom field matches</option></select></Field></>}{tab==="during"&&<><Field label="Execution"><div className="space-y-1.5"><label className="flex items-center gap-2 text-[10px] text-slate-600"><input type="radio" checked={!t.trigger} onChange={()=>p.updateTransition(p.selectedTransition,"trigger",undefined)}/> Automatic</label><label className="flex items-center gap-2 text-[10px] text-slate-600"><input type="radio" checked={!!t.trigger} onChange={()=>p.updateTransition(p.selectedTransition,"trigger","manual")}/> Requires action</label></div></Field><ActionList actions={t.actions} add={(x:string)=>p.addAction(x,p.selectedTransition)} remove={(i:number)=>p.removeAction(p.selectedTransition,i)} update={(i:number,k:string,v:unknown)=>p.updateAction(p.selectedTransition,i,k,v)}/></>}{tab==="after"&&<><div className="rounded-lg border border-slate-200 bg-slate-50 p-3 text-[9.5px] leading-4 text-slate-500">After the transition completes, the workflow enters <strong>{p.states[t.to]?.name||"the selected state"}</strong>.</div><Field label="Completion behavior"><select className="control"><option>Continue normally</option><option>Wait for next action</option><option>Mark workflow complete</option></select></Field></>}</>}

function ActionList({actions,add,remove,update,readOnly=false}:{actions:Action[];add:(t:string)=>void;remove:(i:number)=>void;update?:(i:number,k:string,v:unknown)=>void;readOnly?:boolean}){return <div><div className="mb-2 flex items-center justify-between"><label className="text-[10px] font-semibold text-slate-700">Instant actions</label><span className="text-[9px] text-slate-400">{actions.length}/5</span></div><div className="space-y-2">{actions.map((a,i)=><div key={`${a.type}-${i}`} className="rounded-lg border border-slate-200 bg-white p-2.5"><div className="flex items-center gap-2"><span className="text-slate-400">{ACTION_ICONS[a.type]||"•"}</span><span className="flex-1 text-[10px] font-medium text-slate-700">{actionLabel(a.type)}</span>{!readOnly&&<button onClick={()=>remove(i)} className="text-slate-300 hover:text-red-500">×</button>}</div>{!readOnly&&update&&<ActionConfig action={a} update={(k,v)=>update(i,k,v)}/>}</div>)}</div>{!readOnly&&<select defaultValue="" onChange={e=>{if(e.target.value){add(e.target.value);e.currentTarget.value=""}}} className="control mt-2"><option value="">+ Add action</option>{ACTIONS.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>}</div>}
function ActionConfig({action,update}:{action:Action;update:(k:string,v:unknown)=>void}){if(action.type==="notify")return <input value={String(action.config.message??"")} onChange={e=>update("message",e.target.value)} placeholder="Notification message" className="control mt-2"/>; if(["move","copy"].includes(action.type))return <input value={String(action.config.destinationFolderId??"")} onChange={e=>update("destinationFolderId",e.target.value)} placeholder="Destination folder ID" className="control mt-2"/>; if(action.type==="tag")return <input value={String(action.config.name??"")} onChange={e=>update("name",e.target.value)} placeholder="Tag name" className="control mt-2"/>; if(action.type==="create_folder")return <input value={String(action.config.name??"")} onChange={e=>update("name",e.target.value)} placeholder="Folder name" className="control mt-2"/>; if(action.type==="share")return <select value={String(action.config.permission??"VIEW")} onChange={e=>update("permission",e.target.value)} className="control mt-2"><option value="VIEW">View</option><option value="EDIT">Edit</option></select>; if(action.type==="request_approval")return <input value={String(action.config.title??"")} onChange={e=>update("title",e.target.value)} placeholder="Approval title" className="control mt-2"/>; if(action.type==="generate_link")return <label className="mt-2 flex items-center gap-2 text-[9.5px] text-slate-500"><input type="checkbox" checked={action.config.canDownload!==false} onChange={e=>update("canDownload",e.target.checked)}/> Allow download</label>; return null}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div><label className="mb-1.5 block text-[9.5px] font-semibold uppercase tracking-wide text-slate-400">{label}</label>{children}</div>}

function FieldsTab({fields,setFields,addField}:{fields:FieldDraft[];setFields:(v:FieldDraft[])=>void;addField:()=>void}){return <div className="h-[calc(100vh-132px)] overflow-y-auto bg-[#f6f8fb] p-6"><div className="mx-auto max-w-4xl"><div className="rounded-xl border border-slate-200 bg-white"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 className="text-[14px] font-semibold text-slate-900">Workflow fields</h2><p className="mt-1 text-[11px] text-slate-500">Reusable values that can be referenced by conditions and actions.</p></div><button onClick={addField} className="rounded-lg bg-[#1B66EA] px-3 py-2 text-[10.5px] font-semibold text-white">+ Add field</button></div>{fields.length===0?<div className="p-12 text-center text-[11px] text-slate-400">No fields yet. Add a field to make workflow data reusable.</div>:<div className="divide-y divide-slate-100">{fields.map((f,i)=><div key={f.id} className="grid grid-cols-[1fr_150px_90px_40px] items-center gap-3 px-5 py-3"><input value={f.name} onChange={e=>setFields(fields.map((x,j)=>j===i?{...x,name:e.target.value}:x))} className="control"/><select value={f.type} onChange={e=>setFields(fields.map((x,j)=>j===i?{...x,type:e.target.value}:x))} className="control"><option>Text</option><option>Number</option><option>Date</option><option>Date & time</option><option>Yes / No</option><option>Choice</option><option>Email</option></select><label className="flex items-center gap-2 text-[9.5px] text-slate-500"><input type="checkbox" checked={f.required} onChange={e=>setFields(fields.map((x,j)=>j===i?{...x,required:e.target.checked}:x))}/> Required</label><button onClick={()=>setFields(fields.filter((_,j)=>j!==i))} className="text-slate-300 hover:text-red-500">×</button></div>)}</div>}</div></div></div>}
function ReviewTab({name,mode,resourceType,triggers,states,transitions,actions,fields,onBack,onEnable}:{name:string;mode:string;resourceType:string;triggers:string[];states:StateDraft[];transitions:TransitionDraft[];actions:Action[];fields:FieldDraft[];onBack:()=>void;onEnable:()=>void}){const issues=[!name.trim()?"Workflow needs a name.":null,!states.length?"Add at least one state.":null,!states.some(s=>s.terminal)?"Mark at least one state as final.":null,!transitions.length&&states.length>1?"Add a transition between states.":null,transitions.some(t=>t.from===t.to)?"A transition cannot point to the same state.":null].filter(Boolean) as string[];return <div className="h-[calc(100vh-132px)] overflow-y-auto bg-[#f6f8fb] p-6"><div className="mx-auto max-w-4xl space-y-4"><div className="rounded-xl border border-slate-200 bg-white p-5"><div className="flex items-start justify-between gap-4"><div><div className="text-[9px] font-bold uppercase tracking-[.14em] text-slate-400">Review workflow</div><h2 className="mt-1 text-[18px] font-semibold text-slate-900">{name||"Untitled workflow"}</h2><p className="mt-1 text-[11px] text-slate-500">{resourceType} · {mode} · {triggers.length} trigger{triggers.length!==1?"s":""}</p></div><span className={cx("rounded-full px-2.5 py-1 text-[9px] font-semibold",issues.length?"bg-amber-50 text-amber-700":"bg-emerald-50 text-emerald-700")}>{issues.length?`${issues.length} issue${issues.length>1?"s":""}`:"Ready to enable"}</span></div></div><div className="grid gap-4 sm:grid-cols-4"><SummaryCard label="States" value={String(states.length)}/><SummaryCard label="Transitions" value={String(transitions.length)}/><SummaryCard label="Actions" value={String(actions.length+transitions.reduce((n,t)=>n+t.actions.length,0))}/><SummaryCard label="Fields" value={String(fields.length)}/></div>{issues.length>0&&<div className="rounded-xl border border-amber-200 bg-amber-50 p-4"><div className="text-[11px] font-semibold text-amber-800">Before enabling</div><ul className="mt-2 list-disc space-y-1 ps-5 text-[10.5px] text-amber-700">{issues.map(x=><li key={x}>{x}</li>)}</ul></div>}<div className="flex justify-end gap-2"><button onClick={onBack} className="rounded-lg border border-slate-200 bg-white px-4 py-2.5 text-[11px] font-medium">Back to design</button><button disabled={issues.length>0} onClick={onEnable} className="rounded-lg bg-[#1B66EA] px-4 py-2.5 text-[11px] font-semibold text-white disabled:opacity-40">Enable workflow</button></div></div></div>}
function SummaryCard({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-slate-200 bg-white p-4"><div className="text-[9px] font-semibold uppercase tracking-wider text-slate-400">{label}</div><div className="mt-1 text-[22px] font-semibold text-slate-900">{value}</div></div>}
