"use client";
import { useEffect, useState } from 'react';
import { apiRequest } from '../../../lib/api/client';
type Info={name:string;description:string|null;organizationName:string;collectName:boolean;collectEmail:boolean;maxFiles:number|null;maxFileSizeBytes:string|null};
export default function PublicCollectionPage({params}:{params:{token:string}}){
 const [info,setInfo]=useState<Info|null>(null); const [name,setName]=useState(''); const [email,setEmail]=useState(''); const [files,setFiles]=useState<File[]>([]); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
 useEffect(()=>{void apiRequest<Info>(`/collections/public/${encodeURIComponent(params.token)}`).then(setInfo).catch(e=>setMessage(e instanceof Error?e.message:'Collection unavailable'));},[params.token]);
 async function submit(){if(!files.length)return;setBusy(true);setMessage('');try{for(const file of files){const bytes=await file.arrayBuffer();const digest=await crypto.subtle.digest('SHA-256',bytes);const sha256=Array.from(new Uint8Array(digest)).map(b=>b.toString(16).padStart(2,'0')).join('');const init=await apiRequest<any>(`/collections/public/${encodeURIComponent(params.token)}/upload-request`,{method:'POST',body:JSON.stringify({name:file.name,size:file.size,mimeType:file.type||'application/octet-stream',sha256,submitterName:name,submitterEmail:email})});const url=init.upload_url??init.uploadUrl;if(!url)throw new Error('Upload URL was not returned');const put=await fetch(url,{method:'PUT',headers:init.headers??{'Content-Type':file.type||'application/octet-stream'},body:file});if(!put.ok)throw new Error(`Upload failed for ${file.name}`);await apiRequest(`/collections/public/${encodeURIComponent(params.token)}/complete`,{method:'POST',body:JSON.stringify({submissionId:init.submissionId,uploadId:init.upload_id??init.uploadId})});}setMessage('Your files were submitted successfully.');setFiles([]);}catch(e){setMessage(e instanceof Error?e.message:'Submission failed');}finally{setBusy(false)}}
 if(!info)return <main className="mx-auto max-w-xl p-8"><section className="wd-card p-6">{message||'Loading collection…'}</section></main>;
 return <main className="mx-auto max-w-xl p-6 md:py-12"><section className="wd-card p-6 md:p-8"><p className="text-sm text-slate-500">{info.organizationName}</p><h1 className="mt-2 text-2xl font-semibold">{info.name}</h1>{info.description&&<p className="mt-2 text-slate-600">{info.description}</p>}<div className="mt-6 grid gap-4">{info.collectName&&<label className="grid gap-1 text-sm">Your name<input className="wd-input" value={name} onChange={e=>setName(e.target.value)} required /></label>}{info.collectEmail&&<label className="grid gap-1 text-sm">Email<input type="email" className="wd-input" value={email} onChange={e=>setEmail(e.target.value)} required /></label>}<label className="grid gap-1 text-sm">Files<input type="file" multiple className="wd-input" onChange={e=>setFiles(Array.from(e.target.files??[]))}/></label>{files.length>0&&<ul className="list-disc pl-5 text-sm">{files.map(f=><li key={`${f.name}-${f.size}`}>{f.name} — {Math.ceil(f.size/1024)} KB</li>)}</ul>}<button className="wd-primary-button" disabled={busy||!files.length||(info.collectName&&!name.trim())||(info.collectEmail&&!email.trim())} onClick={()=>void submit()}>{busy?'Uploading…':'Submit files'}</button>{message&&<p role="status" className="text-sm">{message}</p>}</div></section></main>
}
