"use client";
import { useEffect, useState } from "react";
import { WorkflowShell } from "@/components/workflow-shell";
import { WorkflowHelp } from "@/components/workflow-help";
import { useLocale } from "@/components/locale-provider";
import { usePathname } from "next/navigation";
import { createWorkflowTemplate, deleteWorkflowTemplate, listWorkflowTemplateVersions, listWorkflowTemplates, previewWorkflowTemplate, rollbackWorkflowTemplateVersion, updateWorkflowTemplate, type WorkflowDataTemplate, type WorkflowDataTemplateVersion } from "@/lib/api/workflows";
import Link from "next/link";

const blank = { name:"", description:"", template:"Dear {{file.name}},\n\nPlease review this file.\n\nStatus: {{workflow.status}}", format:"TEXT" };
export default function WorkflowTemplatesPage(){
 const {locale}=useLocale(); const ar=locale==="ar"; const pathname=usePathname(); const workflowBase=pathname.startsWith("/admin/workflows") ? "/admin/workflows" : "/files/workflows"; const [rows,setRows]=useState<WorkflowDataTemplate[]>([]); const [open,setOpen]=useState(false); const [editing,setEditing]=useState<WorkflowDataTemplate|null>(null); const [draft,setDraft]=useState(blank); const [status,setStatus]=useState("ACTIVE"); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [versions,setVersions]=useState<WorkflowDataTemplateVersion[]>([]); const [versionOpen,setVersionOpen]=useState(false); const [preview,setPreview]=useState<unknown>(null); const [previewOpen,setPreviewOpen]=useState(false);
 const load=()=>void listWorkflowTemplates().then(setRows).catch(()=>setRows([])); useEffect(load,[]);
 const startCreate=()=>{setEditing(null);setDraft(blank);setStatus("ACTIVE");setError("");setOpen(true)};
 const startEdit=(t:WorkflowDataTemplate)=>{setEditing(t);setDraft({name:t.name,description:t.description||"",template:t.template,format:t.format});setStatus(t.status||"ACTIVE");setError("");setOpen(true)};
 const save=async()=>{if(!draft.name.trim()||!draft.template.trim())return;setBusy(true);setError("");try{if(editing) await updateWorkflowTemplate(editing.id,{...draft,status}); else await createWorkflowTemplate(draft);setOpen(false);load()}catch(e){setError(e instanceof Error?e.message:(ar?"تعذر حفظ القالب":"Unable to save template"))}finally{setBusy(false)}};
 const showVersions=async(t:WorkflowDataTemplate)=>{try{setVersions(await listWorkflowTemplateVersions(t.id));setEditing(t);setVersionOpen(true)}catch(e){setError(e instanceof Error?e.message:"Unable to load versions")}};
 const rollback=async(v:WorkflowDataTemplateVersion)=>{if(!editing)return;setBusy(true);try{await rollbackWorkflowTemplateVersion(editing.id,v.id);setVersionOpen(false);load()}catch(e){setError(e instanceof Error?e.message:"Unable to rollback")}finally{setBusy(false)}};
 const remove=async(t:WorkflowDataTemplate)=>{if(!confirm(ar?`حذف القالب «${t.name}»؟`: `Delete “${t.name}”?`))return;try{await deleteWorkflowTemplate(t.id);load()}catch(e){setError(e instanceof Error?e.message:"Unable to delete")}};
 const doPreview=async(t:WorkflowDataTemplate)=>{try{const r=await previewWorkflowTemplate(t.id,{event:{name:"contract.pdf",fileId:"preview-file",fileType:"PDF",extension:".pdf",mimeType:"application/pdf",userId:"preview-user"},fields:{status:ar?"للمراجعة":"For review"}});setPreview(r);setPreviewOpen(true)}catch(e){setError(e instanceof Error?e.message:"Unable to preview")}};
 return <WorkflowShell active="templates" title={ar?"قوالب بيانات سير العمل":"Workflow data templates"} subtitle={ar?"قوالب بإصدارات ثابتة وقيم ديناميكية قابلة للمعاينة.":"Versioned reusable templates with dynamic values and preview."}>
 <main className="h-full overflow-y-auto p-4 sm:p-5" dir={ar?"rtl":"ltr"}><div className="mx-auto max-w-[1200px]">
  <div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><WorkflowHelp compact title={ar?"ما هي قوالب البيانات؟":"What are data templates?"} description={ar?"محتوى قابل لإعادة الاستخدام داخل إجراءات Workflow، مع إصدار نشط ثابت وقيم ديناميكية.":"Reusable workflow action content with an immutable active version and dynamic values."} tips={[ar?"كل تعديل ينشئ إصداراً جديداً.":"Every content change creates a new version.",ar?"استخدم المعاينة للتحقق من القيم قبل الربط بالـ Workflow.":"Use Preview to validate values before wiring a workflow."]}/><div className="text-[10.5px] text-slate-500">{rows.length} {ar?"قالب":"templates"}</div></div><button onClick={startCreate} className="wd-pill wd-pill-new">＋ {ar?"قالب بيانات جديد":"New data template"}</button></div>
  <div className="wd-card mt-5 p-4 sm:p-5"><div className="flex items-start gap-3"><div className="wf-icon">Aa</div><div><h2 className="text-[12px] font-semibold text-slate-900">{ar?"قوالب بإصدارات حقيقية":"Versioned templates"}</h2><p className="mt-1 text-[10.5px] leading-5 text-slate-500">{ar?"يحتفظ النظام بكل نسخة من المحتوى، ويحدد نسخة نشطة يستخدمها Runtime. يمكنك المعاينة أو الرجوع لنسخة سابقة.":"The system keeps every content version and pins an active version for runtime. Preview or roll back to a previous version."}</p></div></div></div>
  {rows.length===0?<div className="wd-card mt-4 border-dashed p-10 text-center"><div className="mx-auto wf-icon">Aa</div><h2 className="mt-3 text-[13px] font-semibold">{ar?"لا توجد قوالب بعد":"No data templates yet"}</h2><button onClick={startCreate} className="wd-pill wd-pill-new mt-4">{ar?"إنشاء أول قالب":"Create first template"}</button></div>:<div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{rows.map(t=><article key={t.id} className="wd-card flex min-h-[230px] flex-col p-4"><div className="flex items-start justify-between gap-2"><div className="wf-icon">Aa</div><span className="rounded-full bg-slate-100 px-2 py-1 text-[8.5px] font-semibold text-slate-500">{t.format} · v{t.activeVersion?.version??1}</span></div><h3 className="mt-3 truncate text-[12.5px] font-semibold text-slate-900">{t.name}</h3><p className="mt-1 min-h-10 text-[10px] leading-5 text-slate-500">{t.description|| (ar?"قالب قابل لإعادة الاستخدام":"Reusable workflow template")}</p><pre className="mt-3 max-h-20 overflow-auto rounded-xl bg-slate-50 p-3 whitespace-pre-wrap text-[9px] leading-4 text-slate-600">{t.template}</pre><div className="mt-auto flex flex-wrap items-center gap-1.5 pt-3"><button className="wd-pill wd-pill-new" onClick={()=>void doPreview(t)}>{ar?"معاينة":"Preview"}</button><button className="wd-pill wd-pill-new" onClick={()=>void showVersions(t)}>{ar?"الإصدارات":"Versions"}</button><button className="wd-pill wd-pill-new" onClick={()=>startEdit(t)}>{ar?"تعديل":"Edit"}</button><button className="wd-icon-btn" title={ar?"حذف":"Delete"} onClick={()=>void remove(t)}>×</button><Link href={`${workflowBase}/builder`} className="wd-pill wd-pill-new ml-auto">{ar?"استخدام":"Use"}</Link></div></article>)}</div>}
  {error&&<div className="mt-4 rounded-xl bg-red-50 p-3 text-[10px] text-red-700">{error}</div>}
 </div></main>
 {open&&<div className="fixed inset-0 z-[240] flex items-center justify-center bg-slate-950/40 p-4" dir={ar?"rtl":"ltr"}><div className="wf-modal w-[min(760px,96vw)] overflow-hidden"><div className="flex items-start justify-between border-b border-slate-100 px-5 py-4"><div><div className="text-[9px] font-semibold uppercase tracking-[.15em] text-[var(--wd-primary)]">{editing?(ar?"تعديل قالب":"Edit template"):(ar?"قالب بيانات":"Data template")}</div><h2 className="mt-1 text-[17px] font-semibold">{editing?(ar?"إنشاء إصدار جديد":"Create new version"):(ar?"إنشاء قالب قابل لإعادة الاستخدام":"Create reusable template")}</h2></div><button className="wd-icon-btn" onClick={()=>setOpen(false)}>×</button></div><div className="grid gap-3 p-5"><label className="text-[10.5px] font-medium">{ar?"الاسم":"Name"}<input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} className="wf-input"/></label><label className="text-[10.5px] font-medium">{ar?"الوصف":"Description"}<input value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})} className="wf-input"/></label><label className="text-[10.5px] font-medium">{ar?"الحالة":"Status"}<select value={status} onChange={e=>setStatus(e.target.value)} className="wf-input"><option>ACTIVE</option><option>DRAFT</option><option>ARCHIVED</option></select></label><label className="text-[10.5px] font-medium">{ar?"الصيغة":"Format"}<select value={draft.format} onChange={e=>setDraft({...draft,format:e.target.value})} className="wf-input"><option>TEXT</option><option>HTML</option><option>JSON</option></select></label><label className="text-[10.5px] font-medium">{ar?"المحتوى":"Template content"}<textarea value={draft.template} onChange={e=>setDraft({...draft,template:e.target.value})} rows={12} className="wf-input min-h-[230px] resize-y font-mono"/><span className="mt-1 block text-[9px] text-slate-400">{ar?"أمثلة: {{file.name}} · {{file.id}} · {{workflow.status}} · {{user.email}}":"Examples: {{file.name}} · {{file.id}} · {{workflow.status}} · {{user.email}}"}</span></label></div><div className="flex justify-end gap-2 border-t border-slate-100 px-5 py-4"><button className="wd-pill wd-pill-record" onClick={()=>setOpen(false)}>{ar?"إلغاء":"Cancel"}</button><button className="wd-pill wd-pill-new" disabled={busy||!draft.name.trim()||!draft.template.trim()} onClick={()=>void save()}>{busy?(ar?"جارٍ الحفظ…":"Saving…"):(editing?(ar?"حفظ كإصدار":"Save new version"):(ar?"إنشاء القالب":"Create template"))}</button></div></div></div>}
 {versionOpen&&<div className="fixed inset-0 z-[240] flex items-center justify-center bg-slate-950/40 p-4" dir={ar?"rtl":"ltr"}><div className="wf-modal w-[min(760px,96vw)] overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 className="text-[16px] font-semibold">{ar?"إصدارات القالب":"Template versions"}</h2><p className="text-[10px] text-slate-500">{editing?.name}</p></div><button className="wd-icon-btn" onClick={()=>setVersionOpen(false)}>×</button></div><div className="max-h-[60vh] overflow-y-auto p-4">{versions.map(v=><div key={v.id} className="mb-2 rounded-xl border border-slate-100 p-3"><div className="flex items-center justify-between"><div className="text-[11px] font-semibold">v{v.version}</div><button className="wd-pill wd-pill-new" disabled={busy||v.id===editing?.activeVersionId} onClick={()=>void rollback(v)}>{v.id===editing?.activeVersionId?(ar?"نشطة":"Active"):(ar?"استرجاع":"Rollback")}</button></div><pre className="mt-2 max-h-24 overflow-auto whitespace-pre-wrap rounded-lg bg-slate-50 p-2 text-[9px]">{v.template}</pre></div>)}</div></div></div>}
 {previewOpen&&<div className="fixed inset-0 z-[240] flex items-center justify-center bg-slate-950/40 p-4" dir={ar?"rtl":"ltr"}><div className="wf-modal w-[min(760px,96vw)] overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 className="text-[16px] font-semibold">{ar?"معاينة القالب":"Template preview"}</h2><p className="text-[10px] text-slate-500">{preview&&typeof preview==='object'&&'version' in preview?`v${String((preview as any).version)}`:""}</p></div><button className="wd-icon-btn" onClick={()=>setPreviewOpen(false)}>×</button></div><div className="grid gap-3 p-5"><pre className="max-h-[45vh] overflow-auto whitespace-pre-wrap rounded-xl bg-slate-50 p-4 text-[10px] leading-5">{preview&&typeof preview==='object'&&'rendered' in preview?String((preview as any).rendered):""}</pre><div className="text-[9px] text-slate-500">{preview&&typeof preview==='object'&&'unresolvedVariables' in preview&&((preview as any).unresolvedVariables as string[]).length?`${ar?"قيم غير معروفة":"Unresolved variables"}: ${((preview as any).unresolvedVariables as string[]).join(", ")}`:(ar?"لا توجد قيم ديناميكية غير معروفة":"No unresolved dynamic values")}</div></div></div></div>}
 </WorkflowShell>
}
