"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { SecondarySidebar } from "@/components/layout/secondary-sidebar";
import { completeWorkflowTask, listWorkflowTasks, type WorkflowTask } from "@/lib/api/workflows";

export default function WorkflowTasksPage() {
  const [rows,setRows]=useState<WorkflowTask[]>([]); const [busy,setBusy]=useState<string|null>(null); const [selected,setSelected]=useState<{task:WorkflowTask;transitionId:string}|null>(null);
  useEffect(()=>{void listWorkflowTasks().then(setRows).catch(()=>setRows([]));},[]);
  const complete=async(task:WorkflowTask,transitionId:string)=>{setBusy(task.id);try{await completeWorkflowTask(task.id,transitionId);setRows(a=>a.filter(x=>x.id!==task.id));setSelected(null);}finally{setBusy(null)}};
  return <div className="flex min-h-0 flex-1 bg-[#f7f8fa]"><SecondarySidebar section="workflows"/><main className="min-w-0 flex-1 overflow-y-auto bg-white"><header className="border-b border-slate-200 px-7 py-5"><div className="flex items-end justify-between"><div><h1 className="text-[20px] font-semibold">Waiting for my action</h1><p className="mt-1 text-[11.5px] text-slate-500">Review workflow tasks and choose an available transition.</p></div><Link href="/files/workflows" className="rounded-full border border-slate-300 px-4 py-2 text-[10.5px]">Workflows</Link></div></header>{rows.length===0?<div className="p-16 text-center text-[11px] text-slate-400">You're all caught up.</div>:<div className="p-7"><div className="rounded-xl border border-slate-200"><div className="grid grid-cols-[minmax(260px,1.6fr)_180px_180px_minmax(220px,1fr)] border-b border-slate-200 px-4 py-3 text-[10px] font-semibold text-slate-500"><div>Task</div><div>Workflow</div><div>State</div><div>Actions</div></div>{rows.map(t=>{const allowed=Array.isArray(t.run.result?.availableTransitionIds)?t.run.result?.availableTransitionIds.map(String):null; const trs=t.workflow.transitions.filter(x=>x.fromStateId===t.state.id && (!allowed || allowed.includes(x.id)));return <div key={t.id} className="grid grid-cols-[minmax(260px,1.6fr)_180px_180px_minmax(220px,1fr)] items-center border-b border-slate-100 px-4 py-4 last:border-0"><div><div className="text-[12px] font-semibold">{t.title}</div><div className="mt-1 text-[9.5px] text-slate-400">{new Date(t.createdAt).toLocaleString()}</div></div><div className="text-[10.5px] text-slate-600">{t.workflow.name}</div><div><span className="rounded-full bg-amber-50 px-2.5 py-1 text-[9.5px] font-semibold text-amber-700">{t.state.name}</span></div><div className="flex flex-wrap gap-2">{trs.map(tr=><button key={tr.id} disabled={busy===t.id} onClick={()=>setSelected({task:t,transitionId:tr.id})} className="rounded-full border border-slate-300 px-3 py-1.5 text-[10px] font-semibold hover:border-blue-500 hover:text-blue-600">{tr.name}</button>)}</div></div>})}</div></div>}{selected&&<TaskModal task={selected.task} transitionId={selected.transitionId} busy={busy===selected.task.id} onClose={()=>setSelected(null)} onComplete={(values)=>void (async()=>{setBusy(selected.task.id);try{await completeWorkflowTask(selected.task.id,selected.transitionId,values);setRows(a=>a.filter(x=>x.id!==selected.task.id));setSelected(null);}finally{setBusy(null)}})()}/>}</main></div>;
}
function TaskModal({task,transitionId,busy,onClose,onComplete}:{task:WorkflowTask;transitionId:string;busy:boolean;onClose:()=>void;onComplete:(v:Record<string,unknown>)=>void}){const [comment,setComment]=useState("");const transition=task.workflow.transitions.find(t=>t.id===transitionId);return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/45 p-5"><div className="w-full max-w-[560px] rounded-xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><div className="text-[10px] text-slate-400">Workflow action</div><h2 className="mt-1 text-[17px] font-semibold">{transition?.name ?? "Complete task"}</h2><p className="mt-1 text-[10.5px] text-slate-500">{task.title}</p></div><button onClick={onClose} className="text-xl text-slate-400">×</button></div><div className="mt-5"><label className="text-[10px] font-semibold text-slate-600">Feedback / comment</label><textarea rows={5} value={comment} onChange={e=>setComment(e.target.value)} className="control mt-2" placeholder="Enter feedback or details collected during this transition"/></div><div className="mt-6 flex justify-end gap-2"><button onClick={onClose} className="rounded-lg border border-slate-300 px-4 py-2.5 text-[11px]">Cancel</button><button disabled={busy} onClick={()=>onComplete({comment})} className="rounded-lg bg-[#0b8f4d] px-5 py-2.5 text-[11px] font-semibold text-white">{busy?"Completing…":"Complete transition"}</button></div></div></div>}
