"use client";
import { useCallback, useEffect, useState } from 'react';
import { useLocale } from '../../../components/locale-provider';
import { createCollection, deleteCollection, listCollections, listCollectionSubmissions, updateCollection, type FileCollection, type CollectionSubmission } from '../../../lib/api/collections';
export default function CollectionsPage(){
 const {label}=useLocale(); const [rows,setRows]=useState<FileCollection[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [show,setShow]=useState(false); const [name,setName]=useState(''); const [folderId,setFolderId]=useState(''); const [description,setDescription]=useState(''); const [type,setType]=useState<'INTERNAL'|'EXTERNAL'>('EXTERNAL'); const [token,setToken]=useState(''); const [separateFolder,setSeparateFolder]=useState(false); const [selected,setSelected]=useState<FileCollection|null>(null); const [submissions,setSubmissions]=useState<CollectionSubmission[]>([]); const [submissionsLoading,setSubmissionsLoading]=useState(false);
 const refresh=useCallback(()=>listCollections().then(setRows).catch(e=>setError(e instanceof Error?e.message:'Unable to load collections')).finally(()=>setLoading(false)),[]);
 useEffect(()=>{void refresh()},[refresh]);
 async function create(){try{const r=await createCollection({name,folderId,description,type,collectName:true,separateFolderPerUser:separateFolder});setToken(r.token);setShow(false);setName('');setFolderId('');setDescription('');setSeparateFolder(false);await refresh()}catch(e){setError(e instanceof Error?e.message:'Unable to create collection')}}
 return <main className="wd-page"><header className="wd-page-head"><div className="wd-page-head-titles"><h1>{label('nav.collectFiles')}</h1><p>Collect files from team members and external people into a selected WorkDrive folder.</p></div><button className="wd-primary-button" onClick={()=>setShow(true)}>＋ Create Collection</button></header>
 {error&&<div className="wd-alert" role="alert">{error}</div>}{token&&<div className="wd-alert" role="status">Collection created. Save this one-time link token: <strong>{token}</strong> <button onClick={()=>setToken('')}>Dismiss</button></div>}
 {loading?<div className="wd-card p-6">Loading collections…</div>:rows.length===0?<section className="wd-card"><div className="wd-empty"><div className="wd-empty-icon">⇧</div><h2>No collections yet</h2><p>Create a collection to receive files from employees, clients, or suppliers.</p><button className="wd-primary-button" onClick={()=>setShow(true)}>Create Collection</button></div></section>:<div className="wd-card overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-start"><th className="p-4 text-start">Collection</th><th className="p-4 text-start">Type</th><th className="p-4 text-start">Destination</th><th className="p-4 text-start">Submissions</th><th className="p-4 text-start">Files</th><th className="p-4 text-start">Status</th><th className="p-4 text-start">Actions</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-b last:border-0"><td className="p-4"><strong>{r.name}</strong><div className="text-xs text-slate-500">{r.description}</div></td><td className="p-4">{r.type}</td><td className="p-4">{r.folder.name}</td><td className="p-4"><button className="underline" onClick={()=>{setSelected(r);setSubmissionsLoading(true);void listCollectionSubmissions(r.id).then(setSubmissions).catch(e=>setError(e instanceof Error?e.message:'Unable to load submissions')).finally(()=>setSubmissionsLoading(false))}}>{r.submissionsCount} · View</button></td><td className="p-4">{r.filesCount}</td><td className="p-4"><span className="wd-badge wd-badge-green">{r.status}</span></td><td className="p-4"><div className="flex gap-2"><button onClick={()=>void updateCollection(r.id,{status:r.status==='ACTIVE'?'DISABLED':'ACTIVE'}).then(refresh)}> {r.status==='ACTIVE'?'Disable':'Enable'} </button><button className="text-red-600" onClick={()=>{if(confirm('Delete this collection?'))void deleteCollection(r.id).then(refresh)}}>Delete</button></div></td></tr>)}</tbody></table></div>}
 {selected&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><section className="w-full max-w-3xl rounded-xl bg-white p-6 shadow-xl"><div className="mb-4 flex items-center justify-between"><h2 className="text-xl font-semibold">Submissions · {selected.name}</h2><button onClick={()=>setSelected(null)}>Close</button></div>{submissionsLoading?<p>Loading submissions…</p>:submissions.length===0?<p className="text-sm text-slate-500">No submissions yet.</p>:<div className="max-h-[60vh] overflow-auto"><table className="w-full text-sm"><thead><tr><th className="p-2 text-start">Submitter</th><th className="p-2 text-start">File</th><th className="p-2 text-start">Status</th><th className="p-2 text-start">Received</th></tr></thead><tbody>{submissions.map(s=><tr key={s.id} className="border-t"><td className="p-2">{s.submitterName||s.submitterEmail||'External submitter'}</td><td className="p-2">{s.file?.name||'—'}</td><td className="p-2">{s.status}</td><td className="p-2">{s.submittedAt?new Date(s.submittedAt).toLocaleString(): '—'}</td></tr>)}</tbody></table></div>}</section></div>} {show&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><section className="w-full max-w-xl rounded-xl bg-white p-6 shadow-xl"><h2 className="mb-4 text-xl font-semibold">Create Collection</h2><div className="grid gap-3"><label className="grid gap-1 text-sm">Collection name<input className="wd-input" value={name} onChange={e=>setName(e.target.value)} /></label><label className="grid gap-1 text-sm">Destination folder ID<input className="wd-input" value={folderId} onChange={e=>setFolderId(e.target.value)} placeholder="Paste WorkDrive folder ID" /></label><label className="grid gap-1 text-sm">Description<textarea className="wd-input" value={description} onChange={e=>setDescription(e.target.value)}/></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={separateFolder} onChange={e=>setSeparateFolder(e.target.checked)}/> Create a separate destination folder for each submitter</label><label className="grid gap-1 text-sm">Collection type<select className="wd-input" value={type} onChange={e=>setType(e.target.value as 'INTERNAL'|'EXTERNAL')}><option value="EXTERNAL">External — anyone with link</option><option value="INTERNAL">Internal — team members</option></select></label></div><div className="mt-6 flex justify-end gap-2"><button className="wd-secondary-button" onClick={()=>setShow(false)}>Cancel</button><button className="wd-primary-button" disabled={!name.trim()||!folderId.trim()} onClick={()=>void create()}>Create</button></div></section></div>}
 </main>
}
