"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { SecondarySidebar } from "@/components/layout/secondary-sidebar";
import { useLocale } from "@/components/locale-provider";
import { activateWorkflow, deactivateWorkflow, deleteWorkflow, duplicateWorkflow, listWorkflows, type Workflow } from "@/lib/api/workflows";
import { Icons } from "@/components/layout/icons";
import { ZohoMenu } from "@/components/layout/zoho-menu";
import { WorkdriveEvents } from "@/lib/workdrive-events";

export default function WorkflowsPage(){
 const {label}=useLocale(); const [newOpen,setNewOpen]=useState(false); const [rows,setRows]=useState<Workflow[]>([]); const [q,setQ]=useState(""); const [scope,setScope]=useState("all"); const [busy,setBusy]=useState<string|null>(null);
 const load=()=>void listWorkflows(scope==="all"?undefined:scope).then(setRows).catch(()=>setRows([])); useEffect(load,[scope]);
 const visible=useMemo(()=>rows.filter(r=>r.name.toLowerCase().includes(q.toLowerCase())),[rows,q]);
 const toggle=async(r:Workflow)=>{setBusy(r.id);try{const next=r.status==="ACTIVE"?await deactivateWorkflow(r.id):await activateWorkflow(r.id);setRows(all=>all.map(x=>x.id===r.id?{...x,...next}:x))}finally{setBusy(null)}};
 const remove=async(r:Workflow)=>{if(!window.confirm(label("workflows.confirmDelete")))return;setBusy(r.id);try{await deleteWorkflow(r.id);setRows(all=>all.filter(x=>x.id!==r.id))}finally{setBusy(null)}};
 const duplicate=async(r:Workflow)=>{setBusy(r.id);try{const copy=await duplicateWorkflow(r.id);setRows(all=>[copy,...all])}finally{setBusy(null)}};
 const exportWorkflow=(r:Workflow)=>{const spec={version:1,name:r.name,description:r.description,mode:r.mode,resourceType:r.resourceType,trigger:r.steps.find(s=>s.kind==="TRIGGER")?.config.value,condition:r.steps.find(s=>s.kind==="CONDITION")?.config.value,actions:r.steps.find(s=>s.kind==="ACTIONS")?.config.value,states:r.states,transitions:r.transitions};const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(spec,null,2)],{type:"application/json"}));a.download=`${r.name}.json`;a.click();URL.revokeObjectURL(a.href)};
 return <div className="flex min-h-0 flex-1 bg-[#F7F9FC]"><SecondarySidebar section="workflows"/><main className="min-w-0 flex-1 overflow-y-auto"><header className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 bg-white px-6 py-4"><div><div className="text-[10px] font-semibold uppercase tracking-[.14em] text-slate-400">Workflows</div><h1 className="mt-1 text-[19px] font-semibold text-slate-900">{label("workflows.title")}</h1><p className="mt-1 text-[12.5px] text-slate-500">{label("workflows.description")}</p></div><div className="relative"><button id="workflow-new-btn" type="button" onClick={()=>setNewOpen(v=>!v)} className="rounded-lg bg-[#1B66EA] px-4 py-2.5 text-[12px] font-semibold text-white">+ {label("quick.new")}</button><ZohoMenu open={newOpen} onClose={()=>setNewOpen(false)} labelledBy="workflow-new-btn" align="end" onSelect={(k)=>{if(k==="workflow")WorkdriveEvents.newWorkflow();else if(k==="folder")window.location.href="/files?new=folder";else if(k==="upload")window.location.href="/files?new=upload";else if(k==="templates")window.location.href="/files/templates";else WorkdriveEvents.externalApps();}} items={[{key:"workflow",labelKey:"workflows.create"},{key:"folder",labelKey:"menu.newFolder"},{key:"upload",labelKey:"menu.uploadFiles"},{key:"templates",labelKey:"menu.templates"},{key:"external",labelKey:"menu.externalApps"}]}/></div></header>
 <div className="border-b border-slate-200 bg-white px-6 py-3"><div className="flex flex-wrap items-center gap-2"><div className="flex min-w-[260px] flex-1 items-center gap-2 rounded-lg border border-slate-200 px-3 py-2"><Icons.search size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={label("workflows.search")} className="min-w-0 flex-1 text-[12.5px] outline-none"/></div>{[["all",label("workflows.all")],["mine",label("workflows.mine")],["drafts",label("workflows.drafts")]].map(([v,t])=><button key={v} type="button" onClick={()=>setScope(v)} className={`rounded-lg px-3 py-2 text-[11.5px] ${scope===v?"bg-[#EEF4FF] font-semibold text-[#1B66EA]":"border border-slate-200 text-slate-600"}`}>{t}</button>)}<Link href="/files/workflows/tasks" className="rounded-lg border border-slate-200 px-3 py-2 text-[11.5px]">{label("workflows.waiting")}</Link><Link href="/files/workflows/runs" className="rounded-lg border border-slate-200 px-3 py-2 text-[11.5px]">{label("workflows.runs")}</Link></div></div>
 {visible.length===0?<div className="p-8"><div className="wd-empty"><span className="wd-empty-icon"><Icons.flow size={24}/></span><h2>{label("workflows.empty")}</h2><p>{label("workflows.description")}</p><Link href="/files/workflows/builder" className="mt-3 inline-flex rounded-lg bg-[#1B66EA] px-4 py-2 text-[12px] text-white">{label("workflows.create")}</Link></div></div>:<div className="space-y-2.5 p-6">{visible.map(r=>{const trigger=r.steps.find(s=>s.kind==="TRIGGER")?.config.value;const actions=(r.steps.find(s=>s.kind==="ACTIONS")?.config.value as Array<{type:string}>)||[];return <article key={r.id} className="rounded-xl border border-slate-200 bg-white p-4 shadow-[0_1px_2px_rgba(15,23,42,.03)]"><div className="flex flex-wrap items-start justify-between gap-4"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="truncate text-[13.5px] font-semibold text-slate-900">{r.name}</h2><span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${r.status==="ACTIVE"?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-600"}`}>{r.status}</span><span className="rounded-full bg-[#EEF4FF] px-2 py-1 text-[10px] font-medium text-[#1B66EA]">{r.mode}</span><span className="rounded-full bg-slate-100 px-2 py-1 text-[10px]">{r.resourceType}</span></div><p className="mt-1.5 text-[11.5px] text-slate-500">{r.description||label("workflows.noDescription")}</p><div className="mt-2 flex flex-wrap gap-1.5"><span className="rounded-md bg-slate-50 px-2 py-1 text-[10.5px] text-slate-600">Trigger: {Array.isArray(trigger)?trigger.join(", "):String(trigger||"—")}</span><span className="rounded-md bg-slate-50 px-2 py-1 text-[10.5px] text-slate-600">{r.states.length} states</span><span className="rounded-md bg-slate-50 px-2 py-1 text-[10.5px] text-slate-600">{actions.length} actions</span></div></div><div className="flex flex-wrap items-center gap-1.5"><Link href={`/files/workflows/builder?id=${r.id}`} className="rounded-md border border-slate-200 px-2.5 py-1.5 text-[10.5px] text-slate-700 hover:bg-slate-50">Edit</Link><button disabled={busy===r.id} onClick={()=>void toggle(r)} className="rounded-md border border-slate-200 px-2.5 py-1.5 text-[10.5px]">{r.status==="ACTIVE"?label("workflows.deactivate"):label("workflows.activate")}</button><button disabled={busy===r.id} onClick={()=>void duplicate(r)} className="rounded-md border border-slate-200 px-2.5 py-1.5 text-[10.5px]">Duplicate</button><button onClick={()=>exportWorkflow(r)} className="rounded-md border border-slate-200 px-2.5 py-1.5 text-[10.5px]">Export</button><button disabled={busy===r.id} onClick={()=>void remove(r)} className="rounded-md border border-red-200 px-2.5 py-1.5 text-[10.5px] text-red-600">{label("workflows.delete")}</button></div></div></article>})}</div>}
 </main></div>
}
