CREATE TABLE `office_background_jobs` (
  `id` CHAR(36) NOT NULL,
  `org_id` CHAR(36) NOT NULL,
  `created_by_id` CHAR(36) NOT NULL,
  `type` VARCHAR(64) NOT NULL,
  `status` ENUM('QUEUED','RUNNING','SUCCEEDED','FAILED','DEAD_LETTER') NOT NULL DEFAULT 'QUEUED',
  `payload` JSON NOT NULL,
  `result` JSON NULL,
  `error` TEXT NULL,
  `attempts` INT NOT NULL DEFAULT 0,
  `max_attempts` INT NOT NULL DEFAULT 3,
  `run_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `locked_at` DATETIME(3) NULL,
  `locked_by` VARCHAR(191) NULL,
  `lease_until` DATETIME(3) NULL,
  `completed_at` DATETIME(3) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `office_background_jobs_org_id_status_run_at_idx` (`org_id`,`status`,`run_at`),
  INDEX `office_background_jobs_status_run_at_created_at_idx` (`status`,`run_at`,`created_at`),
  INDEX `office_background_jobs_created_by_id_created_at_idx` (`created_by_id`,`created_at`),
  CONSTRAINT `office_background_jobs_org_id_fkey` FOREIGN KEY (`org_id`) REFERENCES `organizations` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `office_background_jobs_created_by_id_fkey` FOREIGN KEY (`created_by_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
