CREATE TABLE `office_presence` (
  `id` CHAR(36) NOT NULL,
  `org_id` CHAR(36) NOT NULL,
  `file_id` CHAR(36) NOT NULL,
  `session_id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `cursor` JSON NULL,
  `selection` JSON NULL,
  `status` VARCHAR(191) NOT NULL DEFAULT 'ACTIVE',
  `last_seen_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `office_presence_session_id_key` (`session_id`),
  KEY `office_presence_org_id_file_id_status_idx` (`org_id`,`file_id`,`status`),
  KEY `office_presence_user_id_status_idx` (`user_id`,`status`),
  CONSTRAINT `office_presence_org_id_fkey` FOREIGN KEY (`org_id`) REFERENCES `organizations` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `office_presence_file_id_fkey` FOREIGN KEY (`file_id`) REFERENCES `files` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `office_presence_session_id_fkey` FOREIGN KEY (`session_id`) REFERENCES `office_sessions` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `office_presence_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `office_operations` (
  `id` CHAR(36) NOT NULL,
  `org_id` CHAR(36) NOT NULL,
  `file_id` CHAR(36) NOT NULL,
  `document_id` CHAR(36) NOT NULL,
  `session_id` CHAR(36) NULL,
  `user_id` CHAR(36) NOT NULL,
  `kind` VARCHAR(64) NOT NULL,
  `base_revision` INTEGER NOT NULL,
  `revision` INTEGER NOT NULL,
  `payload` JSON NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `office_operations_org_id_file_id_revision_idx` (`org_id`,`file_id`,`revision`),
  KEY `office_operations_document_id_revision_idx` (`document_id`,`revision`),
  KEY `office_operations_user_id_created_at_idx` (`user_id`,`created_at`),
  CONSTRAINT `office_operations_org_id_fkey` FOREIGN KEY (`org_id`) REFERENCES `organizations` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `office_operations_file_id_fkey` FOREIGN KEY (`file_id`) REFERENCES `files` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `office_operations_document_id_fkey` FOREIGN KEY (`document_id`) REFERENCES `office_documents` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `office_operations_session_id_fkey` FOREIGN KEY (`session_id`) REFERENCES `office_sessions` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `office_operations_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
