import {ShowDocument,ShowLayout,ShowElement,ShowElementType,cloneShow,activeSlide,ShowTransition} from './model';
const uid=(p:string)=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
function layoutElements(layout:ShowLayout):ShowElement[]{if(layout==='blank')return[];if(layout==='title')return[{id:uid('el'),type:'text',x:10,y:25,width:80,height:25,text:'Title',fontSize:38,bold:true,align:'center',color:'#111827'}];if(layout==='two-column')return[{id:uid('el'),type:'text',x:8,y:10,width:84,height:15,text:'Title',fontSize:30,bold:true,align:'center',color:'#111827'},{id:uid('el'),type:'text',x:8,y:32,width:38,height:40,text:'Left content',fontSize:20,color:'#334155'},{id:uid('el'),type:'text',x:54,y:32,width:38,height:40,text:'Right content',fontSize:20,color:'#334155'}];if(layout==='image-text')return[{id:uid('el'),type:'shape',shape:'roundRect',x:8,y:18,width:40,height:55,fill:'#e2e8f0'},{id:uid('el'),type:'text',x:55,y:18,width:38,height:18,text:'Title',fontSize:30,bold:true,color:'#111827'},{id:uid('el'),type:'text',x:55,y:40,width:38,height:30,text:'Describe the image or topic here',fontSize:18,color:'#475569'}];return[{id:uid('el'),type:'text',x:8,y:10,width:84,height:18,text:'Title',fontSize:32,bold:true,align:'center',color:'#111827'},{id:uid('el'),type:'text',x:12,y:38,width:76,height:30,text:'Add your content here',fontSize:20,align:'center'}]}
export function addSlide(d:ShowDocument,layout:ShowLayout='title-content'){const n=cloneShow(d),id=uid('slide');n.slides.push({id,layout,background:n.theme.background,master:n.masters[0]?.id,transition:'fade',transitionDuration:300,elements:layoutElements(layout)});n.activeSlide=id;return n}
export function deleteSlide(d:ShowDocument){if(d.slides.length<=1)return d;const n=cloneShow(d),i=n.slides.findIndex(s=>s.id===n.activeSlide);n.slides.splice(i,1);n.activeSlide=n.slides[Math.max(0,i-1)].id;return n}
export function duplicateSlide(d:ShowDocument){const n=cloneShow(d),s=activeSlide(n);if(!s)return d;const copy=JSON.parse(JSON.stringify(s));copy.id=uid('slide');copy.elements=copy.elements.map((e:any)=>({...e,id:uid('el')}));const i=n.slides.findIndex(x=>x.id===s.id);n.slides.splice(i+1,0,copy);n.activeSlide=copy.id;return n}
export function setActiveSlide(d:ShowDocument,id:string){const n=cloneShow(d);if(n.slides.some(s=>s.id===id))n.activeSlide=id;return n}
export function moveSlide(d:ShowDocument,from:number,to:number){const n=cloneShow(d);if(from<0||to<0||from>=n.slides.length||to>=n.slides.length)return n;const [s]=n.slides.splice(from,1);n.slides.splice(to,0,s);return n}
export function setLayout(d:ShowDocument,layout:ShowLayout){const n=cloneShow(d),s=activeSlide(n);if(s){s.layout=layout;s.elements=layoutElements(layout)}return n}
export function addElement(d:ShowDocument,type:ShowElementType){const n=cloneShow(d),s=activeSlide(n);if(!s)return d;const el:ShowElement=type==='text'?{id:uid('el'),type,x:25,y:35,width:50,height:18,text:'Text',fontSize:22,fontFamily:n.theme.fontFamily,color:'#111827'}:type==='image'?{id:uid('el'),type,x:25,y:25,width:50,height:35,src:'',border:true}:type==='video'?{id:uid('el'),type,x:20,y:20,width:60,height:40,src:'',border:true,mediaAutoplay:false,mediaLoop:false,mediaMuted:true}:type==='audio'?{id:uid('el'),type,x:25,y:40,width:50,height:12,src:'',border:true,mediaAutoplay:false,mediaLoop:false,mediaMuted:false}:type==='line'?{id:uid('el'),type,x:20,y:50,width:60,height:1,color:'#64748b'}:type==='table'?{id:uid('el'),type,x:15,y:25,width:70,height:40,rows:[['A','B'],['1','2'],['3','4']],border:true}:{id:uid('el'),type,x:25,y:30,width:50,height:25,shape:'roundRect',fill:'#dbeafe',color:'#1e3a8a',border:true};s.elements.push(el);return n}
export function updateElement(d:ShowDocument,id:string,patch:Partial<ShowElement>){const n=cloneShow(d),s=activeSlide(n),e=s?.elements.find(x=>x.id===id);if(e)Object.assign(e,patch);return n}
export function updateElements(d:ShowDocument,ids:string[],patch:Partial<ShowElement>){let n=cloneShow(d);for(const id of ids)n=updateElement(n,id,patch);return n}
export function deleteElement(d:ShowDocument,id:string){const n=cloneShow(d),s=activeSlide(n);if(s)s.elements=s.elements.filter(e=>e.id!==id);return n}
export function deleteElements(d:ShowDocument,ids:string[]){const n=cloneShow(d),s=activeSlide(n);if(s)s.elements=s.elements.filter(e=>!ids.includes(e.id));return n}
export function setSlideBackground(d:ShowDocument,color:string){const n=cloneShow(d),s=activeSlide(n);if(s)s.background=color;return n}
export function setAspectRatio(d:ShowDocument,v:'16:9'|'4:3'){const n=cloneShow(d);n.aspectRatio=v;return n}
export function setTheme(d:ShowDocument,patch:Partial<ShowDocument['theme']>){const n=cloneShow(d);n.theme={...n.theme,...patch};return n}
export function reorderElement(d:ShowDocument,id:string,direction:'forward'|'backward'|'front'|'back'){const n=cloneShow(d),s=activeSlide(n);if(!s)return n;const i=s.elements.findIndex(e=>e.id===id);if(i<0)return n;const [e]=s.elements.splice(i,1);let target=direction==='front'?s.elements.length:direction==='back'?0:direction==='forward'?Math.min(i+1,s.elements.length):Math.max(i-1,0);s.elements.splice(target,0,e);return n}
export function groupElements(d:ShowDocument,ids:string[]){if(ids.length<2)return d;const n=cloneShow(d),s=activeSlide(n);const groupId=uid('group');for(const e of s.elements)if(ids.includes(e.id))e.groupId=groupId;return n}
export function ungroupElements(d:ShowDocument,ids:string[]){const n=cloneShow(d),s=activeSlide(n);for(const e of s.elements)if(ids.includes(e.id))delete e.groupId;return n}
export function setSlideNotes(d:ShowDocument,notes:string){const n=cloneShow(d),s=activeSlide(n);if(s)s.notes=notes;return n}
export function setSlideTransition(d:ShowDocument,transition:ShowTransition,duration=300){const n=cloneShow(d),s=activeSlide(n);if(s){s.transition=transition;s.transitionDuration=Math.max(0,Math.min(5000,duration))}return n}
export function addMaster(d:ShowDocument,name='Master'){const n=cloneShow(d);n.masters.push({id:uid('master'),name,background:n.theme.background,elements:[]});return n}
export function assignMaster(d:ShowDocument,masterId:string){const n=cloneShow(d),s=activeSlide(n);if(s&&n.masters.some(m=>m.id===masterId))s.master=masterId;return n}

export function setElementAnimation(d:ShowDocument,id:string,animation:ShowElement['animation']){const n=cloneShow(d),s=activeSlide(n),e=s?.elements.find(x=>x.id===id);if(e)e.animation=animation;return n}
export function clearElementAnimation(d:ShowDocument,id:string){return setElementAnimation(d,id,undefined)}
export function setMediaSource(d:ShowDocument,id:string,src:string,patch:Partial<ShowElement>={}){const n=cloneShow(d),s=activeSlide(n),e=s?.elements.find(x=>x.id===id);if(e)Object.assign(e,{src, ...patch});return n}
export function setSlideAutoAdvance(d:ShowDocument,ms:number|undefined){const n=cloneShow(d),s=activeSlide(n);if(s)s.autoAdvanceMs=ms===undefined?undefined:Math.max(0,Math.min(600000,Math.round(ms)));return n}
