'use client';
import { useEffect, useState } from 'react';
import { listConnections, type Connection } from '@/lib/api/workflows';
import { createExternalStorage, deleteExternalStorage, listExternalStorage, testExternalStorage, updateExternalStorage, type ExternalStorageMount } from '@/lib/api/external-storage';

export default function ExternalStoragePage() {
  const [mounts,setMounts]=useState<ExternalStorageMount[]>([]), [connections,setConnections]=useState<Connection[]>([]), [busy,setBusy]=useState(false), [message,setMessage]=useState('');
  const [name,setName]=useState(''), [connectionId,setConnectionId]=useState(''), [provider,setProvider]=useState('google'), [rootPath,setRootPath]=useState(''), [writeEnabled,setWriteEnabled]=useState(false);
  const load=async()=>{try{const [m,c]=await Promise.all([listExternalStorage(),listConnections({status:'ACTIVE'})]);setMounts(m);setConnections(c.filter(x=>x.authType==='OAUTH2'&&['google','microsoft','dropbox'].includes(x.provider)))}catch(e:any){setMessage(e?.message||'Failed to load external storage')}};
  useEffect(()=>{void load()},[]);
  const create=async()=>{if(!name.trim()||!connectionId)return;setBusy(true);try{await createExternalStorage({name,provider,connectionId,rootPath:rootPath||undefined,readEnabled:true,writeEnabled});setName('');setRootPath('');setWriteEnabled(false);await load();setMessage('تم إنشاء التخزين الخارجي بنجاح.')}catch(e:any){setMessage(e?.message||'فشل إنشاء التخزين')}finally{setBusy(false)}};
  const test=async(id:string)=>{setBusy(true);try{const r=await testExternalStorage(id);setMessage(r.message);await load()}catch(e:any){setMessage(e?.message||'فشل الاختبار')}finally{setBusy(false)}};
  const remove=async(id:string)=>{if(!confirm('إزالة اتصال التخزين الخارجي؟'))return;setBusy(true);try{await deleteExternalStorage(id);await load()}catch(e:any){setMessage(e?.message||'فشل الحذف')}finally{setBusy(false)}};
  const toggle=async(m:ExternalStorageMount)=>{setBusy(true);try{await updateExternalStorage(m.id,{writeEnabled:!m.writeEnabled});await load()}catch(e:any){setMessage(e?.message||'فشل التعديل')}finally{setBusy(false)}};
  return <main dir="rtl" className="min-h-screen bg-[#F6F8FA] p-5 text-[#202B38] lg:p-8"><div className="mx-auto max-w-6xl"><div className="mb-6"><h1 className="text-2xl font-semibold">External Storage</h1><p className="mt-1 text-sm text-[#667085]">اربط Google Drive أو Microsoft OneDrive أو Dropbox مع IMKAN Office لتصفح التخزين الخارجي وتصدير مستندات Office إليه.</p></div>
  <section className="rounded-xl border border-[#E2E8F0] bg-white p-5 shadow-sm"><h2 className="text-base font-semibold">إضافة تخزين خارجي</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><label><span className="mb-1 block text-xs font-semibold">اسم الاتصال</span><input value={name} onChange={e=>setName(e.target.value)} className="h-11 w-full rounded-lg border px-3 text-sm" placeholder="My Drive"/></label><label><span className="mb-1 block text-xs font-semibold">اتصال OAuth</span><select value={connectionId} onChange={e=>{const c=connections.find(x=>x.id===e.target.value);setConnectionId(e.target.value);if(c)setProvider(c.provider)}} className="h-11 w-full rounded-lg border px-3 text-sm"><option value="">اختر اتصال OAuth</option>{connections.map(c=><option key={c.id} value={c.id}>{c.name} — {c.provider}</option>)}</select></label><label><span className="mb-1 block text-xs font-semibold">Root / Folder ID</span><input value={rootPath} onChange={e=>setRootPath(e.target.value)} className="h-11 w-full rounded-lg border px-3 text-sm" placeholder="اختياري"/></label><label className="flex items-center gap-3 pt-6 text-sm"><input type="checkbox" checked={writeEnabled} onChange={e=>setWriteEnabled(e.target.checked)}/><span>السماح بتصدير مستندات Office</span></label></div><button disabled={busy||!name.trim()||!connectionId} onClick={()=>void create()} className="mt-5 rounded-lg bg-[#1463FF] px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{busy?'جارٍ التنفيذ…':'إضافة Mount'}</button></section>
  {message&&<div className="my-4 rounded-lg border border-[#D9E2F2] bg-white p-3 text-sm">{message}</div>}
  <section className="mt-6 space-y-3">{mounts.map(m=><article key={m.id} className="rounded-xl border border-[#E2E8F0] bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><div className="font-semibold">{m.name}</div><div className="mt-1 text-xs text-[#667085]">{m.provider} · {m.rootPath||'Root'} · {m.status}</div></div><div className="flex flex-wrap gap-2"><button disabled={busy} onClick={()=>void test(m.id)} className="rounded-md border px-3 py-2 text-xs">اختبار</button><button disabled={busy} onClick={()=>void toggle(m)} className="rounded-md border px-3 py-2 text-xs">{m.writeEnabled?'تعطيل التصدير':'تفعيل التصدير'}</button><button disabled={busy} onClick={()=>void remove(m.id)} className="rounded-md border border-red-200 px-3 py-2 text-xs text-red-600">إزالة</button></div></div><div className="mt-3 text-xs text-[#667085]">Read: {m.readEnabled?'ON':'OFF'} · Write: {m.writeEnabled?'ON':'OFF'} · Last test: {m.lastTestOk===null?'لم يتم الاختبار':m.lastTestOk?'نجح':'فشل'}</div></article>)}{!mounts.length&&<div className="rounded-xl border border-dashed border-[#CBD5E1] bg-white p-10 text-center text-sm text-[#667085]">لا توجد External Storage mounts بعد.</div>}</section></div></main>;
}
