"use client";
import { useCallback, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { useLocale } from '../../../components/locale-provider';
import { createWorkspaceLabel, deleteWorkspaceLabel, listWorkspaceLabels, listWorkspaceLabelResources, updateWorkspaceLabel, type WorkspaceLabel, type WorkspaceLabelResource } from '../../../lib/api/workspace-labels';
import { FileTypeIcon, fileIconKind } from '../../../components/file-icon';
import { WORKDRIVE_PREVIEW_EVENT, type PreviewEventDetail } from '../../../components/global-search';
import { Toast } from '../../../components/toast';
const COLORS=['#3B82F6','#8B5CF6','#EC4899','#EF4444','#F97316','#EAB308','#22C55E','#14B8A6','#64748B'];
export default function LabelsPage(){
 const {locale}=useLocale(); const ar=locale==='ar'; const router=useRouter();
 const [labels,setLabels]=useState<WorkspaceLabel[]>([]); const [selected,setSelected]=useState<WorkspaceLabel|null>(null); const [resources,setResources]=useState<WorkspaceLabelResource[]>([]);
 const [name,setName]=useState(''); const [color,setColor]=useState(COLORS[0]); const [editing,setEditing]=useState<WorkspaceLabel|null>(null); const [busy,setBusy]=useState(false); const [toast,setToast]=useState<string|null>(null); const [error,setError]=useState('');
 const load=useCallback(async()=>{try{setLabels(await listWorkspaceLabels());setError('')}catch{setError(ar?'تعذر تحميل التصنيفات':'Could not load labels')}},[ar]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{if(!selected){setResources([]);return} void listWorkspaceLabelResources(selected.id).then(setResources).catch(()=>setResources([]))},[selected]);
 const save=async()=>{if(!name.trim())return;setBusy(true);try{if(editing){const updated=await updateWorkspaceLabel(editing.id,{name:name.trim(),color});setLabels(rows=>rows.map(x=>x.id===updated.id?{...updated,resourceCount:x.resourceCount}:x));if(selected?.id===updated.id)setSelected({...updated,resourceCount:selected.resourceCount});}else{const created=await createWorkspaceLabel(name.trim(),color);setLabels(rows=>[...rows,created]);setSelected(created);}setName('');setEditing(null);setToast(ar?'تم حفظ التصنيف':'Label saved')}catch(e){setError(e instanceof Error?e.message:(ar?'تعذر الحفظ':'Could not save label'))}finally{setBusy(false)}};
 const openResource=(r:WorkspaceLabelResource)=>{if(r.resourceType==='FOLDER')router.push(`/files/${r.resourceId}`);else{const detail:PreviewEventDetail={id:r.resourceId,name:r.resource.name,mimeType:r.resource.mimeType??undefined,size:r.resource.size??undefined};window.dispatchEvent(new CustomEvent<PreviewEventDetail>(WORKDRIVE_PREVIEW_EVENT,{detail}))}};
 const remove=async(l:WorkspaceLabel)=>{if(!window.confirm(ar?`حذف التصنيف «${l.name}»؟`:`Delete label “${l.name}”?`))return;try{await deleteWorkspaceLabel(l.id);setLabels(rows=>rows.filter(x=>x.id!==l.id));if(selected?.id===l.id)setSelected(null)}catch{setError(ar?'تعذر حذف التصنيف':'Could not delete label')}};
 return <main className="workflow-ui flex h-full min-h-0 flex-col overflow-hidden bg-white px-5 py-4 sm:px-6" dir={ar?'rtl':'ltr'}>
  <header className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 pb-4"><div><h1 className="text-[20px] font-semibold text-slate-900">{ar?'التصنيفات':'Labels'}</h1><p className="mt-1 text-[11px] text-slate-500">{ar?'نظّم الملفات والمجلدات عبر مواقع مختلفة دون نقلها. التصنيفات خاصة بحسابك.':'Organize files and folders across locations without moving them. Labels are private to your account.'}</p></div><button className="wd-pill wd-pill-new" onClick={()=>{setEditing(null);setName('');setColor(COLORS[0]);document.getElementById('label-name')?.focus()}}>＋ {ar?'إدارة التصنيفات':'Manage Labels'}</button></header>
  {error?<div role="alert" className="mt-3 rounded-lg bg-red-50 p-3 text-[11px] text-red-700">{error}</div>:null}
  <section className="grid min-h-0 flex-1 grid-cols-1 gap-4 pt-4 lg:grid-cols-[300px_minmax(0,1fr)]">
   <aside className="min-h-0 overflow-auto rounded-xl border border-slate-200 bg-white"><div className="border-b border-slate-100 px-4 py-3 text-[12px] font-semibold">{ar?'قائمة التصنيفات':'Your labels'} <span className="ms-1 text-slate-400">{labels.length}</span></div>
    {labels.length===0?<div className="p-8 text-center text-[11px] text-slate-400">{ar?'أنشئ تصنيفًا للبدء':'Create a label to get started'}</div>:labels.map(l=><div key={l.id} className={`group flex items-center gap-2 border-b border-slate-100 px-3 py-2.5 ${selected?.id===l.id?'bg-blue-50':''}`}><button onClick={()=>setSelected(l)} className="flex min-w-0 flex-1 items-center gap-2 text-start"><span className="h-3 w-3 shrink-0 rounded-full" style={{background:l.color}}/><span className="truncate text-[12px] font-medium text-slate-800">{l.name}</span><span className="ms-auto text-[10px] text-slate-400">{l.resourceCount}</span></button><button title={ar?'تعديل':'Edit'} onClick={()=>{setEditing(l);setName(l.name);setColor(l.color)}} className="rounded p-1 text-slate-400 hover:bg-white hover:text-blue-600">✎</button><button title={ar?'حذف':'Delete'} onClick={()=>void remove(l)} className="rounded p-1 text-slate-400 hover:bg-white hover:text-red-600">×</button></div>)}
    <div className="space-y-2 p-3"><div className="text-[11px] font-semibold text-slate-600">{editing?(ar?'تعديل التصنيف':'Edit label'):(ar?'إنشاء تصنيف':'Create label')}</div><input id="label-name" value={name} onChange={e=>setName(e.target.value)} maxLength={80} placeholder={ar?'اسم التصنيف':'Label name'} className="h-9 w-full rounded-lg border border-slate-200 px-3 text-[12px] outline-none focus:border-blue-400"/><div className="flex flex-wrap gap-2">{COLORS.map(c=><button key={c} onClick={()=>setColor(c)} aria-label={c} className={`h-6 w-6 rounded-full border-2 ${color===c?'border-slate-800':'border-white'}`} style={{background:c}}/>)}</div><div className="flex gap-2"><button disabled={busy||!name.trim()} onClick={()=>void save()} className="h-8 flex-1 rounded-lg bg-blue-600 text-[11px] font-semibold text-white disabled:opacity-50">{busy?(ar?'جارٍ الحفظ':'Saving…'):(ar?'حفظ':'Save')}</button>{editing?<button onClick={()=>{setEditing(null);setName('')}} className="h-8 rounded-lg border border-slate-200 px-3 text-[11px]">{ar?'إلغاء':'Cancel'}</button>:null}</div></div>
   </aside>
   <section className="min-h-0 overflow-auto rounded-xl border border-slate-200 bg-white"><div className="flex items-center justify-between border-b border-slate-100 px-4 py-3"><div className="text-[12px] font-semibold">{selected?selected.name:(ar?'اختر تصنيفًا':'Select a label')}</div>{selected?<span className="text-[10px] text-slate-400">{resources.length} {ar?'عنصر':'items'}</span>:null}</div>{!selected?<div className="flex h-[70%] min-h-64 items-center justify-center text-center text-[12px] text-slate-400">{ar?'اختر تصنيفًا لعرض الملفات والمجلدات المرتبطة به':'Choose a label to view its files and folders'}</div>:resources.length===0?<div className="flex h-[70%] min-h-64 items-center justify-center text-center text-[12px] text-slate-400">{ar?'لا توجد ملفات أو مجلدات مرتبطة بهذا التصنيف':'No files or folders have this label yet'}</div>:<div className="workflow-table-shell m-3"><div className="workflow-table-head" style={{gridTemplateColumns:'minmax(260px,1.8fr) 180px 48px'}}><span>{ar?'الاسم':'Name'}</span><span>{ar?'آخر تعديل':'Last modified'}</span><span/></div>{resources.map(r=><div key={r.id} className="workflow-table-row cursor-pointer" style={{gridTemplateColumns:'minmax(260px,1.8fr) 180px 48px'}} onClick={()=>openResource(r)}><div className="flex min-w-0 items-center gap-2"><FileTypeIcon size={18} kind={fileIconKind(r.resourceType==='FOLDER'?'folder':'file',r.resource.mimeType??undefined,r.resource.name)}/><span className="truncate text-[12px] font-medium">{r.resource.name}</span></div><span className="text-[11px] text-slate-500">{r.resource.updatedAt?new Date(r.resource.updatedAt).toLocaleString():'—'}</span><span className="text-slate-400">›</span></div>)}</div>}</section>
  </section>{toast?<Toast message={toast} onDismiss={()=>setToast(null)}/>:null}
 </main>
}
