-- Backup & Recovery core (org-scoped, isolated from Admin Console)

CREATE TABLE `backup_policies` (
  `id` CHAR(36) NOT NULL,
  `org_id` CHAR(36) NOT NULL,
  `name` VARCHAR(120) NOT NULL,
  `enabled` BOOLEAN NOT NULL DEFAULT true,
  `scope` ENUM('ALL', 'TEAM_FOLDERS', 'MY_FOLDERS', 'SELECTED') NOT NULL DEFAULT 'ALL',
  `scope_ids` JSON NOT NULL,
  `schedule_kind` ENUM('MANUAL', 'DAILY', 'WEEKLY', 'MONTHLY') NOT NULL DEFAULT 'MANUAL',
  `schedule_hour_utc` INT NULL,
  `schedule_day` INT NULL,
  `retention_days` INT NULL,
  `exclude_extensions` JSON NOT NULL,
  `last_run_at` DATETIME(3) NULL,
  `next_run_at` DATETIME(3) NULL,
  `created_by_id` CHAR(36) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `backup_policies_org_id_enabled_idx` (`org_id`, `enabled`),
  INDEX `backup_policies_org_id_next_run_at_idx` (`org_id`, `next_run_at`),
  CONSTRAINT `backup_policies_org_id_fkey` FOREIGN KEY (`org_id`) REFERENCES `organizations`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `backup_runs` (
  `id` CHAR(36) NOT NULL,
  `org_id` CHAR(36) NOT NULL,
  `policy_id` CHAR(36) NULL,
  `kind` ENUM('FULL', 'INCREMENTAL') NOT NULL DEFAULT 'FULL',
  `status` ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED') NOT NULL DEFAULT 'PENDING',
  `snapshot_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `started_at` DATETIME(3) NULL,
  `finished_at` DATETIME(3) NULL,
  `files_total` INT NOT NULL DEFAULT 0,
  `files_copied` INT NOT NULL DEFAULT 0,
  `files_skipped` INT NOT NULL DEFAULT 0,
  `bytes_total` BIGINT NOT NULL DEFAULT 0,
  `bytes_copied` BIGINT NOT NULL DEFAULT 0,
  `error_message` TEXT NULL,
  `manifest_sha256` CHAR(64) NULL,
  `triggered_by_id` CHAR(36) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `backup_runs_org_id_status_created_at_idx` (`org_id`, `status`, `created_at`),
  INDEX `backup_runs_org_id_snapshot_at_idx` (`org_id`, `snapshot_at`),
  INDEX `backup_runs_policy_id_idx` (`policy_id`),
  CONSTRAINT `backup_runs_org_id_fkey` FOREIGN KEY (`org_id`) REFERENCES `organizations`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `backup_runs_policy_id_fkey` FOREIGN KEY (`policy_id`) REFERENCES `backup_policies`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `backup_objects` (
  `id` CHAR(36) NOT NULL,
  `org_id` CHAR(36) NOT NULL,
  `run_id` CHAR(36) NOT NULL,
  `resource_type` VARCHAR(20) NOT NULL,
  `resource_id` CHAR(36) NOT NULL,
  `parent_resource_id` CHAR(36) NULL,
  `name` VARCHAR(500) NOT NULL,
  `path` VARCHAR(2000) NOT NULL,
  `mime_type` VARCHAR(200) NULL,
  `size` BIGINT NOT NULL DEFAULT 0,
  `sha256_hash` CHAR(64) NULL,
  `backup_storage_key` VARCHAR(1000) NOT NULL,
  `source_storage_key` VARCHAR(1000) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `backup_objects_org_id_run_id_idx` (`org_id`, `run_id`),
  INDEX `backup_objects_run_id_resource_type_resource_id_idx` (`run_id`, `resource_type`, `resource_id`),
  INDEX `backup_objects_org_id_path_idx` (`org_id`, `path`),
  CONSTRAINT `backup_objects_org_id_fkey` FOREIGN KEY (`org_id`) REFERENCES `organizations`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `backup_objects_run_id_fkey` FOREIGN KEY (`run_id`) REFERENCES `backup_runs`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `backup_restore_jobs` (
  `id` CHAR(36) NOT NULL,
  `org_id` CHAR(36) NOT NULL,
  `run_id` CHAR(36) NOT NULL,
  `mode` ENUM('ORIGINAL', 'NEW_LOCATION', 'DOWNLOAD') NOT NULL DEFAULT 'NEW_LOCATION',
  `status` ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED') NOT NULL DEFAULT 'PENDING',
  `object_ids` JSON NOT NULL,
  `target_folder_id` CHAR(36) NULL,
  `items_total` INT NOT NULL DEFAULT 0,
  `items_done` INT NOT NULL DEFAULT 0,
  `error_message` TEXT NULL,
  `requested_by_id` CHAR(36) NOT NULL,
  `started_at` DATETIME(3) NULL,
  `finished_at` DATETIME(3) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `backup_restore_jobs_org_id_status_created_at_idx` (`org_id`, `status`, `created_at`),
  INDEX `backup_restore_jobs_run_id_idx` (`run_id`),
  CONSTRAINT `backup_restore_jobs_org_id_fkey` FOREIGN KEY (`org_id`) REFERENCES `organizations`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `backup_restore_jobs_run_id_fkey` FOREIGN KEY (`run_id`) REFERENCES `backup_runs`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
