'use client';

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { useParams, useRouter, useSearchParams } from 'next/navigation';
import { closeOfficeSession, getOfficeOperations, heartbeatOfficePresence, openOfficeSession, touchOfficeSession } from '@/lib/api/office';
import { enqueueWriterChange, flushWriterQueue, useOfficePresence, useOfficeRealtime, writerOfflineQueueCount } from '@/office/collaboration';
import { OfficePresence } from '@/components/office-presence';
import { OfficeConflictDialog } from '@/components/office-conflict-dialog';
import { useLocale } from '@/components/locale-provider';
import { OfficeTransferControls } from '@/components/office-transfer-controls';
import { WriterToolbar } from '@/office/writer/toolbar';
import { OfficeShell } from '@/components/office-shell';
import { OfficeRibbon } from '@/components/office-ribbon';
import { OfficeMobile } from '@/components/office-mobile';
import { OfficeTemplateFields } from '@/components/office-template-fields';
import { addParagraph, addTableColumn, addTableRow, cloneWriterDocument, insertHorizontalRule, insertImage, insertPageBreak, insertTable, mergeAdjacentRuns, patchBlockRuns, removeBlock, removeTableColumn, removeTableRow, setBlockAlignment, setBlockSpacing, setBlockType, setListOrdered, toggleTableBorders, updatePageSettings, updateBlockLayout, insertTableOfContents, addBookmark, addFootnote, replaceAllText, updateSection, addSection, insertSectionBreak, insertEquation, insertSymbol, addCitation, insertBibliography, insertIndex, addCaption, addCrossReference, addIndexEntry, updateImage, updateTableOptions, setTableCellVerticalAlign, addNestedTable } from '@/office/writer/commands';
import type { WriterBlock, WriterDocument, WriterRun } from '@/office/writer/model';
import { applyWriterPatches } from '@/office/writer/operation-patches';
import { readWriterQueue } from '@/office/writer/collaboration';
import { addComment, acceptChange, acceptAllChanges, addSnapshot, compareSnapshot, deleteComment, rejectAllChanges, rejectChange, replyComment, setReviewDisplayMode, setShowFormattingChanges, toggleCommentResolved, toggleTrackChanges, recordChange, textOfRuns } from '@/office/writer/review';
import { normalizeWriterDocument } from '@/office/writer/model';
import { officeClone } from '@/office/performance';
import { cacheOfficeSnapshot, readOfficeSnapshot, offlineQueueCount, installOfflineSync, readOfflineConflict, prepareWriterConflict, rebaseWriterQueue, discardWriterQueue } from '@/office/offline';

function t(ar: boolean, en: string, arText: string) { return ar ? arText : en; }
const cloneWriterValue = <T,>(value:T):T => officeClone(value);
function escapeHtml(text: string) { return text.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;'); }
function htmlForRuns(runs: WriterRun[]) { return runs.map(run => { let v=escapeHtml(run.text).replaceAll('\n','<br/>'); if(run.bold)v=`<strong>${v}</strong>`; if(run.italic)v=`<em>${v}</em>`; if(run.underline)v=`<u>${v}</u>`; if(run.strike)v=`<s>${v}</s>`; if(run.href)v=`<a href="${escapeHtml(run.href)}" target="_blank" rel="noreferrer">${v}</a>`; if(run.verticalAlign==='superscript')v=`<sup>${v}</sup>`; if(run.verticalAlign==='subscript')v=`<sub>${v}</sub>`; const style=[run.fontFamily?`font-family:${escapeHtml(run.fontFamily)}`:'',run.fontSize?`font-size:${run.fontSize}px`:'',run.color?`color:${run.color}`:'',run.highlight?`background-color:${run.highlight}`:''].filter(Boolean).join(';'); return style?`<span style="${style}">${v}</span>`:v; }).join('') || '<br />'; }
function runsFromElement(element: HTMLElement): WriterRun[] {
 const runs: WriterRun[]=[];
 const walk=(node:Node, marks:Omit<WriterRun,'text'>)=>{ if(node.nodeType===Node.TEXT_NODE){const text=node.textContent??'';if(text)runs.push({text,...marks});return;} if(node.nodeType!==Node.ELEMENT_NODE)return; const el=node as HTMLElement; const style=el.style; const href=el.tagName==='A'?(el as HTMLAnchorElement).href:marks.href; const next={bold:marks.bold||el.tagName==='STRONG'||el.tagName==='B',italic:marks.italic||el.tagName==='EM'||el.tagName==='I',underline:marks.underline||el.tagName==='U',strike:marks.strike||el.tagName==='S'||el.tagName==='DEL',fontFamily:style.fontFamily?.replaceAll('"',''),fontSize:style.fontSize?Number.parseFloat(style.fontSize):marks.fontSize,color:style.color?.startsWith('rgb')?rgbToHex(style.color):style.color||marks.color,href,verticalAlign:el.tagName==='SUP'?'superscript':el.tagName==='SUB'?'subscript':marks.verticalAlign}; el.childNodes.forEach(c=>walk(c,next));}; element.childNodes.forEach(c=>walk(c,{})); return mergeAdjacentRuns(runs);
}
function rgbToHex(value:string){const m=value.match(/\d+/g);if(!m||m.length<3)return value;return '#'+m.slice(0,3).map(x=>Number(x).toString(16).padStart(2,'0')).join('');}
function blockClass(block:WriterBlock){if(block.type==='heading1')return 'text-3xl font-bold leading-tight';if(block.type==='heading2')return 'text-2xl font-bold leading-tight';if(block.type==='heading3')return 'text-xl font-semibold leading-tight';return 'text-[16px] leading-7';}
function pagesFor(doc:WriterDocument){const pages:WriterBlock[][]=[[]];for(const block of doc.blocks){if(block.type==='page-break'){pages.push([]);continue;}if(block.pageBreakBefore&&pages[pages.length-1].length)pages.push([]);pages[pages.length-1].push(block);}return pages.filter((p,i)=>p.length||i===0);}


function formatPageNumber(n:number, format:'decimal'|'roman-lower'|'roman-upper'|'letter-upper'|'letter-lower'='decimal'){
 if(format==='decimal')return String(n); if(format.startsWith('letter-')){let x=Math.max(1,n),out='';while(x){x--;out=String.fromCharCode(65+(x%26))+out;x=Math.floor(x/26);}return format==='letter-lower'?out.toLowerCase():out;}
 const vals:[[number,string]]|any=[[1000,'M'],[900,'CM'],[500,'D'],[400,'CD'],[100,'C'],[90,'XC'],[50,'L'],[40,'XL'],[10,'X'],[9,'IX'],[5,'V'],[4,'IV'],[1,'I']];let x=Math.max(1,n),out='';for(const [v,c] of vals as any)while(x>=v){out+=c;x-=v;}return format==='roman-lower'?out.toLowerCase():out;
}
function sectionForBlock(doc:WriterDocument, block:WriterBlock){return doc.sections.find(s=>s.id===block.sectionId)||doc.sections[0];}
function imageStyle(block:any){const img=block.image;const wrap=img?.wrap==='square'?'float-left':img?.wrap==='behind'?'absolute':img?.wrap==='front'?'relative z-10':'mx-auto';const crop=img?.crop?`inset(${img.crop.top}% ${img.crop.right}% ${img.crop.bottom}% ${img.crop.left}%)`:undefined;return {width:img?.width?`${img.width}px`:'auto',maxWidth:'100%',height:img?.height?`${img.height}px`:'auto',transform:`rotate(${img?.rotation??0}deg)`,objectFit:'contain' as const,clipPath:crop?`inset(${img.crop.top}% ${img.crop.right}% ${img.crop.bottom}% ${img.crop.left}%)`:undefined};}

function formatPageNumber(n:number, format:'decimal'|'roman-lower'|'roman-upper'|'letter-upper'|'letter-lower'='decimal'){ if(format==='decimal')return String(n); if(format.startsWith('letter-')){let x=Math.max(1,n),out='';while(x){x--;out=String.fromCharCode(65+(x%26))+out;x=Math.floor(x/26);}return format==='letter-lower'?out.toLowerCase():out;} const vals:any=[[1000,'M'],[900,'CM'],[500,'D'],[400,'CD'],[100,'C'],[90,'XC'],[50,'L'],[40,'XL'],[10,'X'],[9,'IX'],[5,'V'],[4,'IV'],[1,'I']];let x=Math.max(1,n),out='';for(const [v,c] of vals)while(x>=v){out+=c;x-=v;}return format==='roman-lower'?out.toLowerCase():out; }
function sectionForBlock(doc:WriterDocument, block:WriterBlock){return doc.sections.find(s=>s.id===block.sectionId)||doc.sections[0];}
function imageStyle(block:any){const img=block.image;return {width:img?.width?`${img.width}px`:'auto',maxWidth:'100%',height:img?.height?`${img.height}px`:'auto',transform:`rotate(${img?.rotation??0}deg)`,objectFit:'contain' as const,clipPath:img?.crop?`inset(${img.crop.top}% ${img.crop.right}% ${img.crop.bottom}% ${img.crop.left}%)`:undefined};}

export default function ImkanWriterPage(){
 const {locale}=useLocale();const ar=locale==='ar';const {fileId}=useParams<{fileId:string}>();const router=useRouter();const searchParams=useSearchParams();const templateId=searchParams.get('templateId');
 const [doc,setDoc]=useState<WriterDocument|null>(null);
 const presence=useOfficePresence(fileId,sessionId);
 const realtimeHandler=useCallback((event:{revision?:number})=>{ if(typeof event.revision!=='number'||event.revision<=revision) return; void getOfficeOperations(fileId,revision).then(ops=>{ let next=docRef.current; if(!next)return; const pending=readWriterQueue(fileId); for(const op of ops){ if(op.user?.id===undefined)continue; const patches=Array.isArray(op.payload?.patches)?op.payload.patches:[]; if(!patches.length)continue; const overlaps=pending.some(local=>local.patches.some(lp=>patches.some((rp:any)=>lp.path===rp.path||lp.path.startsWith(`${rp.path}/`)||rp.path.startsWith(`${lp.path}/`)))); if(overlaps){setError(t(ar,'A remote edit overlaps your local offline work. Reload to reconcile.','يوجد تعديل بعيد يتعارض مع عملك المحلي غير المتزامن. أعد التحميل للمصالحة.'));return;} next=applyWriterPatches(next,patches); } if(next){setDoc(next);docRef.current=next;dirtyDoc.current=next;setRevision(event.revision as number);setSaved(readWriterQueue(fileId).length===0);} }).catch(()=>void openOfficeSession(fileId).then(r=>{const next=normalizeWriterDocument(r.document.content);setDoc(next);docRef.current=next;dirtyDoc.current=next;setRevision(r.document.revision);})); },[fileId,revision,ar]);
 useOfficeRealtime(fileId,sessionId,undefined,realtimeHandler);
 const [findOpen,setFindOpen]=useState(false); const [findTerm,setFindTerm]=useState(''); const [replaceTerm,setReplaceTerm]=useState('');
 const [reviewTab,setReviewTab]=useState<'comments'|'changes'|'compare'>('comments');
 const [reviewOpen,setReviewOpen]=useState(false);
 const [commentDraft,setCommentDraft]=useState('');
 const [commentFilter,setCommentFilter]=useState<'all'|'open'|'resolved'>('open');
 const [changeFilter,setChangeFilter]=useState<'pending'|'accepted'|'rejected'|'all'>('pending');
 const [replyDraft,setReplyDraft]=useState<Record<string,string>>({});
 const [compareId,setCompareId]=useState('');const [revision,setRevision]=useState(1);const [conflict,setConflict]=useState<any>(()=>readOfflineConflict(fileId));const [sessionId,setSessionId]=useState('');const [activeBlockId,setActiveBlockId]=useState('');const [saving,setSaving]=useState(false);const [saved,setSaved]=useState(true);const [error,setError]=useState('');const [history,setHistory]=useState<WriterDocument[]>([]);const [future,setFuture]=useState<WriterDocument[]>([]);
 const docRef=useRef<WriterDocument|null>(null);const saveTimer=useRef<ReturnType<typeof setTimeout>|null>(null);const dirtyDoc=useRef<WriterDocument|null>(null);
 useEffect(()=>{let cancelled=false;void openOfficeSession(fileId).then(r=>{if(cancelled)return;const next=normalizeWriterDocument(r.document.content);setDoc(next);docRef.current=next;dirtyDoc.current=next;setRevision(r.document.revision);setSessionId(r.sessionId);setHistory([]);setFuture([]);cacheOfficeSnapshot(fileId,'WRITER',r.document.revision,next);}).catch(e=>{const cached=readOfficeSnapshot(fileId);if(cached?.document){const next=normalizeWriterDocument(cached.document);setDoc(next);docRef.current=next;dirtyDoc.current=next;setRevision(cached.revision);setSaved(offlineQueueCount(fileId)===0);setError(t(ar,'Offline mode: using the latest local copy.','وضع عدم الاتصال: يتم استخدام أحدث نسخة محلية.'));}else setError(e instanceof Error?e.message:t(ar,'Unable to open IMKAN Writer.','تعذر فتح IMKAN Writer.'))});return()=>{cancelled=true;};},[fileId,ar]);
 useEffect(()=>{const sync=()=>void flushWriterQueue(fileId,sessionId,(r)=>{setRevision(r);if(docRef.current)cacheOfficeSnapshot(fileId,'WRITER',r,docRef.current)},e=>setError(e instanceof Error?e.message:t(ar,'Sync is waiting for reconciliation.','المزامنة تنتظر المصالحة.')));window.addEventListener('online',sync);return()=>window.removeEventListener('online',sync);},[fileId,sessionId,ar]);
 useEffect(()=>installOfflineSync(fileId,()=>sessionId||undefined,{onOnline:()=>void flushWriterQueue(fileId,sessionId,(r)=>setRevision(r),e=>setError(e instanceof Error?e.message:t(ar,'Sync is waiting for reconciliation.','المزامنة تنتظر المصالحة.'))),onOffline:()=>setError(t(ar,'Offline. Changes will sync automatically.','أنت غير متصل. ستتم مزامنة التغييرات تلقائيًا.'))}),[fileId,sessionId,ar]);
 useEffect(()=>{if(!sessionId)return;const beat=()=>void heartbeatOfficePresence(sessionId,{status:document.hidden?'IDLE':'ACTIVE',cursor:{blockId:activeBlockId||null},selection:{blockId:activeBlockId||null}}).catch(()=>undefined);beat();const timer=window.setInterval(beat,2500);return()=>window.clearInterval(timer);},[sessionId,activeBlockId]);
 const persist=useCallback((previous:WriterDocument,next:WriterDocument)=>{dirtyDoc.current=next;setSaved(false);const operation=enqueueWriterChange(fileId,revision,previous,next,sessionId);if(!operation){setSaved(true);return;}setSaving(true);void flushWriterQueue(fileId,sessionId,(nextRevision)=>{setRevision(nextRevision);if(docRef.current)cacheOfficeSnapshot(fileId,'WRITER',nextRevision,docRef.current);setSaved(writerOfflineQueueCount(fileId)===0);setSaving(writerOfflineQueueCount(fileId)>0);dirtyDoc.current=docRef.current;},(e)=>{if(e?.status===409||e?.code?.includes?.('WRITER_OPERATION_CONFLICT')){void prepareWriterConflict(fileId,e?.code||'WRITER_OPERATION_CONFLICT').then(setConflict);setError(t(ar,'This edit overlaps a newer change. Choose how to reconcile it.','هذا التعديل يتعارض مع تعديل أحدث. اختر طريقة المصالحة.'));}else if(typeof navigator!=='undefined'&&!navigator.onLine)setError(t(ar,'Offline. Changes are queued locally and will sync when you reconnect.','أنت غير متصل. تم حفظ التغييرات محليًا وستتم مزامنتها عند عودة الاتصال.'));else setError(e instanceof Error?e.message:t(ar,'Sync failed.','فشلت المزامنة.'));setSaving(false);});},[fileId,revision,sessionId,ar]);
 const commit=useCallback((next:WriterDocument)=>{const current=docRef.current;if(current)setHistory(items=>[...items.slice(-99),cloneWriterDocument(current)]);if(current)persist(current,next);docRef.current=next;setDoc(next);setFuture([]);},[persist]);
 useEffect(()=>{if(!sessionId)return;const id=setInterval(()=>void touchOfficeSession(sessionId).catch(()=>undefined),30000);return()=>clearInterval(id);},[sessionId]);
 useEffect(()=>()=>{if(saveTimer.current)clearTimeout(saveTimer.current);if(dirtyDoc.current&&sessionId)void closeOfficeSession(sessionId).catch(()=>undefined);},[sessionId]);
 const resolveConflict=async(choice:'local'|'remote')=>{if(choice==='remote'&&conflict?.remote){discardWriterQueue(fileId);const remote=normalizeWriterDocument(conflict.remote);docRef.current=remote;dirtyDoc.current=remote;setDoc(remote);setRevision(conflict.remoteRevision);cacheOfficeSnapshot(fileId,'WRITER',conflict.remoteRevision,remote);setSaved(true);setConflict(null);return;}const result=await rebaseWriterQueue(fileId);if(result.ok){const next=normalizeWriterDocument(result.document);docRef.current=next;dirtyDoc.current=next;setDoc(next);setRevision(result.revision);setConflict(null);const {flushWriterQueue}=await import('@/office/writer/collaboration');await flushWriterQueue(fileId,sessionId,r=>setRevision(r),async e=>{if(e?.status===409)setConflict(await prepareWriterConflict(fileId,e?.code||'WRITER_OPERATION_CONFLICT'));});setSaved(writerOfflineQueueCount(fileId)===0);}else setError(t(ar,'These changes overlap the remote edit. Reconcile the document manually.','هذه التغييرات تتداخل مع التعديل البعيد. قم بالمصالحة يدويًا.'));};
 const activeBlock=useMemo(()=>doc?.blocks.find(b=>b.id===activeBlockId)??doc?.blocks.find(b=>b.type!=='page-break')??null,[doc,activeBlockId]);
 const applyCommand=(command:'bold'|'italic'|'underline'|'strike')=>{const current=docRef.current;if(!current||!activeBlock)return;const before=cloneWriterValue(current).blocks.find(b=>b.id===activeBlock.id)?.runs??[];document.execCommand(command==='strike'?'strikeThrough':command,false);const el=document.querySelector(`[data-writer-block="${activeBlock.id}"]`) as HTMLElement|null;if(el){const next={...current,blocks:current.blocks.map(b=>b.id===activeBlock.id?{...b,runs:runsFromElement(el)}:b)};commit(recordChange(next,activeBlock.id,before,next.blocks.find(b=>b.id===activeBlock.id)?.runs??[], 'format'));}};
 const updateBlockRuns=(blockId:string,element:HTMLElement)=>{const current=docRef.current;if(!current)return;const next=cloneWriterDocument(current);const block=next.blocks.find(x=>x.id===blockId);if(!block)return;const before=cloneWriterValue(current).blocks.find(x=>x.id===blockId)?.runs??[];block.runs=runsFromElement(element);const reviewed=recordChange(next,blockId,before,block.runs,'format');docRef.current=reviewed;setDoc(reviewed);dirtyDoc.current=reviewed;setSaved(false);if(saveTimer.current)clearTimeout(saveTimer.current);saveTimer.current=setTimeout(()=>persist(reviewed),700);};
 const updateTableCell=(blockId:string,row:number,col:number,element:HTMLElement)=>{const current=docRef.current;if(!current)return;const next=cloneWriterDocument(current);const block=next.blocks.find(x=>x.id===blockId);const cell=block?.table?.rows[row]?.[col];if(!cell)return;cell.runs=runsFromElement(element);docRef.current=next;setDoc(next);dirtyDoc.current=next;persist(next);};
 const insertTemplateField=(placeholder:string)=>{const current=docRef.current;const target=activeBlock;if(!current||!target)return;const next=cloneWriterDocument(current);const block=next.blocks.find(b=>b.id===target.id);if(!block)return;const last=block.runs[block.runs.length-1];if(last)last.text=(last.text||'')+placeholder;else block.runs=[{text:placeholder}];commit(next);};
 const undo=()=>{const current=docRef.current,previous=history[history.length-1];if(!current||!previous)return;setHistory(items=>items.slice(0,-1));setFuture(items=>[cloneWriterDocument(current),...items].slice(0,100));docRef.current=previous;setDoc(previous);persist(previous);};
 const redo=()=>{const current=docRef.current,next=future[0];if(!current||!next)return;setFuture(items=>items.slice(1));setHistory(items=>[...items.slice(-99),cloneWriterDocument(current)]);docRef.current=next;setDoc(next);persist(next);};
 const insertLink=()=>{const url=window.prompt(t(ar,'Enter URL','أدخل الرابط'),'https://');if(!url)return;document.execCommand('createLink',false,url);const el=document.querySelector(`[data-writer-block="${activeBlock?.id}"]`) as HTMLElement|null;const current=docRef.current;if(el&&current&&activeBlock)commit({...current,blocks:current.blocks.map(b=>b.id===activeBlock.id?{...b,runs:runsFromElement(el)}:b)});};
 const addImage=()=>{const src=window.prompt(t(ar,'Enter image URL','أدخل رابط الصورة'));if(!src)return;const current=docRef.current;if(current)commit(insertImage(current,src,t(ar,'Image','صورة'),activeBlock?.id));};
 const applyRunPatch=(patch: any)=>{const current=docRef.current;if(!current||!activeBlock)return;commit(patchBlockRuns(current,activeBlock.id,patch));};
 const tableAction=(action:'add-row'|'remove-row'|'add-col'|'remove-col'|'borders')=>{const current=docRef.current;if(!current||!activeBlock)return; if(action==='add-row')commit(addTableRow(current,activeBlock.id)); else if(action==='remove-row')commit(removeTableRow(current,activeBlock.id,activeBlock.table?.rows.length ? activeBlock.table.rows.length-1 : 0)); else if(action==='add-col')commit(addTableColumn(current,activeBlock.id)); else if(action==='remove-col')commit(removeTableColumn(current,activeBlock.id,activeBlock.table?.rows[0]?.length ? activeBlock.table.rows[0].length-1 : 0)); else commit(toggleTableBorders(current,activeBlock.id));};
 const wordStats=useMemo(()=>{if(!doc)return {words:0,chars:0};const text=doc.blocks.flatMap(b=>[b.runs?.map(r=>r.text).join('')||'',...(b.table?b.table.rows.flatMap(r=>r.map(c=>c.runs.map(x=>x.text).join(''))):[]) ]).join(' ');return {words:text.trim()?text.trim().split(/\s+/).length:0,chars:text.length};},[doc]);
 const doReplaceAll=()=>{if(!doc||!findTerm)return;commit(replaceAllText(doc,findTerm,replaceTerm));};
 const askBookmark=()=>{if(!doc||!activeBlock)return;const name=window.prompt(t(ar,'Bookmark name','اسم الإشارة المرجعية'),'bookmark-'+(doc.bookmarks.length+1));if(name)commit(addBookmark(doc,activeBlock.id,name));};
 const askFootnote=()=>{if(!doc||!activeBlock)return;const text=window.prompt(t(ar,'Footnote text','نص الحاشية السفلية'),'');if(text)commit(addFootnote(doc,activeBlock.id,text));};
 const configureColumns=(columns:number)=>{const current=docRef.current;if(!current)return;const secId=activeBlock?.sectionId||current.sections[0]?.id;if(secId)commit(updateSection(current,secId,{columns:Math.max(1,Math.min(4,columns))}));};
 const configureSectionBreak=()=>{const current=docRef.current;if(current)commit(insertSectionBreak(current,activeBlock?.id,2));};
 const configureHeaderFooter=()=>{const current=docRef.current;if(!current)return;const sec=current.sections.find(x=>x.id===activeBlock?.sectionId)||current.sections[0];const header=window.prompt(t(ar,'Header','الرأس'),sec?.header||current.page.header||'');const footer=window.prompt(t(ar,'Footer','التذييل'),sec?.footer||current.page.footer||'');const first=window.confirm(t(ar,'Use a different first page?','استخدام رأس/تذييل مختلف للصفحة الأولى؟'));commit(updatePageSettings(current,{header:header||'',footer:footer||'',differentFirstPage:first,showPageNumbers:true}));if(sec)commit(updateSection(docRef.current||current,sec.id,{header:header||'',footer:footer||'',differentFirstPage:first}));};
 const addEquationPrompt=()=>{const current=docRef.current;if(current){const v=window.prompt(t(ar,'Equation (LaTeX-like text)','المعادلة (صيغة شبيهة بـ LaTeX)'),'x = \frac{-b \pm \sqrt{b^2-4ac}}{2a}');if(v)commit(insertEquation(current,v,activeBlock?.id));}};
 const addSymbolPrompt=()=>{const current=docRef.current;if(current){const v=window.prompt(t(ar,'Symbol','الرمز'),'©');if(v)commit(insertSymbol(current,v,activeBlock?.id));}};
 const addCitationPrompt=()=>{const current=docRef.current;if(!current)return;const source=window.prompt(t(ar,'Source / identifier','المصدر / المعرّف'),'');if(!source)return;const author=window.prompt(t(ar,'Author','المؤلف'),'');const year=window.prompt(t(ar,'Year','السنة'),'');commit(addCitation(current,{source,author:author||undefined,year:year||undefined},activeBlock?.id));};
 const addCaptionPrompt=()=>{const current=docRef.current;if(!current||!activeBlock)return;const label=window.prompt(t(ar,'Caption label','نوع التسمية'),'Figure')||'Figure';const text=window.prompt(t(ar,'Caption text','نص التسمية'),'')||'';commit(addCaption(current,activeBlock.id,label,text));};
 const addCrossRefPrompt=()=>{const current=docRef.current;if(!current)return;const target=window.prompt(t(ar,'Target block ID','معرّف العنصر الهدف'),activeBlock?.id||'');if(!target)return;const name=window.prompt(t(ar,'Reference name','اسم المرجع'),'ref-'+(current.crossReferences.length+1))||'Reference';commit(addCrossReference(current,target,name,'label'));};
 const addIndexPrompt=()=>{const current=docRef.current;if(current&&activeBlock){const term=window.prompt(t(ar,'Index term','مصطلح الفهرس'),'');if(term)commit(addIndexEntry(current,activeBlock.id,term));}};
 const imageOptions=()=>{const current=docRef.current;if(!current||activeBlock?.type!=='image'||!activeBlock.image)return;const rotation=Number(window.prompt(t(ar,'Rotation degrees','زاوية الدوران'),String(activeBlock.image.rotation??0)));const wrap=window.prompt(t(ar,'Wrap: inline/square/tight/through/top-bottom/behind/front','التفاف: inline/square/tight/through/top-bottom/behind/front'),activeBlock.image.wrap||'inline') as any;const anchor=window.prompt(t(ar,'Anchor: paragraph/page/margin','تثبيت: paragraph/page/margin'),activeBlock.image.anchor||'paragraph') as any;commit(updateImage(current,activeBlock.id,{...activeBlock.image,rotation:Number.isFinite(rotation)?rotation:0,wrap,anchor}));};
 const tableOptions=()=>{const current=docRef.current;if(!current||activeBlock?.type!=='table'||!activeBlock.table)return;const headerRows=Number(window.prompt(t(ar,'Header rows','صفوف الرأس'),String(activeBlock.table.headerRows||0)));const repeat=window.confirm(t(ar,'Repeat header row on each page?','تكرار صف الرأس في كل صفحة؟'));const allow=window.confirm(t(ar,'Allow rows to split across pages?','السماح بانقسام الصفوف عبر الصفحات؟'));commit(updateTableOptions(current,activeBlock.id,{...activeBlock.table,headerRows:Number.isFinite(headerRows)?headerRows:0,repeatHeaderRow:repeat,allowRowBreak:allow}));};
 const configureColumns=(columns:number)=>{const current=docRef.current;if(!current)return;const secId=activeBlock?.sectionId||current.sections[0]?.id;if(secId)commit(updateSection(current,secId,{columns:Math.max(1,Math.min(4,columns))}));};
 const configureSectionBreak=()=>{const current=docRef.current;if(current)commit(insertSectionBreak(current,activeBlock?.id,2));};
 const configureHeaderFooter=()=>{const current=docRef.current;if(!current)return;const sec=current.sections.find(x=>x.id===activeBlock?.sectionId)||current.sections[0];const header=window.prompt(t(ar,'Header','الرأس'),sec?.header||current.page.header||'');const footer=window.prompt(t(ar,'Footer','التذييل'),sec?.footer||current.page.footer||'');const first=window.confirm(t(ar,'Use a different first page?','استخدام رأس/تذييل مختلف للصفحة الأولى؟'));let next=updatePageSettings(current,{header:header||'',footer:footer||'',differentFirstPage:first,showPageNumbers:true});if(sec)next=updateSection(next,sec.id,{header:header||'',footer:footer||'',differentFirstPage:first});commit(next);};
 const addEquationPrompt=()=>{const current=docRef.current;if(current){const v=window.prompt(t(ar,'Equation (LaTeX-like text)','المعادلة (صيغة شبيهة بـ LaTeX)'),'x = (-b ± √(b²-4ac)) / 2a');if(v)commit(insertEquation(current,v,activeBlock?.id));}};
 const addSymbolPrompt=()=>{const current=docRef.current;if(current){const v=window.prompt(t(ar,'Symbol','الرمز'),'©');if(v)commit(insertSymbol(current,v,activeBlock?.id));}};
 const addCitationPrompt=()=>{const current=docRef.current;if(!current)return;const source=window.prompt(t(ar,'Source / identifier','المصدر / المعرّف'),'');if(!source)return;const author=window.prompt(t(ar,'Author','المؤلف'),'');const year=window.prompt(t(ar,'Year','السنة'),'');commit(addCitation(current,{source,author:author||undefined,year:year||undefined},activeBlock?.id));};
 const addCaptionPrompt=()=>{const current=docRef.current;if(!current||!activeBlock)return;const label=window.prompt(t(ar,'Caption label','نوع التسمية'),'Figure')||'Figure';const text=window.prompt(t(ar,'Caption text','نص التسمية'),'')||'';commit(addCaption(current,activeBlock.id,label,text));};
 const addCrossRefPrompt=()=>{const current=docRef.current;if(!current)return;const target=window.prompt(t(ar,'Target block ID','معرّف العنصر الهدف'),activeBlock?.id||'');if(!target)return;const name=window.prompt(t(ar,'Reference name','اسم المرجع'),'ref-'+(current.crossReferences.length+1))||'Reference';commit(addCrossReference(current,target,name,'label'));};
 const addIndexPrompt=()=>{const current=docRef.current;if(current&&activeBlock){const term=window.prompt(t(ar,'Index term','مصطلح الفهرس'),'');if(term)commit(addIndexEntry(current,activeBlock.id,term));}};
 const imageOptions=()=>{const current=docRef.current;if(!current||activeBlock?.type!=='image'||!activeBlock.image)return;const rotation=Number(window.prompt(t(ar,'Rotation degrees','زاوية الدوران'),String(activeBlock.image.rotation??0)));const wrap=window.prompt(t(ar,'Wrap: inline/square/tight/through/top-bottom/behind/front','التفاف: inline/square/tight/through/top-bottom/behind/front'),activeBlock.image.wrap||'inline') as any;const anchor=window.prompt(t(ar,'Anchor: paragraph/page/margin','تثبيت: paragraph/page/margin'),activeBlock.image.anchor||'paragraph') as any;commit(updateImage(current,activeBlock.id,{...activeBlock.image,rotation:Number.isFinite(rotation)?rotation:0,wrap,anchor}));};
 const tableOptions=()=>{const current=docRef.current;if(!current||activeBlock?.type!=='table'||!activeBlock.table)return;const headerRows=Number(window.prompt(t(ar,'Header rows','صفوف الرأس'),String(activeBlock.table.headerRows||0)));const repeat=window.confirm(t(ar,'Repeat header row on each page?','تكرار صف الرأس في كل صفحة؟'));const allow=window.confirm(t(ar,'Allow rows to split across pages?','السماح بانقسام الصفوف عبر الصفحات؟'));commit(updateTableOptions(current,activeBlock.id,{...activeBlock.table,headerRows:Number.isFinite(headerRows)?headerRows:0,repeatHeaderRow:repeat,allowRowBreak:allow}));};
 const pageSettings=()=>{const current=docRef.current;if(!current)return;const page=current.page;const size=window.prompt(t(ar,'Page size: A4, LETTER, LEGAL or CUSTOM','حجم الصفحة: A4 أو LETTER أو LEGAL أو CUSTOM'),page.size);if(!size)return;const orientation=window.prompt(t(ar,'Orientation: portrait or landscape','الاتجاه: portrait أو landscape'),page.orientation);const margin=window.prompt(t(ar,'Margins in mm (top,right,bottom,left)','الهوامش بالملليمتر (علوي، يمين، سفلي، يسار)'),`${page.marginTopMm},${page.marginRightMm},${page.marginBottomMm},${page.marginLeftMm}`);const header=window.prompt(t(ar,'Header text','نص الرأس'),page.header??'');const footer=window.prompt(t(ar,'Footer text','نص التذييل'),page.footer??'');const format=window.prompt(t(ar,'Page number format: decimal/roman-lower/roman-upper/letter-upper/letter-lower','تنسيق رقم الصفحة: decimal/roman-lower/roman-upper/letter-upper/letter-lower'),page.pageNumberFormat||'decimal') as any;const start=Number(window.prompt(t(ar,'Page number start','بداية ترقيم الصفحات'),String(page.pageNumberStart||1)));const first=window.confirm(t(ar,'Different first page?','صفحة أولى مختلفة؟'));const oddEven=window.confirm(t(ar,'Different odd/even pages?','صفحات فردية/زوجية مختلفة؟'));const m=(margin??'').split(',').map(Number);commit(updatePageSettings(current,{size:size.toUpperCase() as any,orientation:orientation==='landscape'?'landscape':'portrait',marginTopMm:m[0]||page.marginTopMm,marginRightMm:m[1]||page.marginRightMm,marginBottomMm:m[2]||page.marginBottomMm,marginLeftMm:m[3]||page.marginLeftMm,header:header??'',footer:footer??'',showPageNumbers:true,pageNumberFormat:format,pageNumberStart:Number.isFinite(start)?start:1,differentFirstPage:first,differentOddEven:oddEven}));};
 const addReviewComment=()=>{const current=docRef.current;if(!current||!activeBlockId||!commentDraft.trim())return;commit(addComment(current,activeBlockId,commentDraft,{name:'You'}));setCommentDraft('');};
 const saveReviewSnapshot=()=>{const current=docRef.current;if(!current)return;commit(addSnapshot(current,revision));};
 const visibleComments=doc.review.comments.filter(c=>!c.deleted && (commentFilter==='all'||(commentFilter==='open'&&!c.resolved)||(commentFilter==='resolved'&&c.resolved)));
 const visibleChanges=doc.review.changes.filter(c=>changeFilter==='all'||c.status===changeFilter);
 const acceptAll=()=>commit(acceptAllChanges(doc));
 const rejectAll=()=>commit(rejectAllChanges(doc));
 const changePreview=(id:string)=>{const current=docRef.current;const c=current?.review.changes.find(x=>x.id===id);return c?`${textOfRuns(c.before).slice(0,180)} → ${textOfRuns(c.after).slice(0,180)}`:'';};
 const compareRows=doc?compareSnapshot(doc,compareId):[];
 if(!doc)return <div className="flex h-screen items-center justify-center bg-slate-100 text-sm text-slate-500">{error||t(ar,'Opening IMKAN Writer…','جارٍ فتح IMKAN Writer…')}</div>;
 const pages=pagesFor(doc);const pageWidth=doc.page.orientation==='landscape'?(doc.page.heightMm??297):(doc.page.widthMm??210);const pageHeight=doc.page.orientation==='landscape'?(doc.page.widthMm??210):(doc.page.heightMm??297);
 return <div dir={ar?'rtl':'ltr'} className="flex h-screen flex-col bg-slate-100 text-slate-800 print:bg-white">
  <OfficeShell type="WRITER" fileId={fileId} title={doc.title} revision={revision} saved={saved} saving={saving} ar={ar} presence={<OfficePresence items={presence} ar={ar}/>}/>
  <header className="flex h-14 shrink-0 items-center justify-between border-b border-slate-200 bg-white px-4 shadow-sm print:hidden"><div className="flex min-w-0 items-center gap-3"><button onClick={()=>router.back()} className="rounded-lg px-3 py-2 text-xs hover:bg-slate-100">← {t(ar,'Back','رجوع')}</button><div className="min-w-0"><div className="truncate text-sm font-semibold">{doc.title}</div><div className="text-[10px] text-slate-400">{saving?t(ar,'Syncing…','جارٍ المزامنة…'):saved?t(ar,'Saved','تم الحفظ'):t(ar,'Unsynced changes','تغييرات غير متزامنة')} · Revision {revision}{writerOfflineQueueCount(fileId)>0?` · ${writerOfflineQueueCount(fileId)} queued`:''}</div></div></div><div className="flex items-center gap-1"><button onClick={undo} disabled={!history.length} className="rounded-md px-2.5 py-1.5 text-xs hover:bg-slate-100 disabled:opacity-30">↶</button><button onClick={redo} disabled={!future.length} className="rounded-md px-2.5 py-1.5 text-xs hover:bg-slate-100 disabled:opacity-30">↷</button><OfficePresence items={presence} ar={ar}/><OfficeTransferControls fileId={fileId} type="WRITER" ar={ar}/><button onClick={()=>window.print()} className="rounded-md px-2.5 py-1.5 text-xs hover:bg-slate-100">{t(ar,'Print','طباعة')}</button><button onClick={()=>doc&&commit(addParagraph(doc,activeBlock?.id))} className="rounded-lg bg-[var(--wd-primary)] px-3 py-2 text-xs font-medium text-white">+ {t(ar,'Paragraph','فقرة')}</button></div></header>
  <OfficeRibbon type="WRITER" ar={ar} saved={saved} saving={saving} presence={<OfficePresence items={presence} ar={ar}/>} actions={{undo,redo,bold:()=>applyCommand('bold'),italic:()=>applyCommand('italic'),underline:()=>applyCommand('underline'),find:()=>setFindOpen(v=>!v),table:()=>doc&&commit(insertTable(doc,3,3,activeBlock?.id)),image:addImage,'pagebreak':()=>doc&&commit(insertPageBreak(doc,activeBlock?.id)),toc:()=>doc&&commit(insertTableOfContents(doc,activeBlock?.id)),bookmark:askBookmark,footnote:askFootnote,comments:()=>setReviewOpen(true),'trackchanges':()=>doc&&commit(toggleTrackChanges(doc)),snapshot:saveReviewSnapshot,print:()=>window.print(),fullscreen:()=>document.documentElement.requestFullscreen?.(),columns:()=>configureColumns(2),section:configureSectionBreak,header:configureHeaderFooter,equation:addEquationPrompt,symbol:addSymbolPrompt,cite:addCitationPrompt,caption:addCaptionPrompt,ref:addCrossRefPrompt,index:addIndexPrompt,bibliography:()=>doc&&commit(insertBibliography(doc,activeBlock?.id)),autoIndex:()=>doc&&commit(insertIndex(doc,activeBlock?.id))}} />
  <OfficeMobile type="WRITER" ar={ar} undo={undo} redo={redo} bold={()=>applyCommand('bold')} italic={()=>applyCommand('italic')} underline={()=>applyCommand('underline')} find={()=>setFindOpen(v=>!v)} navigation={()=>document.querySelector('main')?.scrollTo({top:0,behavior:'smooth'})} save={()=>{if(docRef.current)persist(docRef.current,docRef.current)}} />
  <OfficeTemplateFields templateId={templateId} ar={ar} onInsert={insertTemplateField} />

  <div className="print:hidden"><WriterToolbar activeBlock={activeBlock} onCommand={applyCommand} onBlockType={type=>activeBlock&&commit(setBlockType(doc,activeBlock.id,type))} onAlign={align=>activeBlock&&commit(setBlockAlignment(doc,activeBlock.id,align))} onInsertTable={()=>doc&&commit(insertTable(doc,3,3,activeBlock?.id))} onInsertImage={addImage} onPageBreak={()=>doc&&commit(insertPageBreak(doc,activeBlock?.id))} onPageSettings={pageSettings} onLink={insertLink} onFontFamily={v=>applyRunPatch({fontFamily:v})} onFontSize={v=>applyRunPatch({fontSize:v})} onColor={v=>applyRunPatch({color:v})} onHighlight={v=>applyRunPatch({highlight:v})} onVerticalAlign={v=>applyRunPatch({verticalAlign:v})} onList={v=>activeBlock&&commit(setListOrdered(doc,activeBlock.id,v))} onTableAction={tableAction} onRule={()=>doc&&commit(insertHorizontalRule(doc,activeBlock?.id))} onIndent={()=>activeBlock&&commit(updateBlockLayout(doc,activeBlock.id,{indentLeftMm:Math.min(100,(activeBlock.indentLeftMm??0)+10)}))} onOutdent={()=>activeBlock&&commit(updateBlockLayout(doc,activeBlock.id,{indentLeftMm:Math.max(0,(activeBlock.indentLeftMm??0)-10)}))} onToc={()=>doc&&commit(insertTableOfContents(doc,activeBlock?.id))} onBookmark={askBookmark} onFootnote={askFootnote} onFind={()=>setFindOpen(v=>!v)} onColumns={configureColumns} onSectionBreak={configureSectionBreak} onHeaderFooter={configureHeaderFooter} onEquation={addEquationPrompt} onSymbol={addSymbolPrompt} onCitation={addCitationPrompt} onCaption={addCaptionPrompt} onCrossReference={addCrossRefPrompt} onIndex={addIndexPrompt} onBibliography={()=>doc&&commit(insertBibliography(doc,activeBlock?.id))} onAutoIndex={()=>doc&&commit(insertIndex(doc,activeBlock?.id))} onImageOptions={imageOptions} onTableOptions={tableOptions}/></div>
  {findOpen&&<div className="mx-3 mb-3 flex flex-wrap items-center gap-2 rounded-xl border border-slate-200 bg-white p-3 shadow-sm print:hidden"><input value={findTerm} onChange={e=>setFindTerm(e.target.value)} placeholder={t(ar,'Find text','ابحث عن نص')} className="w-48 rounded-md border px-3 py-2 text-xs"/><input value={replaceTerm} onChange={e=>setReplaceTerm(e.target.value)} placeholder={t(ar,'Replace with','استبدال بـ')} className="w-48 rounded-md border px-3 py-2 text-xs"/><button onClick={doReplaceAll} className="rounded-md bg-[var(--wd-primary)] px-3 py-2 text-xs text-white">{t(ar,'Replace all','استبدال الكل')}</button><button onClick={()=>{if(findTerm){const el=document.querySelector(`[data-writer-block]`) as HTMLElement|null; if(el){const r=document.createRange();const w=document.createTreeWalker(el,NodeFilter.SHOW_TEXT);let n;while(n=w.nextNode()){const i=n.textContent?.toLowerCase().indexOf(findTerm.toLowerCase())??-1;if(i>=0){r.setStart(n,i);r.setEnd(n,i+findTerm.length);const sel=window.getSelection();sel?.removeAllRanges();sel?.addRange(r);break;}}}}}} className="rounded-md border px-3 py-2 text-xs">{t(ar,'Find next','التالي')}</button><span className="ms-auto text-[11px] text-slate-400">{wordStats.words} {t(ar,'words','كلمة')} · {wordStats.chars} {t(ar,'characters','حرف')}</span></div>}
  {reviewOpen&&<aside className="mx-3 mb-3 rounded-xl border border-slate-200 bg-white shadow-sm print:hidden">
    <div className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-100 px-4 py-2"><div className="flex gap-1"><button onClick={()=>setReviewTab('comments')} className={`rounded-md px-3 py-1.5 text-xs ${reviewTab==='comments'?'bg-slate-100 font-semibold':''}`}>{t(ar,'Comments','التعليقات')} ({doc.review.comments.filter(c=>!c.resolved&&!c.deleted).length})</button><button onClick={()=>setReviewTab('changes')} className={`rounded-md px-3 py-1.5 text-xs ${reviewTab==='changes'?'bg-slate-100 font-semibold':''}`}>{t(ar,'Changes','التغييرات')} ({doc.review.changes.filter(c=>c.status==='pending').length})</button><button onClick={()=>setReviewTab('compare')} className={`rounded-md px-3 py-1.5 text-xs ${reviewTab==='compare'?'bg-slate-100 font-semibold':''}`}>{t(ar,'Compare','مقارنة')}</button></div><div className="flex flex-wrap gap-2"><button onClick={()=>commit(toggleTrackChanges(doc))} className={`rounded-md border px-3 py-1.5 text-xs ${doc.review.trackChanges?'border-amber-300 bg-amber-50 text-amber-800':''}`}>{doc.review.trackChanges?t(ar,'Track Changes: ON','تتبع التغييرات: مفعل'):t(ar,'Track Changes: OFF','تتبع التغييرات: متوقف')}</button><select value={doc.review.displayMode||'all'} onChange={e=>commit(setReviewDisplayMode(doc,e.target.value as any))} className="rounded border px-2 py-1 text-xs"><option value="all">{t(ar,'All Markup','كل العلامات')}</option><option value="simple">{t(ar,'Simple Markup','علامات مبسطة')}</option><option value="original">{t(ar,'Original','الأصل')}</option></select><button onClick={saveReviewSnapshot} className="rounded-md border px-3 py-1.5 text-xs">{t(ar,'Snapshot','لقطة')}</button></div></div>
    <div className="max-h-64 overflow-auto p-4">
      {reviewTab==='comments'&&<div className="space-y-3"><div className="flex flex-wrap gap-2"><input value={commentDraft} onChange={e=>setCommentDraft(e.target.value)} placeholder={t(ar,'Comment… Use @name to mention','تعليق… استخدم @الاسم للإشارة')} className="min-w-0 flex-1 rounded-md border px-3 py-2 text-xs"/><button onClick={addReviewComment} className="rounded-md bg-[var(--wd-primary)] px-3 py-2 text-xs text-white">{t(ar,'Add comment','إضافة تعليق')}</button><select value={commentFilter} onChange={e=>setCommentFilter(e.target.value as any)} className="rounded border px-2 py-2 text-xs"><option value="open">{t(ar,'Open','مفتوحة')}</option><option value="resolved">{t(ar,'Resolved','محلولة')}</option><option value="all">{t(ar,'All','الكل')}</option></select></div>{visibleComments.length===0?<div className="text-xs text-slate-400">{t(ar,'No comments in this view.','لا توجد تعليقات في هذا العرض.')}</div>:visibleComments.slice().reverse().map(c=><div key={c.id} className={`rounded-lg border p-3 ${c.resolved?'opacity-60':''}`}><div className="flex items-center justify-between"><div className="text-xs font-medium">{c.authorName||t(ar,'You','أنت')}</div><span className="text-[10px] text-slate-400">{new Date(c.createdAt).toLocaleString()}</span></div><div className="mt-1 text-xs whitespace-pre-wrap">{c.text}</div>{c.mentions?.length?<div className="mt-1 text-[10px] text-blue-600">{t(ar,'Mentions:','الإشارات:')} {c.mentions.map(x=>'@'+x).join(', ')}</div>:null}<div className="mt-2 flex gap-2"><button onClick={()=>commit(toggleCommentResolved(doc,c.id))} className="text-[11px] text-slate-500">{c.resolved?t(ar,'Reopen','إعادة فتح'):t(ar,'Resolve','حل')}</button><button onClick={()=>setActiveBlockId(c.blockId)} className="text-[11px] text-[var(--wd-primary)]">{t(ar,'Go to text','انتقل للنص')}</button><button onClick={()=>commit(deleteComment(doc,c.id))} className="text-[11px] text-red-500">{t(ar,'Delete','حذف')}</button></div>{c.replies?.map(r=><div key={r.id} className="mt-2 rounded bg-slate-50 p-2 text-[11px]"><b>{r.authorName||t(ar,'You','أنت')}:</b> {r.text}</div>)}<div className="mt-2 flex gap-2"><input value={replyDraft[c.id]||''} onChange={e=>setReplyDraft(x=>({...x,[c.id]:e.target.value}))} placeholder={t(ar,'Reply…','رد…')} className="flex-1 rounded border px-2 py-1 text-[11px]"/><button onClick={()=>{commit(replyComment(doc,c.id,replyDraft[c.id]||'',{name:'You'}));setReplyDraft(x=>({...x,[c.id]:''}));}} className="text-[11px]">↵</button></div></div>)}</div>}
      {reviewTab==='changes'&&<div className="space-y-2"><div className="flex flex-wrap gap-2"><select value={changeFilter} onChange={e=>setChangeFilter(e.target.value as any)} className="rounded border px-2 py-1 text-xs"><option value="pending">{t(ar,'Pending','معلقة')}</option><option value="accepted">{t(ar,'Accepted','مقبولة')}</option><option value="rejected">{t(ar,'Rejected','مرفوضة')}</option><option value="all">{t(ar,'All','الكل')}</option></select><button onClick={acceptAll} className="rounded border px-2 py-1 text-[11px]">{t(ar,'Accept all','قبول الكل')}</button><button onClick={rejectAll} className="rounded border px-2 py-1 text-[11px]">{t(ar,'Reject all','رفض الكل')}</button><label className="flex items-center gap-1 text-[11px]"><input type="checkbox" checked={doc.review.showFormattingChanges!==false} onChange={e=>commit(setShowFormattingChanges(doc,e.target.checked))}/> {t(ar,'Formatting','التنسيق')}</label></div>{visibleChanges.length===0?<div className="text-xs text-slate-400">{t(ar,'No changes in this view.','لا توجد تغييرات في هذا العرض.')}</div>:visibleChanges.slice().reverse().map(c=><div key={c.id} className="rounded-lg border p-3"><div className="flex justify-between text-[11px] font-medium"><span>{c.kind.toUpperCase()} · {c.authorName||t(ar,'You','أنت')}</span><span>{c.status}</span></div><div className="mt-1 text-xs text-slate-600"><del className="text-red-600">{textOfRuns(c.before).slice(0,180)}</del> <span>→</span> <ins className="text-green-700">{textOfRuns(c.after).slice(0,180)}</ins></div>{c.status==='pending'&&<div className="mt-2 flex gap-2"><button onClick={()=>commit(acceptChange(doc,c.id))} className="rounded border px-2 py-1 text-[11px]">{t(ar,'Accept','قبول')}</button><button onClick={()=>commit(rejectChange(doc,c.id))} className="rounded border px-2 py-1 text-[11px]">{t(ar,'Reject','رفض')}</button></div>}</div>)}</div>}
      {reviewTab==='compare'&&<div className="space-y-3"><div className="flex gap-2"><select value={compareId} onChange={e=>setCompareId(e.target.value)} className="flex-1 rounded border px-2 py-2 text-xs"><option value="">{t(ar,'Select snapshot','اختر لقطة')}</option>{doc.review.snapshots.slice().reverse().map(s=><option key={s.id} value={s.id}>Revision {s.revision} · {new Date(s.createdAt).toLocaleString()}</option>)}</select></div>{compareRows.length===0?<div className="text-xs text-slate-400">{compareId?t(ar,'No textual differences.','لا توجد فروقات نصية.'):t(ar,'Choose a snapshot to compare.','اختر لقطة للمقارنة.')}</div>:compareRows.map(r=><div key={r.blockId} className="grid gap-2 md:grid-cols-2"><div className="rounded border bg-red-50 p-2 text-xs">{r.before||'∅'}</div><div className="rounded border bg-green-50 p-2 text-xs">{r.after||'∅'}</div></div>)}</div>}
    </div>
  </aside>}
  {error&&<div className="m-3 rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-xs text-red-700 print:hidden">{error}</div>}
  <main id="office-main" className="min-h-0 flex-1 overflow-auto p-6 md:p-10 print:overflow-visible print:p-0">
   <div className="mx-auto flex flex-col items-center gap-8">
    {pages.map((pageBlocks,pageIndex)=><section key={pageIndex} className="writer-page relative bg-white shadow-sm print:shadow-none" style={{width:`${pageWidth}mm`,minHeight:`${pageHeight}mm`,padding:`${doc.page.marginTopMm}mm ${doc.page.marginRightMm}mm ${doc.page.marginBottomMm}mm ${doc.page.marginLeftMm}mm`,fontFamily:'Arial, sans-serif'}}>
      {(()=>{const sec=sectionForBlock(doc,pageBlocks[0]||doc.blocks[0]);const first=doc.page.differentFirstPage&&pageIndex===0;const odd=(pageIndex+1)%2===1;const header=first?(sec?.firstHeader??''):(doc.page.differentOddEven?(odd?(sec?.oddHeader??sec?.header??doc.page.header):(sec?.evenHeader??sec?.header??doc.page.header)):(sec?.header??doc.page.header));return (header||doc.page.showPageNumbers)?<div className="mb-5 flex items-center justify-between border-b border-slate-100 pb-2 text-[9px] text-slate-400"><span>{header}</span><span>{doc.page.showPageNumbers?`${t(ar,'Page','صفحة')} ${formatPageNumber((sec?.pageNumberStart??doc.page.pageNumberStart??1)+pageIndex,sec?.pageNumberFormat??doc.page.pageNumberFormat)}`:''}</span></div>:null;})()}
      <div style={{columnCount:Math.max(1,Math.min(4,doc.sections.find(sec=>sec.id===pageBlocks[0]?.sectionId)?.columns||doc.sections[0]?.columns||1)),columnGap:`${doc.sections.find(sec=>sec.id===pageBlocks[0]?.sectionId)?.columnGapMm||8}mm`}}>{pageBlocks.map((block,index)=><div key={block.id} className="group relative" style={{textAlign:block.align==='start'?(ar?'right':'left'):block.align==='end'?(ar?'left':'right'):block.align,marginTop:block.spaceBefore??0,marginBottom:block.spaceAfter??8,lineHeight:block.lineSpacing??1.5,marginLeft:block.indentLeftMm?`${block.indentLeftMm}mm`:undefined,marginRight:block.indentRightMm?`${block.indentRightMm}mm`:undefined,textIndent:block.firstLineIndentMm?`${block.firstLineIndentMm}mm`:undefined}}>
       {block.type==='list-item'&&<span className="absolute -start-7 top-1 text-slate-500">{block.ordered?`${index+1}.`:'•'}</span>}
       {block.type==='table'&&block.table?<table className={`w-full border-collapse ${block.table.bordered?'border border-slate-400':''}`}><tbody>{block.table.rows.map((row,r)=><tr key={r} style={{breakInside:block.table?.allowRowBreak===false?'avoid':'auto'}}>{row.map((cell,c)=><td key={cell.id} colSpan={cell.colSpan||1} rowSpan={cell.rowSpan||1} className={block.table?.bordered?'border border-slate-300 px-2 py-1':''} style={{verticalAlign:cell.verticalAlign==='middle'?'middle':cell.verticalAlign==='bottom'?'bottom':'top'}}>{r<(block.table.headerRows||0)?<strong><div contentEditable role="textbox" aria-multiline="true" aria-label={t(ar,'Table cell','خلية جدول')} suppressContentEditableWarning onFocus={()=>setActiveBlockId(block.id)} onInput={e=>updateTableCell(block.id,r,c,e.currentTarget)} className="min-h-6 rounded px-1 outline-none focus:bg-slate-50" dangerouslySetInnerHTML={{__html:htmlForRuns(cell.runs)}} /></strong>:<div contentEditable role="textbox" aria-multiline="true" aria-label={t(ar,'Table cell','خلية جدول')} suppressContentEditableWarning onFocus={()=>setActiveBlockId(block.id)} onInput={e=>updateTableCell(block.id,r,c,e.currentTarget)} className="min-h-6 rounded px-1 outline-none focus:bg-slate-50" dangerouslySetInnerHTML={{__html:htmlForRuns(cell.runs)}} />}{cell.nestedTable&&<table className="mt-2 w-full border-collapse border border-slate-300"><tbody>{cell.nestedTable.rows.map((nr,ni)=><tr key={ni}>{nr.map(nc=><td key={nc.id} className="border border-slate-200 p-1 text-xs" dangerouslySetInnerHTML={{__html:htmlForRuns(nc.runs)}} />)}</tr>)}</tbody></table>}</td>)}</tr>)}</tbody></table>
       :block.type==='equation'?<div className="my-3 rounded-lg bg-slate-50 px-4 py-3 text-center font-mono text-lg">{block.runs.map(r=>r.text).join('')}</div>
       :block.type==='symbol'?<div className="my-2 text-center text-2xl">{block.runs.map(r=>r.text).join('')}</div>
       :block.type==='bibliography'?<div className="my-4"><h2 className="mb-2 text-xl font-bold">Bibliography</h2>{doc.citations.map((c,i)=><div key={c.id} className="mb-1 text-sm">{i+1}. {[c.author,c.year,c.title,c.source,c.url].filter(Boolean).join('. ')}</div>)}</div>
       :block.type==='index'?<div className="my-4"><h2 className="mb-2 text-xl font-bold">Index</h2>{[...doc.indexEntries].sort((a,b)=>a.term.localeCompare(b.term)).map(e=><div key={e.id} className="text-sm">{e.term}{e.subentry?` — ${e.subentry}`:''}</div>)}</div>
       :block.type==='image'&&block.image?<img src={block.image.src} alt={block.image.alt??''} style={imageStyle(block)} className="rounded-sm" onError={()=>setError(t(ar,'Unable to load this image.','تعذر تحميل هذه الصورة.'))}/>
       :<div data-writer-block={block.id} contentEditable role="textbox" aria-multiline="true" aria-label={t(ar,'Document paragraph','فقرة المستند')} suppressContentEditableWarning spellCheck onFocus={()=>setActiveBlockId(block.id)} onInput={e=>updateBlockRuns(block.id,e.currentTarget)} className={`min-h-8 rounded px-1 outline-none focus:bg-slate-50 ${blockClass(block)}`} dangerouslySetInnerHTML={{__html:htmlForRuns(block.runs)}} />}
       {doc.blocks.length>1&&<button title={t(ar,'Delete block','حذف العنصر')} onMouseDown={e=>e.preventDefault()} onClick={()=>commit(removeBlock(doc,block.id))} className="absolute -end-7 top-1 hidden rounded p-1 text-xs text-slate-300 hover:bg-red-50 hover:text-red-500 group-hover:block print:hidden">×</button>}
      </div>)}
      </div>
      {doc.captions.filter(c=>pageBlocks.some(b=>b.id===c.blockId)).map(c=><div key={c.id} className="mt-1 text-center text-xs text-slate-500">{c.label} {c.number}: {c.text}</div>)}
      {(()=>{const sec=sectionForBlock(doc,pageBlocks[0]||doc.blocks[0]);const first=doc.page.differentFirstPage&&pageIndex===0;const odd=(pageIndex+1)%2===1;const footer=first?(sec?.firstFooter??''):(doc.page.differentOddEven?(odd?(sec?.oddFooter??sec?.footer??doc.page.footer):(sec?.evenFooter??sec?.footer??doc.page.footer)):(sec?.footer??doc.page.footer));const footnotes=doc.footnotes.filter(f=>pageBlocks.some(b=>b.id===f.blockId));return <>{footnotes.length>0&&<div className="mt-6 border-t pt-2 text-[10px] text-slate-500">{footnotes.map(f=><div key={f.id}><sup>{f.marker}</sup> {f.text}</div>)}</div>}{(footer||doc.page.showPageNumbers)&&<div className="absolute bottom-3 start-0 end-0 px-6 text-center text-[9px] text-slate-400">{footer}{doc.page.showPageNumbers?` · ${t(ar,'Page','صفحة')} ${formatPageNumber((sec?.pageNumberStart??doc.page.pageNumberStart??1)+pageIndex,sec?.pageNumberFormat??doc.page.pageNumberFormat)}`:''}</div>}</>;})()}
    </section>)}
   </div>
  </main>
  <footer className="flex h-8 shrink-0 items-center justify-between border-t border-slate-200 bg-white px-4 text-[10px] text-slate-400 print:hidden"><span>IMKAN Writer · {pages.length} {t(ar,'pages','صفحات')} · {doc.blocks.length} {t(ar,'blocks','عناصر')} · {wordStats.words} {t(ar,'words','كلمة')}</span><span>{t(ar,'Native page layout · Autosave enabled','تخطيط صفحات أصلي · الحفظ التلقائي مفعل')}</span></footer>
  {conflict&&<OfficeConflictDialog conflict={conflict} queuedCount={writerOfflineQueueCount(fileId)} ar={ar} onKeepLocal={()=>void resolveConflict('local')} onUseRemote={()=>void resolveConflict('remote')} onDismiss={()=>setConflict(null)}/>}
  <style jsx global>{`@media print{@page{size:${pageWidth}mm ${pageHeight}mm;margin:0}.writer-page{break-after:page;page-break-after:always}.writer-page:last-child{break-after:auto;page-break-after:auto}body{background:white!important}}`}</style>
 </div>;
}
