CREATE TABLE `connection_custom_services` (
  `id` CHAR(36) NOT NULL,
  `org_id` CHAR(36) NOT NULL,
  `owner_id` CHAR(36) NOT NULL,
  `name` VARCHAR(191) NOT NULL,
  `link_name` VARCHAR(191) NOT NULL,
  `auth_type` ENUM('OAUTH2','API_KEY','BEARER','BASIC','CUSTOM_HEADER','NONE') NOT NULL,
  `parameter_key` VARCHAR(191) NULL,
  `parameter_label` VARCHAR(191) NULL,
  `parameter_type` VARCHAR(191) NULL,
  `base_url` VARCHAR(1000) NULL,
  `oauth_auth_url` VARCHAR(2000) NULL,
  `oauth_token_url` VARCHAR(2000) NULL,
  `oauth_revoke_url` VARCHAR(2000) NULL,
  `oauth_client_id` TEXT NULL,
  `oauth_client_secret` TEXT NULL,
  `scopes` JSON NULL,
  `default_scopes` JSON NULL,
  `metadata` JSON NULL,
  `status` VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `connection_custom_services_org_id_link_name_key` (`org_id`,`link_name`),
  KEY `connection_custom_services_org_id_status_updated_at_idx` (`org_id`,`status`,`updated_at`),
  KEY `connection_custom_services_org_id_owner_id_idx` (`org_id`,`owner_id`),
  CONSTRAINT `connection_custom_services_org_id_fkey` FOREIGN KEY (`org_id`) REFERENCES `organizations` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `connection_custom_services_owner_id_fkey` FOREIGN KEY (`owner_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
